In [1]:
import numpy as np
import pandas as pd

In [2]:
#this is to help me create a new pipeline for the fia_wec dataset
#also shows how the data gets put into something usable.

#this is currently the data that we're taking a look at, we're only really curious about 2022 since that's the lastest year.
fia_wec_data = pd.read_csv("2012-2022_FIA_WEC_FULL_LAP_DATA.csv", index_col=0)
#have to map the season to str bc of the way it displays. 
fia_wec_data.season = fia_wec_data.season.map(str)
fia_wec_data_2022 = fia_wec_data[fia_wec_data['season'] == "2022"].reset_index(drop=True)
fia_wec_data_2022

c:\Users\trist\AppData\Local\Programs\Python\Python38\lib\site-packages\IPython\core\interactiveshell.py:3369: DtypeWarning: Columns (26,34,52,53,54,55) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,number,driver_number,lap_number,lap_time,lap_improvement,crossing_finish_line_in_pit,s1,s1_improvement,s2,s2_improvement,...,interval,gap,class_interval,class_gap,primary_key,porsche_large,ford_large,t6_large,t7_large,elapsed_s
0,36,3,1,0 days 00:01:54.835000,0,NaN,36.389,0,39.265,0,...,0.000,0.000,0.000,0.000,2022_1_36_3_1,NaN,NaN,NaN,NaN,114.835
1,708,1,1,0 days 00:01:56.849000,0,NaN,38.120,0,39.547,0,...,2.014,2.014,2.014,2.014,2022_1_708_1_1,NaN,NaN,NaN,NaN,116.849
2,8,1,1,0 days 00:01:58.056000,0,NaN,38.549,0,39.777,0,...,0.747,3.221,0.747,2.761,2022_1_8_1_1,NaN,NaN,NaN,NaN,118.056
3,7,2,1,0 days 00:01:58.577000,0,NaN,39.104,0,39.859,0,...,0.521,3.742,0.521,3.282,2022_1_7_2_1,NaN,NaN,NaN,NaN,118.577
4,33,1,1,0 days 00:02:16.601000,0,NaN,49.403,0,43.401,0,...,1.488,21.766,0.000,0.000,2022_1_33_1_1,NaN,NaN,NaN,NaN,136.601
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9787,31,3,103,0 days 00:02:10.406000,0,NaN,37.172,0,60.085,0,...,38.712,66.185,0.000,0.000,2022_2_31_3_103,NaN,NaN,NaN,NaN,21697.237
9788,41,2,103,0 days 00:02:10.761000,0,NaN,36.841,0,60.085,0,...,34.491,100.676,34.491,34.491,2022_2_41_2_103,NaN,NaN,NaN,NaN,21731.728
9789,38,3,103,0 days 00:02:10.164000,0,NaN,36.517,0,59.479,0,...,7.895,108.571,7.895,42.386,2022_2_38_3_103,NaN,NaN,NaN,NaN,21739.623
9790,5,3,103,0 days 00:02:10.573000,0,NaN,36.975,0,59.739,0,...,9.039,117.610,9.039,51.425,2022_2_5_3_103,NaN,NaN,NaN,NaN,21748.662
9791,22,1,103,0 days 00:02:09.552000,0,NaN,36.445,1,59.983,0,...,0.291,117.901,0.291,51.716,2022_2_22_1_103,NaN,NaN,NaN,NaN,21748.953

In [3]:
#reading the new file in, this time it's lemans.
new_data = pd.read_csv('2022_LEMANS.csv', sep = ';')
new_data = new_data.dropna(axis=1, how="all")
#have to strip + and convert the columns in the data
new_data.columns = new_data.columns.str.lower().str.strip()
new_data.columns
new_data

,number,driver_number,lap_number,lap_time,lap_improvement,crossing_finish_line_in_pit,s1,s1_improvement,s2,s2_improvement,...,driver_name,pit_time,class,group,team,manufacturer,flag_at_fl,s1_seconds,s2_seconds,s3_seconds
0,1,3,1,4:06.517,0,NaN,1:01.857,0,1:24.536,0,...,Charles MILESI,NaN,LMP2,NaN,Richard Mille Racing Team,Oreca,GF,61.857,84.536,100.124
1,1,3,2,4:04.662,0,NaN,1:03.788,0,1:22.995,0,...,Charles MILESI,NaN,LMP2,NaN,Richard Mille Racing Team,Oreca,GF,63.788,82.995,97.879
2,1,3,3,3:34.608,0,NaN,33.989,0,1:22.871,0,...,Charles MILESI,NaN,LMP2,NaN,Richard Mille Racing Team,Oreca,GF,33.989,82.871,97.748
3,1,3,4,3:34.350,0,NaN,33.726,0,1:22.626,0,...,Charles MILESI,NaN,LMP2,NaN,Richard Mille Racing Team,Oreca,GF,33.726,82.626,97.998
4,1,3,5,3:35.703,0,NaN,33.791,0,1:22.740,0,...,Charles MILESI,NaN,LMP2,NaN,Richard Mille Racing Team,Oreca,GF,33.791,82.740,99.172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20497,99,2,334,3:51.332,2,NaN,36.484,0,1:28.508,2,...,Alessio PICARIELLO,NaN,LMGTE Am,NaN,Hardpoint Motorsport,Porsche,GF,36.484,88.508,106.340
20498,99,2,335,3:53.092,0,NaN,36.575,0,1:28.727,0,...,Alessio PICARIELLO,NaN,LMGTE Am,NaN,Hardpoint Motorsport,Porsche,GF,36.575,88.727,107.790
20499,99,2,336,3:54.400,0,NaN,37.187,0,1:29.587,0,...,Alessio PICARIELLO,NaN,LMGTE Am,NaN,Hardpoint Motorsport,Porsche,GF,37.187,89.587,107.626
20500,99,2,337,3:55.628,0,NaN,36.866,0,1:29.677,0,...,Alessio PICARIELLO,NaN,LMGTE Am,NaN,Hardpoint Motorsport,Porsche,GF,36.866,89.677,109.085
20501,99,2,338,3:54.413,0,NaN,37.020,0,1:29.530,0,...,Alessio PICARIELLO,NaN,LMGTE Am,NaN,Hardpoint Motorsport,Porsche,FF,37.020,89.530,107.863

In [4]:
#adding season, circuit, round
new_data['season'] = '2022'
new_data['circuit'] = 'LE MANS'
new_data['round'] = 3

In [5]:
#checks what columns we need to add
full_data_columns = pd.DataFrame(fia_wec_data_2022.columns)
full_data_columns['in_new_df'] = fia_wec_data_2022.columns.isin(new_data.columns)
full_data_columns[full_data_columns['in_new_df'] == False]

                  0  in_new_df
28               t6      False
29               t7      False
30          porsche      False
31             ford      False
32          vehicle      False
34          team_no      False
35      lap_time_ms      False
36       lap_time_s      False
37           engine      False
38  driver_stint_no      False
39     driver_stint      False
40    team_stint_no      False
41       team_stint      False
42       elapsed_ms      False
43         position      False
44   class_position      False
45      interval_ms      False
46         interval      False
47              gap      False
48   class_interval      False
49        class_gap      False
50      primary_key      False
51    porsche_large      False
52       ford_large      False
53         t6_large      False
54         t7_large      False
55        elapsed_s      False

In [6]:
#this contains the mapping for the vehicles
fia_wec_engine_mapping = pd.read_csv("fia_wec_engine_mapping.csv", index_col = 0)
#only getting the engine/vec map for 2022
fia_wec_veh_to_eng_2022 = fia_wec_engine_mapping[fia_wec_engine_mapping['season'] == "2022"].reset_index(drop=True)
fia_wec_veh_to_eng_2022 = fia_wec_veh_to_eng_2022.groupby(['manufacturer', 'class', 'vehicle', 'engine']).mean()
fia_wec_veh_to_eng_2022 = fia_wec_veh_to_eng_2022.reset_index().drop('number', axis=1)

In [7]:
#showing what we're merging on, manufacturer + class
new_data.groupby(['manufacturer', 'class']).mean().reset_index()

,manufacturer,class,number,driver_number,lap_number,lap_improvement,s1_improvement,s2_improvement,s3_improvement,kph,top_speed,s1_seconds,s2_seconds,s3_seconds,round
0,Alpine,HYPERCAR,36.000000,2.002762,181.500000,0.005525,0.011050,0.011050,0.011050,214.256906,315.359669,47.650743,86.799765,104.988923,3.0
1,Aston Martin,LMGTE Am,165.444166,2.107905,155.554580,0.007528,0.015056,0.015056,0.015056,196.877290,288.667754,43.751794,95.162202,113.885439,3.0
2,Chevrolet,LMGTE Pro,63.548523,1.962025,120.116034,0.008439,0.016878,0.016878,0.016878,201.532278,294.276793,52.545956,91.880768,111.454806,3.0
3,Ferrari,LMGTE Am,61.549463,2.069716,159.133646,0.006613,0.013227,0.013227,0.013227,194.683494,286.654202,46.954486,96.243648,114.976250,3.0
4,Ferrari,LMGTE Pro,58.963671,1.979924,174.835564,0.005736,0.011472,0.011472,0.011472,200.238528,291.629924,42.503683,94.128170,112.053011,3.0
5,Glickenhaus,HYPERCAR,708.503356,1.900671,186.758389,0.005369,0.010738,0.010738,0.010738,216.212349,321.294631,41.508477,87.063898,103.880332,3.0
6,Ligier,LMP2,27.000000,2.093093,167.000000,0.006006,0.012012,0.012012,0.012012,200.492192,301.984685,57.259003,92.144252,110.627835,3.0
7,Oreca,LMP2,31.877926,2.038974,180.060983,0.005583,0.011166,0.011166,0.011166,210.869047,311.549710,45.699642,88.629473,105.403100,3.0
8,Porsche,LMGTE Am,82.434300,2.109215,160.107509,0.006826,0.013225,0.013652,0.013652,196.345350,290.799317,46.844279,95.056018,114.585049,3.0
9,Porsche,LMGTE Pro,91.498567,2.021490,175.001433,0.005731,0.011461,0.011461,0.011461,200.964040,293.346991,42.529448,93.936128,111.864288,3.0
10,Toyota,HYPERCAR,7.500000,1.985526,190.500000,0.006579,0.011842,0.011842,0.011842,219.223816,323.120526,39.576711,85.839618,102.448426,3.0

In [8]:
#join the two based on the manufacturer/class, left join in case there are any missing/fallouts
new_data = pd.merge(new_data, fia_wec_veh_to_eng_2022, on = ['manufacturer', 'class'], how = 'left')
new_data

,number,driver_number,lap_number,lap_time,lap_improvement,crossing_finish_line_in_pit,s1,s1_improvement,s2,s2_improvement,...,manufacturer,flag_at_fl,s1_seconds,s2_seconds,s3_seconds,season,circuit,round,vehicle,engine
0,1,3,1,4:06.517,0,NaN,1:01.857,0,1:24.536,0,...,Oreca,GF,61.857,84.536,100.124,2022,LE_MANS,3,Oreca 07,Gibson
1,1,3,2,4:04.662,0,NaN,1:03.788,0,1:22.995,0,...,Oreca,GF,63.788,82.995,97.879,2022,LE_MANS,3,Oreca 07,Gibson
2,1,3,3,3:34.608,0,NaN,33.989,0,1:22.871,0,...,Oreca,GF,33.989,82.871,97.748,2022,LE_MANS,3,Oreca 07,Gibson
3,1,3,4,3:34.350,0,NaN,33.726,0,1:22.626,0,...,Oreca,GF,33.726,82.626,97.998,2022,LE_MANS,3,Oreca 07,Gibson
4,1,3,5,3:35.703,0,NaN,33.791,0,1:22.740,0,...,Oreca,GF,33.791,82.740,99.172,2022,LE_MANS,3,Oreca 07,Gibson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20497,99,2,334,3:51.332,2,NaN,36.484,0,1:28.508,2,...,Porsche,GF,36.484,88.508,106.340,2022,LE_MANS,3,Porsche 911 RSR-19,Porsche
20498,99,2,335,3:53.092,0,NaN,36.575,0,1:28.727,0,...,Porsche,GF,36.575,88.727,107.790,2022,LE_MANS,3,Porsche 911 RSR-19,Porsche
20499,99,2,336,3:54.400,0,NaN,37.187,0,1:29.587,0,...,Porsche,GF,37.187,89.587,107.626,2022,LE_MANS,3,Porsche 911 RSR-19,Porsche
20500,99,2,337,3:55.628,0,NaN,36.866,0,1:29.677,0,...,Porsche,GF,36.866,89.677,109.085,2022,LE_MANS,3,Porsche 911 RSR-19,Porsche
20501,99,2,338,3:54.413,0,NaN,37.020,0,1:29.530,0,...,Porsche,FF,37.020,89.530,107.863,2022,LE_MANS,3,Porsche 911 RSR-19,Porsche

In [9]:
#checks what columns we still need to add
full_data_columns = pd.DataFrame(fia_wec_data_2022.columns)
full_data_columns['in_new_df'] = fia_wec_data_2022.columns.isin(new_data.columns)
full_data_columns[full_data_columns['in_new_df'] == False]

                  0  in_new_df
28               t6      False
29               t7      False
30          porsche      False
31             ford      False
34          team_no      False
35      lap_time_ms      False
36       lap_time_s      False
38  driver_stint_no      False
39     driver_stint      False
40    team_stint_no      False
41       team_stint      False
42       elapsed_ms      False
43         position      False
44   class_position      False
45      interval_ms      False
46         interval      False
47              gap      False
48   class_interval      False
49        class_gap      False
50      primary_key      False
51    porsche_large      False
52       ford_large      False
53         t6_large      False
54         t7_large      False
55        elapsed_s      False

In [10]:
#we need: 'team_no', 'lap_time_ms', 'lap_time_s', 'driver_stint_no', 'driver_stint', 'team_stint_no', 'team_stint'
def convert_to_ms(x):
    hour = 0
    try:
        hour, minutes, second = x.split(":")
    except ValueError:
        minutes, second = x.split(":")
    hour_seconds = int(hour)*60*60
    seconds, ms = second.split(".")
    minute_seconds = (int(minutes)*60 + int(seconds) + int(hour_seconds))*1000 
    total_ms = minute_seconds + int(ms)
    return total_ms

#team_no
new_data['team_no'] = new_data['team'] + " #" + new_data['number'].map(int).map(str)

#lap_time_ms + lap_time_s
#we can then apply this function to every single lap time in the df, and convert everything to ms.
new_data['lap_time_ms'] = new_data['lap_time'].apply(convert_to_ms)
#and then let's make a seconds column to plot it neatly later.
new_data['lap_time_s'] = new_data['lap_time_ms']/1000
new_data

,number,driver_number,lap_number,lap_time,lap_improvement,crossing_finish_line_in_pit,s1,s1_improvement,s2,s2_improvement,...,s2_seconds,s3_seconds,season,circuit,round,vehicle,engine,team_no,lap_time_ms,lap_time_s
0,1,3,1,4:06.517,0,NaN,1:01.857,0,1:24.536,0,...,84.536,100.124,2022,LE_MANS,3,Oreca 07,Gibson,Richard Mille Racing Team #1,246517,246.517
1,1,3,2,4:04.662,0,NaN,1:03.788,0,1:22.995,0,...,82.995,97.879,2022,LE_MANS,3,Oreca 07,Gibson,Richard Mille Racing Team #1,244662,244.662
2,1,3,3,3:34.608,0,NaN,33.989,0,1:22.871,0,...,82.871,97.748,2022,LE_MANS,3,Oreca 07,Gibson,Richard Mille Racing Team #1,214608,214.608
3,1,3,4,3:34.350,0,NaN,33.726,0,1:22.626,0,...,82.626,97.998,2022,LE_MANS,3,Oreca 07,Gibson,Richard Mille Racing Team #1,214350,214.350
4,1,3,5,3:35.703,0,NaN,33.791,0,1:22.740,0,...,82.740,99.172,2022,LE_MANS,3,Oreca 07,Gibson,Richard Mille Racing Team #1,215703,215.703
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20497,99,2,334,3:51.332,2,NaN,36.484,0,1:28.508,2,...,88.508,106.340,2022,LE_MANS,3,Porsche 911 RSR-19,Porsche,Hardpoint Motorsport #99,231332,231.332
20498,99,2,335,3:53.092,0,NaN,36.575,0,1:28.727,0,...,88.727,107.790,2022,LE_MANS,3,Porsche 911 RSR-19,Porsche,Hardpoint Motorsport #99,233092,233.092
20499,99,2,336,3:54.400,0,NaN,37.187,0,1:29.587,0,...,89.587,107.626,2022,LE_MANS,3,Porsche 911 RSR-19,Porsche,Hardpoint Motorsport #99,234400,234.400
20500,99,2,337,3:55.628,0,NaN,36.866,0,1:29.677,0,...,89.677,109.085,2022,LE_MANS,3,Porsche 911 RSR-19,Porsche,Hardpoint Motorsport #99,235628,235.628
20501,99,2,338,3:54.413,0,NaN,37.020,0,1:29.530,0,...,89.530,107.863,2022,LE_MANS,3,Porsche 911 RSR-19,Porsche,Hardpoint Motorsport #99,234413,234.413

In [11]:
#getting team and driver stint nos

#we have two different keys for driver and team, this one is for team
new_data['key'] = new_data['season'].map(int).map(str) + "_" + new_data['round'].map(int).map(str) + "_" + new_data['number'].map(int).map(str)

#we take the next lap: next = df shifted by 1 row (starts from lap 2)
new_data_next = new_data.shift(-1).fillna(0)

#check where the driver changes, different from "crossing line in pit" since we know that the driver changes.
new_data['change_driver'] = np.where(new_data['key'] == new_data_next['key'], 0, 1)
new_data['change_driver'] = new_data['change_driver'].shift(1).fillna(0)

#check where the team changes
new_data['change_team'] = np.where(new_data['number'] == new_data_next['number'], 0, 1)
new_data['change_team'] = new_data['change_team'].shift(1).fillna(0)

new_data['change_stint'] = np.where(new_data['crossing_finish_line_in_pit'] == "B", 1, 0)
new_data['change_stint'] = new_data['change_stint'].shift(1).fillna(0)

#here we're creating a dictionary for the keys by pivoting it by these columns
wanted_columns = ['key']
new_data_pivoted = new_data.groupby(wanted_columns).mean().reset_index()[wanted_columns]
new_data_pivoted['team_stint_no'] = 0

wanted_columns = ['key', 'team_stint_no']
new_data_pivoted_wc = new_data_pivoted[wanted_columns]
new_data_pivoted_dict = new_data_pivoted_wc.to_dict('records')

#methods for incrementing and getting values of keys in dictionaries
def search_key_in_dicts(key, dict):
    for d in dict:
        if d['key'] == key:
            return d
    return None
def update_value_in_dicts(key, dict, col, value):
    dict_key = search_key_in_dicts(key, dict)
    dict_key.update({col : value})
def increment_driver_stint_value(key, dict):
    update_value_in_dicts(key, dict, 'driver_stint_no', search_key_in_dicts(key, dict).get('driver_stint_no') + 1)
    return search_key_in_dicts(key, new_data_pivoted_dict).get('driver_stint_no')
def increment_team_stint_value(key,dict):
    update_value_in_dicts(key, dict, 'team_stint_no', search_key_in_dicts(key, dict).get('team_stint_no') + 1)
    return search_key_in_dicts(key, new_data_pivoted_dict).get('team_stint_no')

key = new_data.at[0, 'key']
#zero everything out again, but we need to increment the very first stint
update_value_in_dicts(key, new_data_pivoted_dict, 'team_stint_no', 1)
#getting team_stint_no
new_data['team_stint_no'] = 0
for i in range(0,len(new_data)):
    x = new_data.iloc[i]
    if x['change_stint'] == 1 or x['change_team'] == 1:
        increment_team_stint_value(x.key, new_data_pivoted_dict)
    new_data.at[x.name, 'team_stint_no'] = (search_key_in_dicts(x.key, new_data_pivoted_dict).get('team_stint_no'))

In [12]:
#we need a new key for driver number and driver stint
new_data['key'] = new_data['season'].map(int).map(str) + "_" + new_data['round'].map(int).map(str) + "_" + new_data['number'].map(int).map(str) + "_"+ new_data['driver_number'].map(int).map(str)

#so using the same key parameter we zero it all out again
wanted_columns = ['key']
new_data_pivoted = new_data.groupby(wanted_columns).mean().reset_index()[wanted_columns]
new_data_pivoted['driver_stint_no'] = 0

#and then convert these into a dictionary
wanted_columns = ['key', 'driver_stint_no']
new_data_pivoted_wc = new_data_pivoted[wanted_columns]
new_data_pivoted_dict = new_data_pivoted_wc.to_dict('records')

#zero everything out again, but we need to increment the very first stint
key = new_data.at[0, 'key']
update_value_in_dicts(key, new_data_pivoted_dict, 'driver_stint_no', 1)

new_data['driver_stint_no'] = 0
for i in range(0,len(new_data)):
    x = new_data.iloc[i]
    if x['change_stint'] == 1:
        increment_driver_stint_value(x.key, new_data_pivoted_dict)
    new_data.at[x.name, 'driver_stint_no'] = (search_key_in_dicts(x.key, new_data_pivoted_dict).get('driver_stint_no'))

In [13]:
new_data['driver_stint'] = new_data['driver_name'] + " Stint #" +  new_data['driver_stint_no'].map(int).map(str)
new_data['team_stint'] = new_data['team_no'] + " Stint #" +  new_data['team_stint_no'].map(int).map(str)
#dropping s1_seconds, since the fia wec data seems to add new columns every iteration ;;
new_data = new_data.drop(['change_driver', 'change_team', 'change_stint', 'key', 's1_seconds', 's2_seconds', 's3_seconds'], axis=1)

In [14]:
#checking that team stint + driver stint are right
new_data

,number,driver_number,lap_number,lap_time,lap_improvement,crossing_finish_line_in_pit,s1,s1_improvement,s2,s2_improvement,...,round,vehicle,engine,team_no,lap_time_ms,lap_time_s,team_stint_no,driver_stint_no,driver_stint,team_stint
0,1,3,1,4:06.517,0,NaN,1:01.857,0,1:24.536,0,...,3,Oreca 07,Gibson,Richard Mille Racing Team #1,246517,246.517,1,1,Charles MILESI Stint #1,Richard Mille Racing Team #1 Stint #1
1,1,3,2,4:04.662,0,NaN,1:03.788,0,1:22.995,0,...,3,Oreca 07,Gibson,Richard Mille Racing Team #1,244662,244.662,1,1,Charles MILESI Stint #1,Richard Mille Racing Team #1 Stint #1
2,1,3,3,3:34.608,0,NaN,33.989,0,1:22.871,0,...,3,Oreca 07,Gibson,Richard Mille Racing Team #1,214608,214.608,1,1,Charles MILESI Stint #1,Richard Mille Racing Team #1 Stint #1
3,1,3,4,3:34.350,0,NaN,33.726,0,1:22.626,0,...,3,Oreca 07,Gibson,Richard Mille Racing Team #1,214350,214.350,1,1,Charles MILESI Stint #1,Richard Mille Racing Team #1 Stint #1
4,1,3,5,3:35.703,0,NaN,33.791,0,1:22.740,0,...,3,Oreca 07,Gibson,Richard Mille Racing Team #1,215703,215.703,1,1,Charles MILESI Stint #1,Richard Mille Racing Team #1 Stint #1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20497,99,2,334,3:51.332,2,NaN,36.484,0,1:28.508,2,...,3,Porsche 911 RSR-19,Porsche,Hardpoint Motorsport #99,231332,231.332,25,10,Alessio PICARIELLO Stint #10,Hardpoint Motorsport #99 Stint #25
20498,99,2,335,3:53.092,0,NaN,36.575,0,1:28.727,0,...,3,Porsche 911 RSR-19,Porsche,Hardpoint Motorsport #99,233092,233.092,25,10,Alessio PICARIELLO Stint #10,Hardpoint Motorsport #99 Stint #25
20499,99,2,336,3:54.400,0,NaN,37.187,0,1:29.587,0,...,3,Porsche 911 RSR-19,Porsche,Hardpoint Motorsport #99,234400,234.400,25,10,Alessio PICARIELLO Stint #10,Hardpoint Motorsport #99 Stint #25
20500,99,2,337,3:55.628,0,NaN,36.866,0,1:29.677,0,...,3,Porsche 911 RSR-19,Porsche,Hardpoint Motorsport #99,235628,235.628,25,10,Alessio PICARIELLO Stint #10,Hardpoint Motorsport #99 Stint #25
20501,99,2,338,3:54.413,0,NaN,37.020,0,1:29.530,0,...,3,Porsche 911 RSR-19,Porsche,Hardpoint Motorsport #99,234413,234.413,25,10,Alessio PICARIELLO Stint #10,Hardpoint Motorsport #99 Stint #25

In [15]:
#hour isn't right, so we have to make elapsed/elapsedms
def convert_to_ms(x):
    hour = 0
    try:
        hour, minutes, second = x.split(":")
    except ValueError:
        minutes, second = x.split(":")
    hour_seconds = int(hour)*60*60
    seconds, ms = second.split(".")
    minute_seconds = (int(minutes)*60 + int(seconds) + int(hour_seconds))*1000 
    total_ms = minute_seconds + int(ms)
    return total_ms
new_data['elapsed_ms'] = new_data.elapsed.map(convert_to_ms)
new_data['elapsed_s'] = new_data.elapsed.map(convert_to_ms)/1000
new_data_with_filters_sorted_hour = new_data.sort_values(['round', 'lap_number', 'elapsed_s']).reset_index(drop=True)
new_data_with_filters_sorted_hour

,number,driver_number,lap_number,lap_time,lap_improvement,crossing_finish_line_in_pit,s1,s1_improvement,s2,s2_improvement,...,engine,team_no,lap_time_ms,lap_time_s,team_stint_no,driver_stint_no,driver_stint,team_stint,elapsed_ms,elapsed_s
0,8,1,1,3:58.487,0,NaN,59.016,0,1:21.863,0,...,Toyota,Toyota Gazoo Racing #8,238487,238.487,1,0,Sébastien BUEMI Stint #0,Toyota Gazoo Racing #8 Stint #1,238487,238.487
1,7,1,1,3:59.536,0,NaN,59.498,0,1:21.915,0,...,Toyota,Toyota Gazoo Racing #7,239536,239.536,1,0,Mike CONWAY Stint #0,Toyota Gazoo Racing #7 Stint #1,239536,239.536
2,708,1,1,4:01.913,0,NaN,1:00.159,0,1:21.956,0,...,Pipo Moteurs,Glickenhaus Racing #708,241913,241.913,1,0,Olivier PLA Stint #0,Glickenhaus Racing #708 Stint #1,241913,241.913
3,709,3,1,4:03.814,0,NaN,1:00.408,0,1:22.718,0,...,Pipo Moteurs,Glickenhaus Racing #709,243814,243.814,1,0,Franck MAILLEUX Stint #0,Glickenhaus Racing #709 Stint #1,243814,243.814
4,9,1,1,4:04.291,0,NaN,1:00.657,0,1:23.547,0,...,Gibson,Prema Orlen Team #9,244291,244.291,1,0,Robert KUBICA Stint #0,Prema Orlen Team #9 Stint #1,244291,244.291
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20497,7,3,378,3:32.801,0,NaN,33.645,0,1:20.892,0,...,Toyota,Toyota Gazoo Racing #7,212801,212.801,33,13,Jose Maria LOPEZ Stint #13,Toyota Gazoo Racing #7 Stint #33,86220663,86220.663
20498,8,2,379,3:32.310,0,NaN,33.323,0,1:20.052,0,...,Toyota,Toyota Gazoo Racing #8,212310,212.310,32,12,Brendon HARTLEY Stint #12,Toyota Gazoo Racing #8 Stint #32,86311854,86311.854
20499,7,3,379,3:33.348,0,NaN,34.550,0,1:21.034,0,...,Toyota,Toyota Gazoo Racing #7,213348,213.348,33,13,Jose Maria LOPEZ Stint #13,Toyota Gazoo Racing #7 Stint #33,86434011,86434.011
20500,8,2,380,3:36.142,0,NaN,33.452,0,1:20.406,0,...,Toyota,Toyota Gazoo Racing #8,216142,216.142,32,12,Brendon HARTLEY Stint #12,Toyota Gazoo Racing #8 Stint #32,86527996,86527.996
20501,7,3,380,3:35.207,0,NaN,33.411,0,1:20.843,0,...,Toyota,Toyota Gazoo Racing #7,215207,215.207,33,13,Jose Maria LOPEZ Stint #13,Toyota Gazoo Racing #7 Stint #33,86649218,86649.218

In [16]:
#gets dict for sorted hour by overall
new_data_with_filters_sorted_hour['key'] = new_data_with_filters_sorted_hour['season'] + "_" +  new_data_with_filters_sorted_hour['round'].map(int).map(str) + "_" + new_data_with_filters_sorted_hour['lap_number'].map(int).map(str) 
wanted_columns = ['key', 'round', 'lap_number']
data_keys = new_data_with_filters_sorted_hour.groupby('key').mean().reset_index()[wanted_columns].sort_values(['round','lap_number']).reset_index(drop=True)
data_keys['position'] = 0
data_keys_dict = data_keys.to_dict('records')

def search_key_in_dicts(key, dict):
    for d in dict:
        if d['key'] == key:
            return d
    return None
def update_value_in_dicts(key, dict, col, value):
    dict_key = search_key_in_dicts(key, dict)
    dict_key.update({col : value})
def increment_position(key, dict):
    update_value_in_dicts(key, dict, 'position', search_key_in_dicts(key, dict).get('position') + 1)
    return search_key_in_dicts(key, dict).get('position')
def increment_class_position(key, dict):
    update_value_in_dicts(key, dict, 'class_position', search_key_in_dicts(key, dict).get('class_position') + 1)
    return search_key_in_dicts(key, dict).get('class_position')
    
#loop to run through position, takes a while...
for i in range(0, len(new_data_with_filters_sorted_hour)):
    x = new_data_with_filters_sorted_hour.iloc[i]
    increment_position(x['key'], data_keys_dict)
    new_data_with_filters_sorted_hour.at[i, 'position'] = search_key_in_dicts(x['key'], data_keys_dict).get('position')

In [17]:
#gets dict for sorted hour by class
new_data_with_filters_sorted_hour['key_class'] = new_data_with_filters_sorted_hour['key'] + "_" +  new_data_with_filters_sorted_hour['class']
wanted_columns = ['key_class', 'round', 'lap_number']
data_keys_class = new_data_with_filters_sorted_hour.groupby('key_class').mean().reset_index()[wanted_columns].sort_values(['round','lap_number']).reset_index(drop=True)
data_keys_class['key'] = data_keys_class['key_class']
data_keys_class = data_keys_class.drop(['key_class'], axis=1)
data_keys_class['class_position'] = 0
data_keys_class_dict = data_keys_class.to_dict('records')

#loop to run through position, takes a while...
for i in range(0, len(new_data_with_filters_sorted_hour)):
    x = new_data_with_filters_sorted_hour.iloc[i]
    increment_class_position(x['key_class'], data_keys_class_dict)
    new_data_with_filters_sorted_hour.at[i, 'class_position'] = search_key_in_dicts(x['key_class'], data_keys_class_dict).get('class_position')

In [18]:
data_sorted_by_position = new_data_with_filters_sorted_hour.sort_values(['season','round', 'lap_number', 'position']).reset_index(drop=True)
#full_data_sorted_by_position

#gets interval overall
data_shift_minus_one = data_sorted_by_position.shift(-1)
data_shift_minus_one['interval'] = data_shift_minus_one['elapsed_ms'] - data_sorted_by_position['elapsed_ms']
negative_interval = data_shift_minus_one[data_shift_minus_one['interval'] < 0]
positive_interval = data_shift_minus_one[data_shift_minus_one['interval'] >= 0]
negative_interval.interval = 0
data_shift_minus_one = negative_interval.append(positive_interval).sort_values(['season','round', 'lap_number', 'position']).reset_index(drop=True)
data_sorted_by_position['interval_ms'] = data_shift_minus_one['interval']
data_sorted_by_position['interval_ms'] = data_sorted_by_position['interval_ms'].shift(1, fill_value=0)
data_sorted_by_position['interval'] = data_sorted_by_position['interval_ms']/1000
data_sorted_by_position

c:\Users\trist\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\generic.py:5516: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

,number,driver_number,lap_number,lap_time,lap_improvement,crossing_finish_line_in_pit,s1,s1_improvement,s2,s2_improvement,...,driver_stint,team_stint,elapsed_ms,elapsed_s,key,position,key_class,class_position,interval_ms,interval
0,8,1,1,3:58.487,0,NaN,59.016,0,1:21.863,0,...,Sébastien BUEMI Stint #0,Toyota Gazoo Racing #8 Stint #1,238487,238.487,2022_3_1,1.0,2022_3_1_HYPERCAR,1.0,0.0,0.000
1,7,1,1,3:59.536,0,NaN,59.498,0,1:21.915,0,...,Mike CONWAY Stint #0,Toyota Gazoo Racing #7 Stint #1,239536,239.536,2022_3_1,2.0,2022_3_1_HYPERCAR,2.0,1049.0,1.049
2,708,1,1,4:01.913,0,NaN,1:00.159,0,1:21.956,0,...,Olivier PLA Stint #0,Glickenhaus Racing #708 Stint #1,241913,241.913,2022_3_1,3.0,2022_3_1_HYPERCAR,3.0,2377.0,2.377
3,709,3,1,4:03.814,0,NaN,1:00.408,0,1:22.718,0,...,Franck MAILLEUX Stint #0,Glickenhaus Racing #709 Stint #1,243814,243.814,2022_3_1,4.0,2022_3_1_HYPERCAR,4.0,1901.0,1.901
4,9,1,1,4:04.291,0,NaN,1:00.657,0,1:23.547,0,...,Robert KUBICA Stint #0,Prema Orlen Team #9 Stint #1,244291,244.291,2022_3_1,5.0,2022_3_1_LMP2,1.0,477.0,0.477
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20497,7,3,378,3:32.801,0,NaN,33.645,0,1:20.892,0,...,Jose Maria LOPEZ Stint #13,Toyota Gazoo Racing #7 Stint #33,86220663,86220.663,2022_3_378,2.0,2022_3_378_HYPERCAR,2.0,121119.0,121.119
20498,8,2,379,3:32.310,0,NaN,33.323,0,1:20.052,0,...,Brendon HARTLEY Stint #12,Toyota Gazoo Racing #8 Stint #32,86311854,86311.854,2022_3_379,1.0,2022_3_379_HYPERCAR,1.0,91191.0,91.191
20499,7,3,379,3:33.348,0,NaN,34.550,0,1:21.034,0,...,Jose Maria LOPEZ Stint #13,Toyota Gazoo Racing #7 Stint #33,86434011,86434.011,2022_3_379,2.0,2022_3_379_HYPERCAR,2.0,122157.0,122.157
20500,8,2,380,3:36.142,0,NaN,33.452,0,1:20.406,0,...,Brendon HARTLEY Stint #12,Toyota Gazoo Racing #8 Stint #32,86527996,86527.996,2022_3_380,1.0,2022_3_380_HYPERCAR,1.0,93985.0,93.985
20501,7,3,380,3:35.207,0,NaN,33.411,0,1:20.843,0,...,Jose Maria LOPEZ Stint #13,Toyota Gazoo Racing #7 Stint #33,86649218,86649.218,2022_3_380,2.0,2022_3_380_HYPERCAR,2.0,121222.0,121.222

In [19]:
#this gets gap for overall
new_data_sorted_by_position = data_sorted_by_position.sort_values(['season','round', 'lap_number', 'position'])
new_data_sorted_by_position['gap'] = new_data_sorted_by_position.groupby('key')['interval'].cumsum()
#this sorts it by class and gets interval and gap for class
new_data_sorted_by_position = new_data_sorted_by_position.sort_values(['season','round', 'lap_number', 'class', 'class_position']).reset_index(drop=True)
new_data_sorted_by_position['class_interval'] = np.where(new_data_sorted_by_position['class_position']!=1, new_data_sorted_by_position['interval'], 0)
new_data_sorted_by_position['class_gap'] = new_data_sorted_by_position.groupby('key_class')['class_interval'].cumsum()

In [20]:
new_data_sorted_by_position.head(60)

,number,driver_number,lap_number,lap_time,lap_improvement,crossing_finish_line_in_pit,s1,s1_improvement,s2,s2_improvement,...,elapsed_s,key,position,key_class,class_position,interval_ms,interval,gap,class_interval,class_gap
0,8,1,1,3:58.487,0,NaN,59.016,0,1:21.863,0,...,238.487,2022_3_1,1.0,2022_3_1_HYPERCAR,1.0,0.0,0.000,0.000,0.000,0.000
1,7,1,1,3:59.536,0,NaN,59.498,0,1:21.915,0,...,239.536,2022_3_1,2.0,2022_3_1_HYPERCAR,2.0,1049.0,1.049,1.049,1.049,1.049
2,708,1,1,4:01.913,0,NaN,1:00.159,0,1:21.956,0,...,241.913,2022_3_1,3.0,2022_3_1_HYPERCAR,3.0,2377.0,2.377,3.426,2.377,3.426
3,709,3,1,4:03.814,0,NaN,1:00.408,0,1:22.718,0,...,243.814,2022_3_1,4.0,2022_3_1_HYPERCAR,4.0,1901.0,1.901,5.327,1.901,5.327
4,36,2,1,4:04.707,0,NaN,1:00.945,0,1:23.809,0,...,244.707,2022_3_1,6.0,2022_3_1_HYPERCAR,5.0,416.0,0.416,6.220,0.416,5.743
5,61,3,1,4:36.239,0,NaN,1:16.868,0,1:30.597,0,...,276.239,2022_3_1,34.0,2022_3_1_LMGTE Am,1.0,3641.0,3.641,37.752,0.000,0.000
6,77,3,1,4:36.527,0,NaN,1:17.791,0,1:30.079,0,...,276.527,2022_3_1,35.0,2022_3_1_LMGTE Am,2.0,288.0,0.288,38.040,0.288,0.288
7,57,3,1,4:37.456,0,NaN,1:17.443,0,1:30.471,0,...,277.456,2022_3_1,37.0,2022_3_1_LMGTE Am,3.0,74.0,0.074,38.969,0.074,0.362
8,86,3,1,4:37.902,0,NaN,1:19.070,0,1:30.365,0,...,277.902,2022_3_1,38.0,2022_3_1_LMGTE Am,4.0,446.0,0.446,39.415,0.446,0.808
9,98,3,1,4:38.496,0,NaN,1:18.293,0,1:30.753,0,...,278.496,2022_3_1,39.0,2022_3_1_LMGTE Am,5.0,594.0,0.594,40.009,0.594,1.402
10,54,3,1,4:40.133,0,NaN,1:18.585,0,1:31.175,0,...,280.133,2022_3_1,41.0,2022_3_1_LMGTE Am,6.0,858.0,0.858,41.646,0.858,2.260
11,85,2,1,4:40.481,0,NaN,1:18.819,0,1:31.250,0,...,280.481,2022_3_1,42.0,2022_3_1_LMGTE Am,7.0,348.0,0.348,41.994,0.348,2.608
12,46,1,1,4:40.956,0,NaN,1:19.647,0,1:30.739,0,...,280.956,2022_3_1,43.0,2022_3_1_LMGTE Am,8.0,475.0,0.475,42.469,0.475,3.083
13,99,2,1,4:41.387,0,NaN,1:20.293,0,1:30.459,0,...,281.387,2022_3_1,44.0,2022_3_1_LMGTE Am,9.0,431.0,0.431,42.900,0.431,3.514
14,56,3,1,4:41.805,0,NaN,1:19.318,0,1:31.290,0,...,281.805,2022_3_1,45.0,2022_3_1_LMGTE Am,10.0,418.0,0.418,43.318,0.418,3.932
15,79,2,1,4:42.129,0,NaN,1:19.954,0,1:31.751,0,...,282.129,2022_3_1,46.0,2022_3_1_LMGTE Am,11.0,324.0,0.324,43.642,0.324,4.256
16,59,2,1,4:42.435,0,NaN,1:21.364,0,1:30.655,0,...,282.435,2022_3_1,47.0,2022_3_1_LMGTE Am,12.0,306.0,0.306,43.948,0.306,4.562
17,21,3,1,4:42.992,0,NaN,1:21.742,0,1:30.939,0,...,282.992,2022_3_1,48.0,2022_3_1_LMGTE Am,13.0,557.0,0.557,44.505,0.557,5.119
18,88,3,1,4:43.498,0,NaN,1:22.802,0,1:31.298,0,...,283.498,2022_3_1,49.0,2022_3_1_LMGTE Am,14.0,506.0,0.506,45.011,0.506,5.625
19,55,2,1,4:44.571,0,NaN,1:22.168,0,1:31.957,0,...,284.571,2022_3_1,50.0,2022_3_1_LMGTE Am,15.0,1073.0,1.073,46.084,1.073,6.698
20,75,3,1,4:46.323,0,NaN,1:22.464,0,1:32.383,0,...,286.323,2022_3_1,52.0,2022_3_1_LMGTE Am,16.0,652.0,0.652,47.836,0.652,7.350
21,777,2,1,4:46.833,0,NaN,1:24.675,0,1:31.769,0,...,286.833,2022_3_1,53.0,2022_3_1_LMGTE Am,17.0,510.0,0.510,48.346,0.510,7.860
22,33,3,1,4:47.502,0,NaN,1:25.055,0,1:32.149,0,...,287.502,2022_3_1,54.0,2022_3_1_LMGTE Am,18.0,669.0,0.669,49.015,0.669,8.529
23,93,2,1,4:47.909,0,NaN,1:26.628,0,1:31.677,0,...,287.909,2022_3_1,55.0,2022_3_1_LMGTE Am,19.0,407.0,0.407,49.422,0.407,8.936
24,80,2,1,4:48.800,0,NaN,1:27.317,0,1:32.036,0,...,288.800,2022_3_1,56.0,2022_3_1_LMGTE Am,20.0,891.0,0.891,50.313,0.891,9.827
25,71,2,1,4:51.220,0,NaN,1:28.740,0,1:32.781,0,...,291.220,2022_3_1,57.0,2022_3_1_LMGTE Am,21.0,2420.0,2.420,52.733,2.420,12.247
26,66,2,1,4:56.159,0,NaN,1:24.432,0,1:36.518,0,...,296.159,2022_3_1,58.0,2022_3_1_LMGTE Am,22.0,4939.0,4.939,57.672,4.939,17.186
27,60,1,1,4:59.071,0,NaN,1:28.930,0,1:34.406,0,...,299.071,2022_3_1,59.0,2022_3_1_LMGTE Am,23.0,2912.0,2.912,60.584,2.912,20.098
28,64,2,1,4:28.000,0,NaN,1:12.568,0,1:29.436,0,...,268.000,2022_3_1,27.0,2022_3_1_LMGTE Pro,1.0,10048.0,10.048,29.513,0.000,0.000
29,63,1,1,4:29.044,0,NaN,1:13.481,0,1:29.014,0,...,269.044,2022_3_1,28.0,2022_3_1_LMGTE Pro,2.0,1044.0,1.044,30.557,1.044,1.044
30,92,2,1,4:29.769,0,NaN,1:14.229,0,1:28.552,0,...,269.769,2022_3_1,29.0,2022_3_1_LMGTE Pro,3.0,725.0,0.725,31.282,0.725,1.769
31,91,3,1,4:29.974,0,NaN,1:13.889,0,1:29.231,0,...,269.974,2022_3_1,30.0,2022_3_1_LMGTE Pro,4.0,205.0,0.205,31.487,0.205,1.974
32,52,1,1,4:31.323,0,NaN,1:14.719,0,1:28.777,0,...,271.323,2022_3_1,31.0,2022_3_1_LMGTE Pro,5.0,1349.0,1.349,32.836,1.349,3.323
33,51,2,1,4:31.881,0,NaN,1:15.303,0,1:28.784,0,...,271.881,2022_3_1,32.0,2022_3_1_LMGTE Pro,6.0,558.0,0.558,33.394,0.558,3.881
34,74,1,1,4:32.598,0,NaN,1:15.842,0,1:29.507,0,...,272.598,2022_3_1,33.0,2022_3_1_LMGTE Pro,7.0,717.0,0.717,34.111,0.717,4.598
35,9,1,1,4:04.291,0,NaN,1:00.657,0,1:23.547,0,...,244.291,2022_3_1,5.0,2022_3_1_LMP2,1.0,477.0,0.477,5.804,0.000,0.000
36,31,3,1,4:05.248,0,NaN,1:01.346,0,1:23.832,0,...,245.248,2022_3_1,7.0,2022_3_1_LMP2,2.0,541.0,0.541,6.761,0.541,0.541
37,38,2,1,4:05.484,0,NaN,1:01.565,0,1:24.029,0,...,245.484,2022_3_1,8.0,2022_3_1_LMP2,3.0,236.0,0.236,6.997,0.236,0.777
38,5,3,1,4:05.937,0,NaN,1:02.003,0,1:23.886,0,...,245.937,2022_3_1,9.0,2022_3_1_LMP2,4.0,453.0,0.453,7.450,0.453,1.230
39,1,3,1,4:06.517,0,NaN,1:01.857,0,1:24.536,0,...,246.517,2022_3_1,10.0,2022_3_1_LMP2,5.0,580.0,0.580,8.030,0.580,1.810
40,65,3,1,4:07.272,0,NaN,1:02.274,0,1:24.783,0,...,247.272,2022_3_1,11.0,2022_3_1_LMP2,6.0,755.0,0.755,8.785,0.755,2.565
41,23,1,1,4:07.943,0,NaN,1:02.529,0,1:24.881,0,...,247.943,2022_3_1,12.0,2022_3_1_LMP2,7.0,671.0,0.671,9.456,0.671,3.236
42,32,2,1,4:08.411,0,NaN,1:02.989,0,1:24.834,0,...,248.411,2022_3_1,13.0,2022_3_1_LMP2,8.0,468.0,0.468,9.924,0.468,3.704
43,48,2,1,4:08.729,0,NaN,1:03.293,0,1:24.790,0,...,248.729,2022_3_1,14.0,2022_3_1_LMP2,9.0,318.0,0.318,10.242,0.318,4.022
44,30,1,1,4:09.520,0,NaN,1:03.558,0,1:25.029,0,...,249.520,2022_3_1,15.0,2022_3_1_LMP2,10.0,791.0,0.791,11.033,0.791,4.813
45,34,2,1,4:10.041,0,NaN,1:04.241,0,1:24.589,0,...,250.041,2022_3_1,16.0,2022_3_1_LMP2,11.0,521.0,0.521,11.554,0.521,5.334
46,37,2,1,4:10.713,0,NaN,1:03.976,0,1:25.429,0,...,250.713,2022_3_1,17.0,2022_3_1_LMP2,12.0,672.0,0.672,12.226,0.672,6.006
47,28,3,1,4:11.546,0,NaN,1:04.632,0,1:25.104,0,...,251.546,2022_3_1,18.0,2022_3_1_LMP2,13.0,833.0,0.833,13.059,0.833,6.839
48,24,3,1,4:12.022,0,NaN,1:05.244,0,1:24.758,0,...,252.022,2022_3_1,19.0,2022_3_1_LMP2,14.0,476.0,0.476,13.535,0.476,7.315
49,44,2,1,4:12.974,0,NaN,1:05.829,0,1:24.719,0,...,252.974,2022_3_1,20.0,2022_3_1_LMP2,15.0,952.0,0.952,14.487,0.952,8.267
50,3,1,1,4:13.297,0,NaN,1:06.023,0,1:25.801,0,...,253.297,2022_3_1,21.0,2022_3_1_LMP2,16.0,323.0,0.323,14.810,0.323,8.590
51,43,2,1,4:14.230,0,NaN,1:07.109,0,1:25.188,0,...,254.230,2022_3_1,22.0,2022_3_1_LMP2,17.0,933.0,0.933,15.743,0.933,9.523
52,83,2,1,4:16.143,0,NaN,1:07.627,0,1:25.169,0,...,256.143,2022_3_1,23.0,2022_3_1_LMP2,18.0,1913.0,1.913,17.656,1.913,11.436
53,39,1,1,4:17.112,0,NaN,1:06.328,0,1:25.481,0,...,257.112,2022_3_1,24.0,2022_3_1_LMP2,19.0,969.0,0.969,18.625,0.969,12.405
54,13,2,1,4:17.506,0,NaN,1:08.010,0,1:25.021,0,...,257.506,2022_3_1,25.0,2022_3_1_LMP2,20.0,394.0,0.394,19.019,0.394,12.799
55,27,3,1,4:17.952,0,NaN,1:08.500,0,1:25.696,0,...,257.952,2022_3_1,26.0,2022_3_1_LMP2,21.0,446.0,0.446,19.465,0.446,13.245
56,45,2,1,4:37.382,0,NaN,1:26.326,0,1:26.776,0,...,277.382,2022_3_1,36.0,2022_3_1_LMP2,22.0,855.0,0.855,38.895,0.855,14.100
57,10,1,1,4:39.275,0,NaN,1:27.063,0,1:26.619,0,...,279.275,2022_3_1,40.0,2022_3_1_LMP2,23.0,779.0,0.779,40.788,0.779,14.879
58,35,2,1,4:45.671,0,NaN,1:05.551,0,1:55.454,0,...,285.671,2022_3_1,51.0,2022_3_1_LMP2,24.0,1100.0,1.100,47.184,1.100,15.979
59,41,2,1,8:31.707,0,B,1:10.390,0,3:33.594,0,...,511.707,2022_3_1,60.0,2022_3_1_LMP2,25.0,212636.0,212.636,273.220,212.636,228.615

In [21]:
#in this one, I'm fixing the time data to be read in as large or seconds, large would be the timedelta object, otherwise our data is now in seconds.
def convert_to_s(x):
    hour = 0
    try:
        hour, minutes, second = x.split(":")
    except ValueError:
        hour = 0
    try: 
        minutes, second = x.split(":")
    except ValueError:
        minutes = 0
    hour_seconds = int(hour)*60*60
    if hour == 0 and minutes == 0:
        return x
    else:
        seconds, ms = second.split(".")
    minute_seconds = (int(minutes)*60 + int(seconds) + int(hour_seconds))*1000 
    total_ms = minute_seconds + int(ms)
    return total_ms/1000

timing_columns_to_fix = ['s1', 's2', 's3']
#all of the x_large data is then converted into into seconds, and then converted into a time_delta variable for ease of displaying data/comparison; this helps for visualizations later
for t in timing_columns_to_fix:
    timing_large_label = t + '_large'
    new_data_sorted_by_position[t] = new_data_sorted_by_position[t].map(str).map(convert_to_s).map(float)
    new_data_sorted_by_position[timing_large_label] = pd.to_timedelta(fia_wec_data[t], unit = 'S')
new_data_sorted_by_position['lap_time'] = pd.to_timedelta(new_data_sorted_by_position['lap_time_s'], unit = 'S')
new_data_sorted_by_position['elapsed_s'] = new_data_sorted_by_position['elapsed_ms']/1000
new_data_sorted_by_position['elapsed'] = pd.to_timedelta(new_data_sorted_by_position['elapsed_s'], unit = 'S')

#dropping key and key_class
new_data_sorted_by_position = new_data_sorted_by_position.drop(['key','key_class'], axis=1)
new_data_sorted_by_position

,number,driver_number,lap_number,lap_time,lap_improvement,crossing_finish_line_in_pit,s1,s1_improvement,s2,s2_improvement,...,team_stint,elapsed_ms,elapsed_s,position,class_position,interval_ms,interval,gap,class_interval,class_gap
0,8,1,1,0 days 00:03:58.487000,0,NaN,59.016,0,81.863,0,...,Toyota Gazoo Racing #8 Stint #1,238487,238.487,1.0,1.0,0.0,0.000,0.000,0.000,0.000
1,7,1,1,0 days 00:03:59.536000,0,NaN,59.498,0,81.915,0,...,Toyota Gazoo Racing #7 Stint #1,239536,239.536,2.0,2.0,1049.0,1.049,1.049,1.049,1.049
2,708,1,1,0 days 00:04:01.913000,0,NaN,60.159,0,81.956,0,...,Glickenhaus Racing #708 Stint #1,241913,241.913,3.0,3.0,2377.0,2.377,3.426,2.377,3.426
3,709,3,1,0 days 00:04:03.814000,0,NaN,60.408,0,82.718,0,...,Glickenhaus Racing #709 Stint #1,243814,243.814,4.0,4.0,1901.0,1.901,5.327,1.901,5.327
4,36,2,1,0 days 00:04:04.707000,0,NaN,60.945,0,83.809,0,...,Alpine ELF Team #36 Stint #1,244707,244.707,6.0,5.0,416.0,0.416,6.220,0.416,5.743
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20497,7,3,378,0 days 00:03:32.801000,0,NaN,33.645,0,80.892,0,...,Toyota Gazoo Racing #7 Stint #33,86220663,86220.663,2.0,2.0,121119.0,121.119,212.801,121.119,121.119
20498,8,2,379,0 days 00:03:32.310000,0,NaN,33.323,0,80.052,0,...,Toyota Gazoo Racing #8 Stint #32,86311854,86311.854,1.0,1.0,91191.0,91.191,91.191,0.000,0.000
20499,7,3,379,0 days 00:03:33.348000,0,NaN,34.550,0,81.034,0,...,Toyota Gazoo Racing #7 Stint #33,86434011,86434.011,2.0,2.0,122157.0,122.157,213.348,122.157,122.157
20500,8,2,380,0 days 00:03:36.142000,0,NaN,33.452,0,80.406,0,...,Toyota Gazoo Racing #8 Stint #32,86527996,86527.996,1.0,1.0,93985.0,93.985,93.985,0.000,0.000
20501,7,3,380,0 days 00:03:35.207000,0,NaN,33.411,0,80.843,0,...,Toyota Gazoo Racing #7 Stint #33,86649218,86649.218,2.0,2.0,121222.0,121.222,215.207,121.222,121.222

In [34]:
#checks if we have all the columns we need
fia_wec_data.columns.isin(new_data_sorted_by_position.columns)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [28]:
#checks what columns we still need to add
full_data_columns = pd.DataFrame(fia_wec_data.columns)
full_data_columns['in_new_df'] = fia_wec_data.columns.isin(new_data_sorted_by_position.columns)
full_data_columns[full_data_columns['in_new_df'] == False]

In [24]:
#puts the data to a new csv file
fia_wec_data = fia_wec_data.append(new_data_sorted_by_position).reset_index(drop=True)
fia_wec_data.to_csv("2012-2022_FIA_WEC_FULL_LAP_DATA_new.csv")

In [31]:
#checks if all the rows were kept
fia_wec_data_old = pd.read_csv("2012-2022_FIA_WEC_FULL_LAP_DATA.csv", index_col=0)
fia_wec_data_new = pd.read_csv("2012-2022_FIA_WEC_FULL_LAP_DATA_new.csv", index_col=0)
#should be 0
len(fia_wec_data_new) - len(fia_wec_data_old) - len(new_data)

c:\Users\trist\AppData\Local\Programs\Python\Python38\lib\site-packages\IPython\core\interactiveshell.py:3369: DtypeWarning: Columns (26,34,52,53,54,55) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\trist\AppData\Local\Programs\Python\Python38\lib\site-packages\IPython\core\interactiveshell.py:3369: DtypeWarning: Columns (26,30) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

0