In [224]:
import pandas as pd
from tabula.io import read_pdf

In [225]:
#here we're using tabula to read the pdf and grab the table from it.
test_1 = read_pdf('sebring_entry_list.pdf', pandas_options={'header':1})[0]
test_1

'pages' argument isn't specified.Will extract only from page 1 by default.

,Unnamed: 0,N°,HYPERCAR,NAT,Unnamed: 1,T,CARS,MISC,DRIVER 1,Unnamed: 2,DRIVER 2,Unnamed: 3,DRIVER 3,Unnamed: 4,DRIVER 4,Unnamed: 5,4,Unnamed: 6
0,NaN,2022 FIA WORLD ENDURANCE CHAMPIONSHIP - PROLOG...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,7,TOYOTA GAZOO RACING,JPN,NaN,M,Toyota GR010 - Hybrid,Hybrid,Mike Conway (GBR),P,Kamui Kobayashi (JPN),P,Jose Maria Lopez (ARG),P,NaN,NaN,NaN,NaN
2,NaN,8,TOYOTA GAZOO RACING,JPN,NaN,M,Toyota GR010 - Hybrid,Hybrid,Sébastien Buemi (CHE),P,Brendon Hartley (NZL),P,Ryo Hirakawa (JPN),P,NaN,NaN,NaN,NaN
3,NaN,36,ALPINE ELF TEAM,FRA,NaN,M,Alpine A480 - Gibson,NaN,André Negrão (BRA),G,Nicolas Lapierre (FRA),P,Matthieu Vaxiviere (FRA),G,NaN,NaN,NaN,NaN
4,NaN,708,GLICKENHAUS RACING,USA,NaN,M,Glickenhaus 007 LMH,NaN,Olivier Pla (FRA),P,Romain Dumas (FRA),P,Ryan Briscoe (USA),P,NaN,NaN,NaN,NaN
5,NaN,N°,LMP2,NAT,NaN,T,CARS,MISC,DRIVER 1,NaN,DRIVER 2,NaN,DRIVER 3,NaN,DRIVER 4,NaN,15.0,NaN
6,NaN,1,RICHARD MILLE RACING TEAM,FRA,NaN,G,Oreca 07 - Gibson,NaN,Lilou Wadoux (FRA),S,Sébastien Ogier (FRA),P,Charles Milesi (FRA),G,NaN,NaN,NaN,NaN
7,NaN,5,TEAM PENSKE,USA,NaN,G,Oreca 07 - Gibson,NaN,Dane Cameron (USA),G,Emmanuel Collard (FRA),S,Felipe Nasr (BRA),P,NaN,NaN,NaN,NaN
8,NaN,9,PREMA ORLEN TEAM,ITA,NaN,G,Oreca 07 - Gibson,NaN,Robert Kubica (POL),P,Louis Deletraz (CHE),G,Lorenzo Colombo (ITA),S,NaN,NaN,NaN,NaN
9,NaN,10,VECTOR SPORT,GBR,G,Oreca 07 - Gibson,NaN,Nico Müller (CHE),P,Ryan Cullen (GBR),S,Mike Rockenfeller (DEU),P,NaN,NaN,NaN,NaN,NaN
10,NaN,22,UNITED AUTOSPORTS USA,USA,NaN,G,Oreca 07 - Gibson,NaN,Philip Hanson (GBR),G,Filipe Albuquerque (PRT),P,William Owen (USA),S,NaN,NaN,NaN,NaN
11,NaN,23,UNITED AUTOSPORTS USA,USA,NaN,G,Oreca 07 - Gibson,NaN,Paul di Resta (GBR),P,Oliver Jarvis (GBR),P,Joshua Pierson (USA),S,NaN,NaN,NaN,NaN
12,NaN,28,JOTA,GBR,NaN,G,Oreca 07 - Gibson,NaN,Oliver Rasmussen (DNK),S,Edward Jones (GBR),G,Jonathan Aberdein (ZAF),G,NaN,NaN,NaN,NaN
13,NaN,31,WRT,BEL,NaN,G,Oreca 07 - Gibson,NaN,Sean Gelael (IDN),S,Robin Frijns (NLD),P,René Rast (DEU),P,NaN,NaN,NaN,NaN
14,NaN,34,INTER EUROPOL COMPETITION,POL,NaN,G,Oreca 07 - Gibson,NaN,Jakub Smiechowski (POL),S,Alex Brundle (GBR),G,Esteban Gutierrez (MEX),P,NaN,NaN,NaN,NaN
15,NaN,35,ULTIMATE,FRA,NaN,G,Oreca 07 - Gibson,Pro/Am,Jean-Baptiste Lahaye (FRA),S,Matthieu Lahaye (FRA),S,François Heriau (FRA),B,NaN,NaN,NaN,NaN
16,NaN,38,JOTA,GBR,NaN,G,Oreca 07 - Gibson,NaN,Roberto Gonzalez (MEX),S,Antonio Felix da Costa (PRT),P,William Stevens (GBR),P,NaN,NaN,NaN,NaN
17,NaN,41,REALTEAM BY WRT,CHE,NaN,G,Oreca 07 - Gibson,NaN,Rui Andrade (PRT),S,Ferdinand Habsburg-Lothringen (AUT),G,Norman Nato (FRA),G,NaN,NaN,NaN,NaN
18,NaN,44,ARC BRATISLAVA,SVK,NaN,G,Oreca 07 - Gibson,Pro/Am,Miroslav Konopka (SVK),B,Mathias Beche (CHE),G,Tijmen van der Helm (NLD),S,NaN,NaN,NaN,NaN
19,NaN,45,ALGARVE PRO RACING,PRT,NaN,G,Oreca 07 - Gibson,Pro/Am,Steven Thomas (USA),B,James Allen (AUS),G,Rene Binder (AUT),S,NaN,NaN,NaN,NaN
20,NaN,83,AF CORSE,ITA,NaN,G,Oreca 07 - Gibson,Pro/Am,François Perrodo (FRA),B,Nicklas Nielsen (DNK),G,Alessio Rovera (ITA),G,NaN,NaN,NaN,NaN
21,NaN,N°,LMGTE Pro,NAT,NaN,T,CARS,MISC,DRIVER 1,NaN,DRIVER 2,NaN,DRIVER 3,NaN,DRIVER 4,NaN,5.0,NaN
22,NaN,51,AF CORSE,ITA,NaN,M,Ferrari 488 GTE EVO,NaN,Alessandro Pier Guidi (ITA),P,James Calado (GBR),P,-,NaN,-,NaN,NaN,NaN
23,NaN,52,AF CORSE,ITA,NaN,M,Ferrari 488 GTE EVO,NaN,Miguel Molina (ESP),P,Antonio Fuoco (ITA),P,-,NaN,-,NaN,NaN,NaN
24,NaN,64,CORVETTE RACING,USA,NaN,M,Chevrolet Corvette C8.R,NaN,Tommy Milner (USA),P,Nick Tandy (GBR),P,-,NaN,-,NaN,NaN,NaN
25,NaN,91,PORSCHE GT TEAM,DEU,NaN,M,Porsche 911 RSR - 19,NaN,Gianmaria Bruni (ITA),P,Richard Lietz (AUT),P,-,NaN,-,NaN,NaN,NaN
26,NaN,92,PORSCHE GT TEAM,DEU,NaN,M,Porsche 911 RSR - 19,NaN,Michael Christensen (DNK),P,Kevin Estre (FRA),P,-,NaN,-,NaN,NaN,NaN
27,NaN,N°,LMGTE Am,NAT,NaN,T,CARS,MISC,DRIVER 1,NaN,DRIVER 2,NaN,DRIVER 3,NaN,DRIVER 4,NaN,12.0,NaN
28,NaN,21,AF CORSE,ITA,NaN,M,Ferrari 488 GTE EVO,NaN,Simon Mann (USA),S,Christoph Ulrich (CHE),B,Toni Vilander (FIN),P,NaN,NaN,NaN,NaN
29,NaN,33,TF SPORT,GBR,NaN,M,Aston Martin Vantage AMR,NaN,Ben Keating (USA),B,Florian Latorre (FRA),S,Marco Sorensen (DNK),P,NaN,NaN,NaN,NaN
30,NaN,46,TEAM PROJECT 1,DEU,NaN,M,Porsche 911 RSR - 19,NaN,Matteo Cairoli (ITA),G,Mikkel Pedersen (DNK),S,Nicolas Leutwiler (CHE),B,NaN,NaN,NaN,NaN
31,NaN,54,AF CORSE,ITA,NaN,M,Ferrari 488 GTE EVO,NaN,Thomas Flohr (CHE),B,Francesco Castellacci (ITA),S,Nicholas Cassidy (NZL),G,NaN,NaN,NaN,NaN
32,NaN,56,TEAM PROJECT 1,DEU,NaN,M,Porsche 911 RSR - 19,NaN,Brendan Iribe (USA),B,Olliver Millroy (GBR),S,Ben Barnicoat (GBR),P,NaN,NaN,NaN,NaN
33,NaN,60,IRON LYNX,ITA,NaN,M,Ferrari 488 GTE EVO,NaN,Claudio Schiavoni (ITA),B,Matteo Cressoni (ITA),S,Giancarlo Fisichella (ITA),P,NaN,NaN,NaN,NaN
34,NaN,71,SPIRIT OF RACE,CHE,NaN,M,Ferrari 488 GTE EVO,NaN,Franck Dezoteux (FRA),B,Pierre Ragues (FRA),S,Gabriel Aubry (FRA),G,NaN,NaN,NaN,NaN
35,NaN,77,DEMPSEY-PROTON RACING,DEU,NaN,M,Porsche 911 RSR - 19,NaN,Christian Ried (DEU),B,Sebastian Priaulx (FRA),S,Harry Tincknell (GBR),P,Memo Gidley (USA)°,B,NaN,NaN
36,NaN,85,IRON DAMES,ITA,NaN,M,Ferrari 488 GTE EVO,NaN,Rahel Frey (CHE),G,Michelle Gatting (DNK),S,Sarah Bovy (BEL),B,NaN,NaN,NaN,NaN
37,NaN,88,DEMPSEY-PROTON RACING,DEU,NaN,M,Porsche 911 RSR - 19,NaN,Fred Poordad (USA),B,Patrick Lindsey (USA),S,Julien Andlauer (FRA),G,NaN,NaN,NaN,NaN
38,NaN,98,NORTHWEST AMR,CAN,NaN,M,Aston Martin Vantage AMR,NaN,Paul Dalla Lana (CAN),B,David Pittard (GBR),S,Nicki Thiim (DNK),P,Henrique Chaves (PRT),S,NaN,NaN
39,NaN,777,D' STATION RACING,JPN,NaN,M,Aston Martin Vantage AMR,NaN,Satoshi Hoshino (JPN),B,Tomonobu Fujii (JPN),G,Charles Fagg (GBR),S,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.0,NaN
41,TYRES - M : MICHELIN / G : GOODYEAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,CATEGORISATION - P : PLATINUM /,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [226]:
#manually fixed this, basically the data is unclean. I can explain what I did, but I think through coding it would have been less efficient, since it's such a small set.
#changed the titles to reflect better what we're looking for,
#added a comma and fixed line 9
#removed the other useless rows at the bottom

drivers = pd.read_csv('entries.csv')
drivers

,Unnamed: 0,N/A,number,team,nationality,na,tyres,car_type,misc,driver_1,license_1,driver_2,license_2,driver_3,license_3,driver_4,license_4,na_2,na_3
0,5,NaN,N°,HYPERCAR,NAT,NaN,T,CARS,MISC,DRIVER 1,NaN,DRIVER 2,NaN,DRIVER 3,NaN,DRIVER 4,NaN,4.0,NaN
1,1,NaN,7,TOYOTA GAZOO RACING,JPN,NaN,M,Toyota GR010 - Hybrid,Hybrid,Mike Conway (GBR),P,Kamui Kobayashi (JPN),P,Jose Maria Lopez (ARG),P,NaN,NaN,NaN,NaN
2,2,NaN,8,TOYOTA GAZOO RACING,JPN,NaN,M,Toyota GR010 - Hybrid,Hybrid,Sébastien Buemi (CHE),P,Brendon Hartley (NZL),P,Ryo Hirakawa (JPN),P,NaN,NaN,NaN,NaN
3,3,NaN,36,ALPINE ELF TEAM,FRA,NaN,M,Alpine A480 - Gibson,NaN,André Negrão (BRA),G,Nicolas Lapierre (FRA),P,Matthieu Vaxiviere (FRA),G,NaN,NaN,NaN,NaN
4,4,NaN,708,GLICKENHAUS RACING,USA,NaN,M,Glickenhaus 007 LMH,NaN,Olivier Pla (FRA),P,Romain Dumas (FRA),P,Ryan Briscoe (USA),P,NaN,NaN,NaN,NaN
5,5,NaN,N°,LMP2,NAT,NaN,T,CARS,MISC,DRIVER 1,NaN,DRIVER 2,NaN,DRIVER 3,NaN,DRIVER 4,NaN,15.0,NaN
6,6,NaN,1,RICHARD MILLE RACING TEAM,FRA,NaN,G,Oreca 07 - Gibson,NaN,Lilou Wadoux (FRA),S,Sébastien Ogier (FRA),P,Charles Milesi (FRA),G,NaN,NaN,NaN,NaN
7,7,NaN,5,TEAM PENSKE,USA,NaN,G,Oreca 07 - Gibson,NaN,Dane Cameron (USA),G,Emmanuel Collard (FRA),S,Felipe Nasr (BRA),P,NaN,NaN,NaN,NaN
8,8,NaN,9,PREMA ORLEN TEAM,ITA,NaN,G,Oreca 07 - Gibson,NaN,Robert Kubica (POL),P,Louis Deletraz (CHE),G,Lorenzo Colombo (ITA),S,NaN,NaN,NaN,NaN
9,9,NaN,10,VECTOR SPORT,GBR,NaN,G,Oreca 07 - Gibson,NaN,Nico Müller (CHE),P,Ryan Cullen (GBR),S,Mike Rockenfeller (DEU),P,NaN,NaN,NaN,NaN
10,10,NaN,22,UNITED AUTOSPORTS USA,USA,NaN,G,Oreca 07 - Gibson,NaN,Philip Hanson (GBR),G,Filipe Albuquerque (PRT),P,William Owen (USA),S,NaN,NaN,NaN,NaN
11,11,NaN,23,UNITED AUTOSPORTS USA,USA,NaN,G,Oreca 07 - Gibson,NaN,Paul di Resta (GBR),P,Oliver Jarvis (GBR),P,Joshua Pierson (USA),S,NaN,NaN,NaN,NaN
12,12,NaN,28,JOTA,GBR,NaN,G,Oreca 07 - Gibson,NaN,Oliver Rasmussen (DNK),S,Edward Jones (GBR),G,Jonathan Aberdein (ZAF),G,NaN,NaN,NaN,NaN
13,13,NaN,31,WRT,BEL,NaN,G,Oreca 07 - Gibson,NaN,Sean Gelael (IDN),S,Robin Frijns (NLD),P,René Rast (DEU),P,NaN,NaN,NaN,NaN
14,14,NaN,34,INTER EUROPOL COMPETITION,POL,NaN,G,Oreca 07 - Gibson,NaN,Jakub Smiechowski (POL),S,Alex Brundle (GBR),G,Esteban Gutierrez (MEX),P,NaN,NaN,NaN,NaN
15,15,NaN,35,ULTIMATE,FRA,NaN,G,Oreca 07 - Gibson,Pro/Am,Jean-Baptiste Lahaye (FRA),S,Matthieu Lahaye (FRA),S,François Heriau (FRA),B,NaN,NaN,NaN,NaN
16,16,NaN,38,JOTA,GBR,NaN,G,Oreca 07 - Gibson,NaN,Roberto Gonzalez (MEX),S,Antonio Felix da Costa (PRT),P,William Stevens (GBR),P,NaN,NaN,NaN,NaN
17,17,NaN,41,REALTEAM BY WRT,CHE,NaN,G,Oreca 07 - Gibson,NaN,Rui Andrade (PRT),S,Ferdinand Habsburg-Lothringen (AUT),G,Norman Nato (FRA),G,NaN,NaN,NaN,NaN
18,18,NaN,44,ARC BRATISLAVA,SVK,NaN,G,Oreca 07 - Gibson,Pro/Am,Miroslav Konopka (SVK),B,Mathias Beche (CHE),G,Tijmen van der Helm (NLD),S,NaN,NaN,NaN,NaN
19,19,NaN,45,ALGARVE PRO RACING,PRT,NaN,G,Oreca 07 - Gibson,Pro/Am,Steven Thomas (USA),B,James Allen (AUS),G,Rene Binder (AUT),S,NaN,NaN,NaN,NaN
20,20,NaN,83,AF CORSE,ITA,NaN,G,Oreca 07 - Gibson,Pro/Am,François Perrodo (FRA),B,Nicklas Nielsen (DNK),G,Alessio Rovera (ITA),G,NaN,NaN,NaN,NaN
21,21,NaN,N°,LMGTE Pro,NAT,NaN,T,CARS,MISC,DRIVER 1,NaN,DRIVER 2,NaN,DRIVER 3,NaN,DRIVER 4,NaN,5.0,NaN
22,22,NaN,51,AF CORSE,ITA,NaN,M,Ferrari 488 GTE EVO,NaN,Alessandro Pier Guidi (ITA),P,James Calado (GBR),P,-,NaN,-,NaN,NaN,NaN
23,23,NaN,52,AF CORSE,ITA,NaN,M,Ferrari 488 GTE EVO,NaN,Miguel Molina (ESP),P,Antonio Fuoco (ITA),P,-,NaN,-,NaN,NaN,NaN
24,24,NaN,64,CORVETTE RACING,USA,NaN,M,Chevrolet Corvette C8.R,NaN,Tommy Milner (USA),P,Nick Tandy (GBR),P,-,NaN,-,NaN,NaN,NaN
25,25,NaN,91,PORSCHE GT TEAM,DEU,NaN,M,Porsche 911 RSR - 19,NaN,Gianmaria Bruni (ITA),P,Richard Lietz (AUT),P,-,NaN,-,NaN,NaN,NaN
26,26,NaN,92,PORSCHE GT TEAM,DEU,NaN,M,Porsche 911 RSR - 19,NaN,Michael Christensen (DNK),P,Kevin Estre (FRA),P,-,NaN,-,NaN,NaN,NaN
27,27,NaN,N°,LMGTE Am,NAT,NaN,T,CARS,MISC,DRIVER 1,NaN,DRIVER 2,NaN,DRIVER 3,NaN,DRIVER 4,NaN,12.0,NaN
28,28,NaN,21,AF CORSE,ITA,NaN,M,Ferrari 488 GTE EVO,NaN,Simon Mann (USA),S,Christoph Ulrich (CHE),B,Toni Vilander (FIN),P,NaN,NaN,NaN,NaN
29,29,NaN,33,TF SPORT,GBR,NaN,M,Aston Martin Vantage AMR,NaN,Ben Keating (USA),B,Florian Latorre (FRA),S,Marco Sorensen (DNK),P,NaN,NaN,NaN,NaN
30,30,NaN,46,TEAM PROJECT 1,DEU,NaN,M,Porsche 911 RSR - 19,NaN,Matteo Cairoli (ITA),G,Mikkel Pedersen (DNK),S,Nicolas Leutwiler (CHE),B,NaN,NaN,NaN,NaN
31,31,NaN,54,AF CORSE,ITA,NaN,M,Ferrari 488 GTE EVO,NaN,Thomas Flohr (CHE),B,Francesco Castellacci (ITA),S,Nicholas Cassidy (NZL),G,NaN,NaN,NaN,NaN
32,32,NaN,56,TEAM PROJECT 1,DEU,NaN,M,Porsche 911 RSR - 19,NaN,Brendan Iribe (USA),B,Olliver Millroy (GBR),S,Ben Barnicoat (GBR),P,NaN,NaN,NaN,NaN
33,33,NaN,60,IRON LYNX,ITA,NaN,M,Ferrari 488 GTE EVO,NaN,Claudio Schiavoni (ITA),B,Matteo Cressoni (ITA),S,Giancarlo Fisichella (ITA),P,NaN,NaN,NaN,NaN
34,34,NaN,71,SPIRIT OF RACE,CHE,NaN,M,Ferrari 488 GTE EVO,NaN,Franck Dezoteux (FRA),B,Pierre Ragues (FRA),S,Gabriel Aubry (FRA),G,NaN,NaN,NaN,NaN
35,35,NaN,77,DEMPSEY-PROTON RACING,DEU,NaN,M,Porsche 911 RSR - 19,NaN,Christian Ried (DEU),B,Sebastian Priaulx (FRA),S,Harry Tincknell (GBR),P,Memo Gidley (USA)°,B,NaN,NaN
36,36,NaN,85,IRON DAMES,ITA,NaN,M,Ferrari 488 GTE EVO,NaN,Rahel Frey (CHE),G,Michelle Gatting (DNK),S,Sarah Bovy (BEL),B,NaN,NaN,NaN,NaN
37,37,NaN,88,DEMPSEY-PROTON RACING,DEU,NaN,M,Porsche 911 RSR - 19,NaN,Fred Poordad (USA),B,Patrick Lindsey (USA),S,Julien Andlauer (FRA),G,NaN,NaN,NaN,NaN
38,38,NaN,98,NORTHWEST AMR,CAN,NaN,M,Aston Martin Vantage AMR,NaN,Paul Dalla Lana (CAN),B,David Pittard (GBR),S,Nicki Thiim (DNK),P,Henrique Chaves (PRT),S,NaN,NaN
39,39,NaN,777,D' STATION RACING,JPN,NaN,M,Aston Martin Vantage AMR,NaN,Satoshi Hoshino (JPN),B,Tomonobu Fujii (JPN),G,Charles Fagg (GBR),S,NaN,NaN,NaN,NaN

In [227]:
#the drivers are stacked in columns driver_1 to driver_4, so we have to unstack them
driver_columns = ['driver', "license"]
drivers_with_licenses = pd.DataFrame(columns = driver_columns)
#essentially this loop takes what I put for driver_x and license_x and combines them into drivers_with_licenses
for i in range(1,5):
    driver_col = "driver_" + str(i)
    license_col = "license_" + str(i)
    wanted_columns = [driver_col, license_col]
    
    iter_drivers = drivers[wanted_columns]
    iter_drivers.columns = driver_columns
    drivers_with_licenses = drivers_with_licenses.append(iter_drivers)

drivers_with_licenses

                   driver license
0                DRIVER 1     NaN
1       Mike Conway (GBR)       P
2   Sébastien Buemi (CHE)       P
3      André Negrão (BRA)       G
4       Olivier Pla (FRA)       P
..                    ...     ...
35     Memo Gidley (USA)°       B
36                    NaN     NaN
37                    NaN     NaN
38  Henrique Chaves (PRT)       S
39                    NaN     NaN

[160 rows x 2 columns]

In [228]:
#still some more work to do. There's NA's in licenses, let's get rid of those first.
drivers_with_licenses =  drivers_with_licenses[drivers_with_licenses['license'].notna()]
drivers_with_licenses

                   driver license
1       Mike Conway (GBR)       P
2   Sébastien Buemi (CHE)       P
3      André Negrão (BRA)       G
4       Olivier Pla (FRA)       P
6      Lilou Wadoux (FRA)       S
..                    ...     ...
37  Julien Andlauer (FRA)       G
38      Nicki Thiim (DNK)       P
39     Charles Fagg (GBR)       S
35     Memo Gidley (USA)°       B
38  Henrique Chaves (PRT)       S

[105 rows x 2 columns]

In [229]:
#let's also compare to what we currently have for driver_name in the sebring pdf
sebring_laps = pd.read_csv('1000_Sebring_Laps.csv', delimiter = ";")
sebring_laps.groupby("DRIVER_NAME").mean()

,NUMBER,DRIVER_NUMBER,LAP_NUMBER,LAP_IMPROVEMENT,S1_IMPROVEMENT,S2_IMPROVEMENT,S3_IMPROVEMENT,KPH,TOP_SPEED,Unnamed: 26
DRIVER_NAME,,,,,,,,,,
Alessandro PIER GUIDI,51.0,1.0,110.617284,0.000000,0.012346,0.024691,0.024691,167.149383,232.362963,NaN
Alessio ROVERA,83.0,3.0,132.759494,0.025316,0.025316,0.012658,0.025316,174.916456,253.627848,NaN
André NEGRÃO,36.0,1.0,128.000000,0.000000,0.018868,0.018868,0.018868,182.409434,267.079245,NaN
Antonio FUOCO,52.0,2.0,81.211864,0.000000,0.016949,0.016949,0.008475,174.702542,241.708475,NaN
Antonio Felix DA COSTA,38.0,2.0,98.000000,0.000000,0.024390,0.024390,0.048780,177.970732,255.741463,NaN
...,...,...,...,...,...,...,...,...,...,...
Tommy MILNER,64.0,1.0,109.320988,0.000000,0.012346,0.012346,0.012346,170.093827,237.098765,NaN
Tomonobu FUJII,777.0,2.0,13.500000,0.000000,0.038462,0.038462,0.038462,176.373077,247.680769,NaN
Toni VILANDER,21.0,3.0,72.500000,0.066667,0.033333,0.066667,0.066667,175.016667,239.043333,NaN
William OWEN,22.0,3.0,102.000000,0.000000,0.020408,0.020408,0.020408,175.006122,256.038776,NaN
William STEVENS,38.0,3.0,115.287234,0.021277,0.021277,0.021277,0.010638,182.903191,259.935106,NaN

In [230]:
#we have to fix this name, could do it by creating a function that takes the driver names and takes the nationality out of the name
def fix_driver_names(x):
    name_array = x.split(" ")
    name_array = name_array[:-1]
    name = " ".join(name_array)
    return name

#so let's apply it to our df
drivers_with_licenses.driver = drivers_with_licenses.driver.apply(fix_driver_names)
drivers_with_licenses

C:\Users\trist\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\generic.py:5516: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

             driver license
1       Mike Conway       P
2   Sébastien Buemi       P
3      André Negrão       G
4       Olivier Pla       P
6      Lilou Wadoux       S
..              ...     ...
37  Julien Andlauer       G
38      Nicki Thiim       P
39     Charles Fagg       S
35      Memo Gidley       B
38  Henrique Chaves       S

[105 rows x 2 columns]

In [231]:
#we got the names free! but...
sebring_laps.DRIVER_NAME

0       Charles MILESI
1       Charles MILESI
2       Charles MILESI
3       Charles MILESI
4       Charles MILESI
             ...
6402     David PITTARD
6403     David PITTARD
6404     David PITTARD
6405     David PITTARD
6406     David PITTARD
Name: DRIVER_NAME, Length: 6407, dtype: object

In [232]:
#as we can kinda see, it doesn't really match the previous one.
#we can fix this by making them all lower or uppercase, let's go with lower
sebring_laps_lower = sebring_laps.copy()
sebring_laps_lower['DRIVER_NAME'] = sebring_laps['DRIVER_NAME'].str.lower()
sebring_laps_lower

,NUMBER,DRIVER_NUMBER,LAP_NUMBER,LAP_TIME,LAP_IMPROVEMENT,CROSSING_FINISH_LINE_IN_PIT,S1,S1_IMPROVEMENT,S2,S2_IMPROVEMENT,...,S3_LARGE,TOP_SPEED,DRIVER_NAME,PIT_TIME,CLASS,GROUP,TEAM,MANUFACTURER,FLAG_AT_FL,Unnamed: 26
0,1,3,1,2:03.750,0,NaN,41.661,0,41.326,0,...,0:40.763,269.6,charles milesi,NaN,LMP2,NaN,Richard Mille Racing Team,Oreca,GF,NaN
1,1,3,2,1:53.835,0,NaN,33.887,0,39.585,0,...,0:40.363,272.3,charles milesi,NaN,LMP2,NaN,Richard Mille Racing Team,Oreca,GF,NaN
2,1,3,3,1:53.408,0,NaN,34.080,0,39.336,0,...,0:39.992,272.9,charles milesi,NaN,LMP2,NaN,Richard Mille Racing Team,Oreca,GF,NaN
3,1,3,4,1:52.926,0,NaN,33.461,0,39.513,0,...,0:39.952,272.9,charles milesi,NaN,LMP2,NaN,Richard Mille Racing Team,Oreca,GF,NaN
4,1,3,5,1:52.332,2,NaN,33.384,0,39.181,2,...,0:39.767,272.3,charles milesi,NaN,LMP2,NaN,Richard Mille Racing Team,Oreca,GF,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6402,98,2,176,2:00.136,0,NaN,35.565,0,41.630,0,...,0:42.941,240.6,david pittard,NaN,LMGTE Am,NaN,Northwest AMR,Aston Martin,GF,NaN
6403,98,2,177,2:00.514,0,NaN,35.849,0,41.913,0,...,0:42.752,249.9,david pittard,NaN,LMGTE Am,NaN,Northwest AMR,Aston Martin,GF,NaN
6404,98,2,178,2:00.760,0,NaN,35.627,0,41.511,0,...,0:43.622,218.0,david pittard,NaN,LMGTE Am,NaN,Northwest AMR,Aston Martin,GF,NaN
6405,98,2,179,2:08.667,0,NaN,35.600,0,42.613,0,...,0:50.454,165.6,david pittard,NaN,LMGTE Am,NaN,Northwest AMR,Aston Martin,SF,NaN
6406,98,2,180,24:46.859,0,NaN,51.685,0,1:22.717,0,...,22:32.457,156.6,david pittard,NaN,LMGTE Am,NaN,Northwest AMR,Aston Martin,SF,NaN

In [233]:
#doing the same on the licenses
drivers_with_licenses['driver'] = drivers_with_licenses['driver'].str.lower()
drivers_with_licenses

<ipython-input-233-0019e6740b0b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drivers_with_licenses['driver'] = drivers_with_licenses['driver'].str.lower()

             driver license
1       mike conway       P
2   sébastien buemi       P
3      andré negrão       G
4       olivier pla       P
6      lilou wadoux       S
..              ...     ...
37  julien andlauer       G
38      nicki thiim       P
39     charles fagg       S
35      memo gidley       B
38  henrique chaves       S

[105 rows x 2 columns]

In [234]:
#now let's see if this combines them!
laps_with_licenses = pd.merge(left = sebring_laps_lower, right = drivers_with_licenses, left_on = "DRIVER_NAME", right_on = "driver", how = "outer")
laps_with_licenses

,NUMBER,DRIVER_NUMBER,LAP_NUMBER,LAP_TIME,LAP_IMPROVEMENT,CROSSING_FINISH_LINE_IN_PIT,S1,S1_IMPROVEMENT,S2,S2_IMPROVEMENT,...,DRIVER_NAME,PIT_TIME,CLASS,GROUP,TEAM,MANUFACTURER,FLAG_AT_FL,Unnamed: 26,driver,license
0,1.0,3.0,1.0,2:03.750,0.0,NaN,41.661,0.0,41.326,0.0,...,charles milesi,NaN,LMP2,NaN,Richard Mille Racing Team,Oreca,GF,NaN,charles milesi,G
1,1.0,3.0,2.0,1:53.835,0.0,NaN,33.887,0.0,39.585,0.0,...,charles milesi,NaN,LMP2,NaN,Richard Mille Racing Team,Oreca,GF,NaN,charles milesi,G
2,1.0,3.0,3.0,1:53.408,0.0,NaN,34.080,0.0,39.336,0.0,...,charles milesi,NaN,LMP2,NaN,Richard Mille Racing Team,Oreca,GF,NaN,charles milesi,G
3,1.0,3.0,4.0,1:52.926,0.0,NaN,33.461,0.0,39.513,0.0,...,charles milesi,NaN,LMP2,NaN,Richard Mille Racing Team,Oreca,GF,NaN,charles milesi,G
4,1.0,3.0,5.0,1:52.332,2.0,NaN,33.384,0.0,39.181,2.0,...,charles milesi,NaN,LMP2,NaN,Richard Mille Racing Team,Oreca,GF,NaN,charles milesi,G
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6410,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,olliver millroy,S
6411,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rene binder,S
6412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,marco sorensen,P
6413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,memo gidley,B
6414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,henrique chaves,S

In [235]:
#since we did an outer join, we can see that there are people that got omitted from both dfs
laps_with_licenses_na = laps_with_licenses[laps_with_licenses['CLASS'].isna()]
laps_with_licenses_na

,NUMBER,DRIVER_NUMBER,LAP_NUMBER,LAP_TIME,LAP_IMPROVEMENT,CROSSING_FINISH_LINE_IN_PIT,S1,S1_IMPROVEMENT,S2,S2_IMPROVEMENT,...,DRIVER_NAME,PIT_TIME,CLASS,GROUP,TEAM,MANUFACTURER,FLAG_AT_FL,Unnamed: 26,driver,license
6407,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mike conway,P
6408,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,alex brundle,G
6409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ferdinand habsburg-lothringen,G
6410,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,olliver millroy,S
6411,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rene binder,S
6412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,marco sorensen,P
6413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,memo gidley,B
6414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,henrique chaves,S

In [236]:
#some of them didn't race, like Mike Conway or Alex Brundle.
#But some of them do exist in the df, specifically Marco SØrensen, Ferdinand Habsburg, and Oliver Millroy (misspelled as Olliver)
sebring_laps_omitted = sebring_laps[(sebring_laps['DRIVER_NAME'] == 'Marco SØRENSEN') | (sebring_laps['DRIVER_NAME'] == "Ferdinand HABSBURG") | (sebring_laps['DRIVER_NAME'] == "Oliver MILLROY")]
sebring_laps_omitted

,NUMBER,DRIVER_NUMBER,LAP_NUMBER,LAP_TIME,LAP_IMPROVEMENT,CROSSING_FINISH_LINE_IN_PIT,S1,S1_IMPROVEMENT,S2,S2_IMPROVEMENT,...,S3_LARGE,TOP_SPEED,DRIVER_NAME,PIT_TIME,CLASS,GROUP,TEAM,MANUFACTURER,FLAG_AT_FL,Unnamed: 26
1452,33,3,161,4:42.557,0,B,48.673,0,1:21.854,0,...,2:32.030,79.6,Marco SØRENSEN,0:01:18.656,LMGTE Am,NaN,TF Sport,Aston Martin,FCY,NaN
1453,33,3,162,4:22.148,0,NaN,1:20.558,0,1:22.471,0,...,1:39.119,79.6,Marco SØRENSEN,NaN,LMGTE Am,NaN,TF Sport,Aston Martin,FCY,NaN
1454,33,3,163,2:22.574,0,NaN,56.194,0,43.007,0,...,0:43.373,244.5,Marco SØRENSEN,NaN,LMGTE Am,NaN,TF Sport,Aston Martin,GF,NaN
1455,33,3,164,2:00.875,0,NaN,35.996,0,42.164,0,...,0:42.715,246.3,Marco SØRENSEN,NaN,LMGTE Am,NaN,TF Sport,Aston Martin,GF,NaN
1456,33,3,165,2:00.917,0,NaN,35.913,0,41.896,0,...,0:43.108,245.0,Marco SØRENSEN,NaN,LMGTE Am,NaN,TF Sport,Aston Martin,GF,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3750,56,2,140,2:00.477,0,NaN,35.855,0,41.808,0,...,0:42.814,249.0,Oliver MILLROY,NaN,LMGTE Am,NaN,Team Project 1,Porsche,GF,NaN
3751,56,2,141,2:00.998,0,NaN,35.778,0,42.092,0,...,0:43.128,248.5,Oliver MILLROY,NaN,LMGTE Am,NaN,Team Project 1,Porsche,GF,NaN
3752,56,2,142,2:01.191,0,NaN,36.023,0,42.275,0,...,0:42.893,248.1,Oliver MILLROY,NaN,LMGTE Am,NaN,Team Project 1,Porsche,GF,NaN
3753,56,2,143,2:00.754,0,NaN,35.793,0,41.934,0,...,0:43.027,249.0,Oliver MILLROY,NaN,LMGTE Am,NaN,Team Project 1,Porsche,GF,NaN
3754,56,2,144,2:01.740,0,NaN,36.257,0,42.383,0,...,0:43.100,249.4,Oliver MILLROY,NaN,LMGTE Am,NaN,Team Project 1,Porsche,GF,NaN

In [237]:
#let's grab them from the DF
omitted_wanted_columns = ["DRIVER_NAME"]
laps_with_licenses_na = laps_with_licenses[laps_with_licenses['license'].isna()]
laps_with_licenses_na_drivers = laps_with_licenses_na[omitted_wanted_columns]
laps_with_licenses_na_drivers["driver"] = laps_with_licenses_na["DRIVER_NAME"].str.lower()
laps_with_licenses_na_drivers = laps_with_licenses_na_drivers.drop_duplicates().reset_index(drop = True)
laps_with_licenses_na_drivers = laps_with_licenses_na_drivers.drop("DRIVER_NAME", axis = 1)
laps_with_licenses_na_drivers

<ipython-input-237-68418e3e6a0d>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  laps_with_licenses_na_drivers["driver"] = laps_with_licenses_na["DRIVER_NAME"].str.lower()

               driver
0      marco sørensen
1       fabio scherer
2  ferdinand habsburg
3         rené binder
4      oliver millroy

In [238]:
#fabio scherer and rene binder aren't on the fia list for some reason
#just a google search shows rene is a silver and fabio is a gold

omitted_drivers_license = ["P", "G", "G", "S", "S"]
#now that we have this, we can append this to the driver_licenses df
laps_with_licenses_na_drivers['license'] = omitted_drivers_license
laps_with_licenses_na_drivers

               driver license
0      marco sørensen       P
1       fabio scherer       G
2  ferdinand habsburg       G
3         rené binder       S
4      oliver millroy       S

In [239]:
#so let's add them to the drivers_with_licenses df
drivers_with_licenses = drivers_with_licenses.append(laps_with_licenses_na_drivers).reset_index(drop=True)
drivers_with_licenses

                 driver license
0           mike conway       P
1       sébastien buemi       P
2          andré negrão       G
3           olivier pla       P
4          lilou wadoux       S
..                  ...     ...
105      marco sørensen       P
106       fabio scherer       G
107  ferdinand habsburg       G
108         rené binder       S
109      oliver millroy       S

[110 rows x 2 columns]

In [240]:
#let's try combining them again!
laps_with_licenses = pd.merge(left = sebring_laps_lower, right = drivers_with_licenses, left_on = "DRIVER_NAME", right_on = "driver", how = "outer")
laps_with_licenses

,NUMBER,DRIVER_NUMBER,LAP_NUMBER,LAP_TIME,LAP_IMPROVEMENT,CROSSING_FINISH_LINE_IN_PIT,S1,S1_IMPROVEMENT,S2,S2_IMPROVEMENT,...,DRIVER_NAME,PIT_TIME,CLASS,GROUP,TEAM,MANUFACTURER,FLAG_AT_FL,Unnamed: 26,driver,license
0,1.0,3.0,1.0,2:03.750,0.0,NaN,41.661,0.0,41.326,0.0,...,charles milesi,NaN,LMP2,NaN,Richard Mille Racing Team,Oreca,GF,NaN,charles milesi,G
1,1.0,3.0,2.0,1:53.835,0.0,NaN,33.887,0.0,39.585,0.0,...,charles milesi,NaN,LMP2,NaN,Richard Mille Racing Team,Oreca,GF,NaN,charles milesi,G
2,1.0,3.0,3.0,1:53.408,0.0,NaN,34.080,0.0,39.336,0.0,...,charles milesi,NaN,LMP2,NaN,Richard Mille Racing Team,Oreca,GF,NaN,charles milesi,G
3,1.0,3.0,4.0,1:52.926,0.0,NaN,33.461,0.0,39.513,0.0,...,charles milesi,NaN,LMP2,NaN,Richard Mille Racing Team,Oreca,GF,NaN,charles milesi,G
4,1.0,3.0,5.0,1:52.332,2.0,NaN,33.384,0.0,39.181,2.0,...,charles milesi,NaN,LMP2,NaN,Richard Mille Racing Team,Oreca,GF,NaN,charles milesi,G
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6410,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,olliver millroy,S
6411,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rene binder,S
6412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,marco sorensen,P
6413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,memo gidley,B
6414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,henrique chaves,S

In [241]:
#any nas?
laps_with_licenses_na = laps_with_licenses[laps_with_licenses['license'].isna()]
laps_with_licenses_na

Empty DataFrame
Columns: [NUMBER,  DRIVER_NUMBER,  LAP_NUMBER,  LAP_TIME,  LAP_IMPROVEMENT,  CROSSING_FINISH_LINE_IN_PIT,  S1,  S1_IMPROVEMENT,  S2,  S2_IMPROVEMENT,  S3,  S3_IMPROVEMENT,  KPH,  ELAPSED,  HOUR, S1_LARGE, S2_LARGE, S3_LARGE, TOP_SPEED, DRIVER_NAME, PIT_TIME, CLASS, GROUP, TEAM, MANUFACTURER, FLAG_AT_FL, Unnamed: 26, driver, license]
Index: []

[0 rows x 29 columns]

In [244]:
#okay cool! let's drop the column and bottom nas
laps_with_licenses = laps_with_licenses[laps_with_licenses["TEAM"].notna()]

#and also drop the driver column 
laps_with_licenses = laps_with_licenses.drop("driver", axis=1)
laps_with_licenses

KeyError: "['driver'] not found in axis"

In [245]:
#nooooow we can do my analysis, so let's save this as a csv
laps_with_licenses.to_csv('sebring_data_with_licenses.csv')