In [221]:
import pandas as pd
import numpy as np

In [222]:
#2012=2014 data don't have teams, manufacturer or class

prefix_yr = "2012_"
year = 2012
tracks_2012 = ["SEBRING","SPA_FRANCORCHAMPS","LE_MANS","INTERLAGOS","SILVERSTONE","BAHRAIN_INTERNATIONAL_CIRCUIT","FUJI_SPEEDWAY","SHANGHAI_INTERNATIONAL_CIRCUIT"]
tracks_2013 = ["SILVERSTONE","SPA_FRANCORCHAMPS","LE_MANS","INTERLAGOS","CIRCUIT_OF_THE_AMERICAS", "FUJI_SPEEDWAY","SHANGHAI_INTERNATIONAL_CIRCUIT", "BAHRAIN_INTERNATIONAL_CIRCUIT"]

tracks_2014 = ["SILVERSTONE","SPA_FRANCORCHAMPS","LE_MANS","CIRCUIT_OF_THE_AMERICAS", "FUJI_SPEEDWAY","SHANGHAI_INTERNATIONAL_CIRCUIT", "BAHRAIN_INTERNATIONAL_CIRCUIT","INTERLAGOS"]
tracks_2015 = ["SILVERSTONE","SPA_FRANCORCHAMPS","LE_MANS","NURBURGRING", "CIRCUIT_OF_THE_AMERICAS", "FUJI_SPEEDWAY","SHANGHAI_INTERNATIONAL_CIRCUIT", "BAHRAIN_INTERNATIONAL_CIRCUIT"]
tracks_2016_2017 = ["SILVERSTONE","SPA_FRANCORCHAMPS","LE_MANS","NURBURGRING","AUTODROMO_HERMANOS_RODRIGUEZ", "CIRCUIT_OF_THE_AMERICAS", "FUJI_SPEEDWAY","SHANGHAI_INTERNATIONAL_CIRCUIT", "BAHRAIN_INTERNATIONAL_CIRCUIT"]
tracks_2018_2019 = ["SPA_FRANCORCHAMPS_2018","LE_MANS_2018","SILVERSTONE","FUJI_SPEEDWAY","SHANGHAI_INTERNATIONAL_CIRCUIT","SEBRING","SPA_FRANCORCHAMPS_2019","LE_MANS_2019"]
tracks_2019_2020 = ["SILVERSTONE","FUJI_SPEEDWAY","SHANGHAI_INTERNATIONAL_CIRCUIT","BAHRAIN_INTERNATIONAL_CIRCUIT_2019","CIRCUIT_OF_THE_AMERICAS","SPA_FRANCORCHAMPS","LE_MANS","BAHRAIN_INTERNATIONAL_CIRCUIT_2020"]
tracks_2021 = ["SPA_FRANCORCHAMPS","AUTODROMO_DO_ALGARVE", "AUTODROMO_NAZIONALE_DI_MONZA","LE_MANS","BAHRAIN_INTERNATIONAL_CIRCUIT_6_HOURS", "BAHRAIN_INTERNATIONAL_CIRCUIT_8_HOURS"]
tracks_2022 = ['SEBRING']
wanted_columns = ['NUMBER', 'TEAM', 'VEHICLE', 'CLASS']

classification_df = pd.read_csv("data/classifications/2012_CLASSIFICATION.csv", sep = ";")

classification_df = classification_df[wanted_columns]
print(classification_df)

    NUMBER                       TEAM                      VEHICLE      CLASS
0        1      Audi Sport Team Joest      Audi R18 e-tron quattro       LMP1
1        2      Audi Sport Team Joest      Audi R18 e-tron quattro       LMP1
2        4   Audi Sport North America               Audi R18 Ultra       LMP1
3       12           Rebellion Racing   Lola B12/60 Coupe - Toyota       LMP1
4        3      Audi Sport Team Joest               Audi R18 Ultra       LMP1
5       22                        JRM         HPD ARX  03a - Honda       LMP1
6       44      Starworks Motorsports          HPD ARX 03b - Honda       LMP2
7       46      Thiriet By TDS Racing            Oreca 03 - Nissan       LMP2
8       49               Pecom Racing            Oreca 03 - Nissan       LMP2
9       26           Signatech Nissan            Oreca 03 - Nissan       LMP2
10      13           Rebellion Racing   Lola B12/60 Coupe - Toyota       LMP1
11      41         Greaves Motorsport         Zytek Z11SN - Nissan       LMP2
12      25                  ADR-Delta            Oreca 03 - Nissan       LMP2
13      35                 Oak Racing              Morgan - Nissan       LMP2
14      42         Greaves Motorsport         Zytek Z11SN - Nissan       LMP2
15      23           Signatech Nissan            Oreca 03 - Nissan       LMP2
16      51                   AF Corse           Ferrari 458 Italia  LMGTE Pro
17      59              Luxury Racing           Ferrari 458 Italia  LMGTE Pro
18      97        Aston Martin Racing      Aston Martin Vantage V8  LMGTE Pro
19      50         Larbre Competition    Chevrolet Corvette C6 ZR1   LMGTE Am
20      67    Imsa Performance Matmut        Porsche 911 RSR (997)   LMGTE Am
21      71                   AF Corse           Ferrari 458 Italia  LMGTE Pro
22      73            Corvette Racing    Chevrolet Corvette C6 ZR1  LMGTE Pro
23      45      Boutsen Ginion Racing            Oreca 03 - Nissan       LMP2
24      57               Krohn Racing           Ferrari 458 Italia   LMGTE Am
25      40           Race Performance              Oreca 03 - Judd       LMP2
26      79  Flying Lizard Motorsports        Porsche 911 RSR (997)   LMGTE Am
27      70         Larbre Competition    Chevrolet Corvette C6 ZR1   LMGTE Am
28      43         Extreme Limit Aric         Norma MP 2000 - Judd       LMP2
29      21             Strakka Racing         HPD ARX  03a - Honda       LMP1
30      61           AF Corse-Waltrip           Ferrari 458 Italia   LMGTE Am
31      83                JMB  Racing           Ferrari 458 Italia   LMGTE Am
32      55                  JWA-Avila        Porsche 911 RSR (997)   LMGTE Am
33      74            Corvette Racing    Chevrolet Corvette C6 ZR1  LMGTE Pro
34      17             Pescarolo Team                  Dome - Judd       LMP1
35      38                       Jota         Zytek Z11SN - Nissan       LMP2
36      33         Level 5 Motorsport          HPD ARX 03b - Honda       LMP2
37      30          Status Grand Prix                  Lola - Judd       LMP2
38      88     Team Felbermayr-Proton        Porsche 911 RSR (997)   LMGTE Am
39      15                 Oak Racing         Oak Pescarolo - Judd       LMP1
40      66             JMW Motorsport           Ferrari 458 Italia  LMGTE Pro
41      48          Murphy Prototypes            Oreca 03 - Nissan       LMP2
42      77     Team Felbermayr-Proton        Porsche 911 RSR (997)  LMGTE Pro
43      75       Prospeed Competition        Porsche 911 RSR (997)   LMGTE Am
44      31                      Lotus    Lola B12/80 Coupe - Lotus       LMP2
45      58              Luxury Racing           Ferrari 458 Italia   LMGTE Am
46      24                 Oak Racing                Morgan - Judd       LMP2
47       7              Toyota Racing       Toyota TS 030 - Hybrid       LMP1
48      80  Flying Lizard Motorsports        Porsche 911 RSR (997)  LMGTE Pro
49      28    Gulf Racing Middle East  Lola  B12/80 Coupe - Nissan       LMP2
50       8              Toyota Racing       Toyota TS 030 - Hybrid       LMP1
51       0           Highcroft Racing            Delta Wing Nissan       CDNT
52      81                   AF Corse           Ferrari 458 Italia   LMGTE Am
53      99        Aston Martin Racing      Aston Martin Vantage V8   LMGTE Am
54      16             Pescarolo Team          Pescarolo 03 - Judd       LMP1
55      29    Gulf Racing Middle East  Lola  B12/80 Coupe - Nissan       LMP2
56      32                      Lotus    Lola B12/80 Coupé - Lotus       LMP2
57      98        Aston Martin Racing      Aston Martin Vantage V8   LMGTE Am

In [223]:
csv = "data/" + prefix_yr + tracks_2012[0] + ".csv"
combined_df = pd.read_csv(csv, index_col = 0)
combined_df.columns =  combined_df.columns.str.strip()
combined_df = combined_df.merge(classification_df, how = "inner")
combined_df.columns = combined_df.columns.str.strip()
combined_df['round'] = 1
combined_df

,NUMBER,DRIVER_NUMBER,LAP_NUMBER,LAP_TIME,LAP_IMPROVEMENT,CROSSING_FINISH_LINE_IN_PIT,S1,S1_IMPROVEMENT,S2,S2_IMPROVEMENT,...,TOP_SPEED,DRIVER_NAME,PIT_TIME,Unnamed: 21,season,circuit,round,TEAM,VEHICLE,CLASS
0,1,2,1,1:57.002,0,NaN,36.575,0,38.786,0,...,273.4,Benoit Tréluyer,NaN,NaN,2012,SEBRING,1,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1
1,1,2,2,1:49.997,0,NaN,32.678,0,38.707,0,...,275.1,Benoit Tréluyer,NaN,NaN,2012,SEBRING,1,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1
2,1,2,3,1:49.306,0,NaN,32.516,0,38.311,0,...,275.1,Benoit Tréluyer,NaN,NaN,2012,SEBRING,1,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1
3,1,2,4,1:48.975,0,NaN,32.115,0,38.539,0,...,274.5,Benoit Tréluyer,NaN,NaN,2012,SEBRING,1,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1
4,1,2,5,1:48.489,0,NaN,31.852,0,38.269,0,...,276.8,Benoit Tréluyer,NaN,NaN,2012,SEBRING,1,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7856,97,2,288,2:09.941,0,NaN,38.747,0,45.538,0,...,244.5,Darren Turner,NaN,NaN,2012,SEBRING,1,Aston Martin Racing,Aston Martin Vantage V8,LMGTE Pro
7857,97,2,289,3:22.938,0,B,37.619,0,44.882,0,...,245.0,Darren Turner,NaN,NaN,2012,SEBRING,1,Aston Martin Racing,Aston Martin Vantage V8,LMGTE Pro
7858,97,2,290,12:51.059,0,B,59.355,0,48.354,0,...,242.8,Darren Turner,0:01:36,NaN,2012,SEBRING,1,Aston Martin Racing,Aston Martin Vantage V8,LMGTE Pro
7859,97,2,291,2:41.519,0,NaN,1:02.220,0,51.014,0,...,214.5,Darren Turner,0:10:39,NaN,2012,SEBRING,1,Aston Martin Racing,Aston Martin Vantage V8,LMGTE Pro
7860,97,2,292,2:15.419,0,NaN,39.257,0,48.614,0,...,232.8,Darren Turner,NaN,NaN,2012,SEBRING,1,Aston Martin Racing,Aston Martin Vantage V8,LMGTE Pro

In [224]:
for i in range(1, len(tracks_2012)):
    csv = "data/" + prefix_yr + tracks_2012[i] + ".csv"
    if i >= 6:
        track_df = pd.read_csv(csv, sep=";")
    else:
        track_df = pd.read_csv(csv, index_col=0)
    track_df = track_df.merge(classification_df, how = "inner")
    track_df.columns =  track_df.columns.str.strip()
    track_df['season'] = year
    track_df['round'] = i+1
    track_df['circuit'] = tracks_2012[i]
    combined_df = combined_df.append(track_df)
combined_df

,NUMBER,DRIVER_NUMBER,LAP_NUMBER,LAP_TIME,LAP_IMPROVEMENT,CROSSING_FINISH_LINE_IN_PIT,S1,S1_IMPROVEMENT,S2,S2_IMPROVEMENT,...,circuit,round,TEAM,VEHICLE,CLASS,T6,T7,PORSCHE,FORD,Unnamed: 25
0,1,2,1,1:57.002,0,NaN,36.575,0,38.786,0,...,SEBRING,1,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1,NaN,NaN,NaN,NaN,NaN
1,1,2,2,1:49.997,0,NaN,32.678,0,38.707,0,...,SEBRING,1,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1,NaN,NaN,NaN,NaN,NaN
2,1,2,3,1:49.306,0,NaN,32.516,0,38.311,0,...,SEBRING,1,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1,NaN,NaN,NaN,NaN,NaN
3,1,2,4,1:48.975,0,NaN,32.115,0,38.539,0,...,SEBRING,1,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1,NaN,NaN,NaN,NaN,NaN
4,1,2,5,1:48.489,0,NaN,31.852,0,38.269,0,...,SEBRING,1,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4690,97,1,165,2:07.991,0,NaN,43.548,0,46.705,0,...,SHANGHAI_INTERNATIONAL_CIRCUIT,8,Aston Martin Racing,Aston Martin Vantage V8,LMGTE Pro,NaN,NaN,NaN,NaN,NaN
4691,97,1,166,2:08.433,0,NaN,43.369,0,46.205,0,...,SHANGHAI_INTERNATIONAL_CIRCUIT,8,Aston Martin Racing,Aston Martin Vantage V8,LMGTE Pro,NaN,NaN,NaN,NaN,NaN
4692,97,1,167,2:08.300,0,NaN,44.033,0,46.494,0,...,SHANGHAI_INTERNATIONAL_CIRCUIT,8,Aston Martin Racing,Aston Martin Vantage V8,LMGTE Pro,NaN,NaN,NaN,NaN,NaN
4693,97,1,168,2:10.378,0,NaN,43.811,0,48.549,0,...,SHANGHAI_INTERNATIONAL_CIRCUIT,8,Aston Martin Racing,Aston Martin Vantage V8,LMGTE Pro,NaN,NaN,NaN,NaN,NaN
4694,97,1,169,2:09.082,0,NaN,43.898,0,46.830,0,...,SHANGHAI_INTERNATIONAL_CIRCUIT,8,Aston Martin Racing,Aston Martin Vantage V8,LMGTE Pro,NaN,NaN,NaN,NaN,NaN

In [225]:
combined_df_nas = combined_df[combined_df['TEAM'].isna()]
combined_df_nas

Empty DataFrame
Columns: [NUMBER, DRIVER_NUMBER, LAP_NUMBER, LAP_TIME, LAP_IMPROVEMENT, CROSSING_FINISH_LINE_IN_PIT, S1, S1_IMPROVEMENT, S2, S2_IMPROVEMENT, S3, S3_IMPROVEMENT, KPH, ELAPSED, HOUR, S1_LARGE, S2_LARGE, S3_LARGE, TOP_SPEED, DRIVER_NAME, PIT_TIME, Unnamed: 21, season, circuit, round, TEAM, VEHICLE, CLASS, T6, T7, PORSCHE, FORD, Unnamed: 25]
Index: []

[0 rows x 33 columns]

In [226]:
combined_df = combined_df.dropna(axis = 1, how = 'all')
combined_df = combined_df.reset_index(drop=True)
combined_df

,NUMBER,DRIVER_NUMBER,LAP_NUMBER,LAP_TIME,LAP_IMPROVEMENT,CROSSING_FINISH_LINE_IN_PIT,S1,S1_IMPROVEMENT,S2,S2_IMPROVEMENT,...,season,circuit,round,TEAM,VEHICLE,CLASS,T6,T7,PORSCHE,FORD
0,1,2,1,1:57.002,0,NaN,36.575,0,38.786,0,...,2012,SEBRING,1,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1,NaN,NaN,NaN,NaN
1,1,2,2,1:49.997,0,NaN,32.678,0,38.707,0,...,2012,SEBRING,1,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1,NaN,NaN,NaN,NaN
2,1,2,3,1:49.306,0,NaN,32.516,0,38.311,0,...,2012,SEBRING,1,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1,NaN,NaN,NaN,NaN
3,1,2,4,1:48.975,0,NaN,32.115,0,38.539,0,...,2012,SEBRING,1,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1,NaN,NaN,NaN,NaN
4,1,2,5,1:48.489,0,NaN,31.852,0,38.269,0,...,2012,SEBRING,1,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54427,97,1,165,2:07.991,0,NaN,43.548,0,46.705,0,...,2012,SHANGHAI_INTERNATIONAL_CIRCUIT,8,Aston Martin Racing,Aston Martin Vantage V8,LMGTE Pro,NaN,NaN,NaN,NaN
54428,97,1,166,2:08.433,0,NaN,43.369,0,46.205,0,...,2012,SHANGHAI_INTERNATIONAL_CIRCUIT,8,Aston Martin Racing,Aston Martin Vantage V8,LMGTE Pro,NaN,NaN,NaN,NaN
54429,97,1,167,2:08.300,0,NaN,44.033,0,46.494,0,...,2012,SHANGHAI_INTERNATIONAL_CIRCUIT,8,Aston Martin Racing,Aston Martin Vantage V8,LMGTE Pro,NaN,NaN,NaN,NaN
54430,97,1,168,2:10.378,0,NaN,43.811,0,48.549,0,...,2012,SHANGHAI_INTERNATIONAL_CIRCUIT,8,Aston Martin Racing,Aston Martin Vantage V8,LMGTE Pro,NaN,NaN,NaN,NaN
54431,97,1,169,2:09.082,0,NaN,43.898,0,46.830,0,...,2012,SHANGHAI_INTERNATIONAL_CIRCUIT,8,Aston Martin Racing,Aston Martin Vantage V8,LMGTE Pro,NaN,NaN,NaN,NaN

In [227]:
csv_path = prefix_yr + "WEC_SEASON.csv"
combined_df.to_csv(csv_path, sep = ";")