In [55]:
import pandas as pd
import numpy as np

In [56]:
seasons = ['2012_', '2013_', '2014_', '2015_', '2016_', '2017_', '2018-2019_', '2019-2020_','2021_', '2022_']
season_csv = seasons[8] + "WEC_SEASON.csv"
season = pd.read_csv(season_csv, index_col =0, sep = ";")
season[season['GROUP'].notna()]

,NUMBER,DRIVER_NUMBER,LAP_NUMBER,LAP_TIME,LAP_IMPROVEMENT,CROSSING_FINISH_LINE_IN_PIT,S1,S1_IMPROVEMENT,S2,S2_IMPROVEMENT,...,TOP_SPEED,DRIVER_NAME,PIT_TIME,CLASS,GROUP,TEAM,MANUFACTURER,season,circuit,round
158,20,2,1,2:14.618,0,NaN,38.487,0,1:02.711,0,...,250.3,Anders FJORDBACH,NaN,LMP2,P/A,High Class Racing,Oreca,2021,SPA FRANCORCHAMPS,1
159,20,2,2,2:08.929,0,NaN,36.714,0,59.092,0,...,294.5,Anders FJORDBACH,NaN,LMP2,P/A,High Class Racing,Oreca,2021,SPA FRANCORCHAMPS,1
160,20,2,3,2:08.645,0,NaN,36.610,0,58.900,0,...,295.3,Anders FJORDBACH,NaN,LMP2,P/A,High Class Racing,Oreca,2021,SPA FRANCORCHAMPS,1
161,20,2,4,2:10.365,0,NaN,36.583,0,1:00.840,0,...,294.5,Anders FJORDBACH,NaN,LMP2,P/A,High Class Racing,Oreca,2021,SPA FRANCORCHAMPS,1
162,20,2,5,2:09.902,0,NaN,36.524,0,1:00.449,0,...,294.5,Anders FJORDBACH,NaN,LMP2,P/A,High Class Racing,Oreca,2021,SPA FRANCORCHAMPS,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48590,8,2,243,1:52.827,0,NaN,34.963,0,42.442,0,...,266.9,Kazuki NAKAJIMA,NaN,HYPERCAR,H,Toyota Gazoo Racing,Toyota,2021,BAHRAIN_INTERNATIONAL_CIRCUIT_8_HOURS,6
48591,8,2,244,1:52.432,0,NaN,34.864,0,42.340,0,...,263.6,Kazuki NAKAJIMA,NaN,HYPERCAR,H,Toyota Gazoo Racing,Toyota,2021,BAHRAIN_INTERNATIONAL_CIRCUIT_8_HOURS,6
48592,8,2,245,1:52.726,0,NaN,35.297,0,42.217,0,...,241.9,Kazuki NAKAJIMA,NaN,HYPERCAR,H,Toyota Gazoo Racing,Toyota,2021,BAHRAIN_INTERNATIONAL_CIRCUIT_8_HOURS,6
48593,8,2,246,1:53.440,0,NaN,35.225,0,42.799,0,...,240.8,Kazuki NAKAJIMA,NaN,HYPERCAR,H,Toyota Gazoo Racing,Toyota,2021,BAHRAIN_INTERNATIONAL_CIRCUIT_8_HOURS,6
48594,8,2,247,1:53.577,0,NaN,35.030,0,42.846,0,...,262.4,Kazuki NAKAJIMA,NaN,HYPERCAR,H,Toyota Gazoo Racing,Toyota,2021,BAHRAIN_INTERNATIONAL_CIRCUIT_8_HOURS,6

In [3]:
vehicle_man_lookup = pd.read_csv("vehicle_manufacturer_mapping.csv", index_col=0,sep = ";")
lookup_2014 = pd.read_csv("2014_mapping.csv",index_col=0, sep = ";")
lmp1_lookups = lookup_2014[(lookup_2014['CLASS'] == "LMP1-H") | (lookup_2014['CLASS'] == "LMP1-L")].reset_index(drop=True)
lmp1_lookups

                    VEHICLE   CLASS MANUFACTURER
0   Audi R18 e-tron quattro  LMP1-H         Audi
1        Porsche 919 Hybrid  LMP1-H      Porsche
2  Rebellion R-One - Toyota  LMP1-L    Rebellion
3    Toyota TS 040 - Hybrid  LMP1-H       Toyota

In [16]:
other_lookups = lookup_2014[(lookup_2014['CLASS'] != "LMP1-H") & (lookup_2014['CLASS'] != "LMP1-L")].reset_index(drop=True)
wanted_columns = ['VEHICLE', 'MANUFACTURER']
other_lookups = other_lookups[wanted_columns]
other_lookups

                    VEHICLE  MANUFACTURER
0     Alpine A450b - Nissan        Alpine
1   Aston Martin Vantage V8  Aston Martin
2   Chevrolet Corvette - C7     Chevrolet
3        Ferrari 458 Italia       Ferrari
4           Ligier - Nissan        Ligier
5        Ligier JS P2 - HPD        Ligier
6     Ligier JS P2 - Nissan        Ligier
7             Morgan - Judd        Morgan
8           Morgan - Nissan        Morgan
9            Nissan ZEOD RC        Nissan
10         Oreca 03R - Judd         Oreca
11       Oreca 03R - Nissan         Oreca
12      Porsche 911 GT3 RSR       Porsche
13          Porsche 911 RSR       Porsche
14     Zytek Z11SN - Nissan         Zytek

In [5]:
season_lmp1 = season[season['CLASS'] == "LMP1"].reset_index(drop=True)
season_lmp1

,NUMBER,DRIVER_NUMBER,LAP_NUMBER,LAP_TIME,LAP_IMPROVEMENT,CROSSING_FINISH_LINE_IN_PIT,S1,S1_IMPROVEMENT,S2,S2_IMPROVEMENT,...,round,TEAM,CLASS,VEHICLE,T6,T7,PORSCHE,FORD,GROUP,MANUFACTURER
0,1,0,1,1:50.025,0,NaN,34.368,0,44.737,0,...,1,Audi Sport Team Joest,LMP1,Audi R18 e-tron quattro,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0,2,1:47.971,0,NaN,33.893,0,45.075,0,...,1,Audi Sport Team Joest,LMP1,Audi R18 e-tron quattro,NaN,NaN,NaN,NaN,NaN,NaN
2,1,0,3,1:44.961,0,NaN,32.215,0,43.844,0,...,1,Audi Sport Team Joest,LMP1,Audi R18 e-tron quattro,NaN,NaN,NaN,NaN,NaN,NaN
3,1,0,4,1:45.228,0,NaN,32.317,0,43.945,0,...,1,Audi Sport Team Joest,LMP1,Audi R18 e-tron quattro,NaN,NaN,NaN,NaN,NaN,NaN
4,1,0,5,1:45.501,0,NaN,32.181,0,43.922,0,...,1,Audi Sport Team Joest,LMP1,Audi R18 e-tron quattro,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12583,8,0,245,2:37.069,0,NaN,38.915,0,1:13.696,0,...,8,Toyota Racing,LMP1,Toyota TS 040 - Hybrid,NaN,NaN,NaN,NaN,H,Toyota
12584,8,0,246,2:38.051,0,NaN,41.260,0,1:14.474,0,...,8,Toyota Racing,LMP1,Toyota TS 040 - Hybrid,NaN,NaN,NaN,NaN,H,Toyota
12585,8,0,247,2:38.538,0,NaN,41.319,0,1:13.871,0,...,8,Toyota Racing,LMP1,Toyota TS 040 - Hybrid,NaN,NaN,NaN,NaN,H,Toyota
12586,8,0,248,2:36.603,0,NaN,43.932,0,1:09.296,0,...,8,Toyota Racing,LMP1,Toyota TS 040 - Hybrid,NaN,NaN,NaN,NaN,H,Toyota
12587,8,0,249,2:07.067,0,NaN,34.782,0,59.550,0,...,8,Toyota Racing,LMP1,Toyota TS 040 - Hybrid,NaN,NaN,NaN,NaN,H,Toyota

In [14]:
season_lmp1_right_class = pd.merge(left = season_lmp1, right = lmp1_lookups, on = "VEHICLE", how = "outer")
season_lmp1_right_class['CLASS'] = season_lmp1_right_class['CLASS_y']
season_lmp1_right_class['MANUFACTURER'] = season_lmp1_right_class['MANUFACTURER_y']
season_lmp1_right_class = season_lmp1_right_class.drop(['CLASS_x', 'MANUFACTURER_x','CLASS_y', 'MANUFACTURER_y'], axis=1)

In [17]:
season_not_lmp1 = season[season['CLASS'] != "LMP1"].reset_index(drop=True)
season_not_lmp1

,NUMBER,DRIVER_NUMBER,LAP_NUMBER,LAP_TIME,LAP_IMPROVEMENT,CROSSING_FINISH_LINE_IN_PIT,S1,S1_IMPROVEMENT,S2,S2_IMPROVEMENT,...,round,TEAM,CLASS,VEHICLE,T6,T7,PORSCHE,FORD,GROUP,MANUFACTURER
0,26,1,1,1:58.243,0,NaN,38.648,0,48.412,0,...,1,G-Drive Racing,LMP2,Morgan - Nissan,NaN,NaN,NaN,NaN,NaN,NaN
1,26,1,2,1:52.384,0,NaN,34.242,0,47.227,0,...,1,G-Drive Racing,LMP2,Morgan - Nissan,NaN,NaN,NaN,NaN,NaN,NaN
2,26,1,3,1:51.339,2,NaN,33.989,0,46.698,2,...,1,G-Drive Racing,LMP2,Morgan - Nissan,NaN,NaN,NaN,NaN,NaN,NaN
3,26,1,4,1:51.639,0,NaN,33.928,0,46.828,0,...,1,G-Drive Racing,LMP2,Morgan - Nissan,NaN,NaN,NaN,NaN,NaN,NaN
4,26,1,5,1:51.410,0,NaN,33.850,2,46.811,0,...,1,G-Drive Racing,LMP2,Morgan - Nissan,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31051,98,1,215,2:35.332,0,NaN,39.479,0,1:09.527,0,...,8,Aston Martin Racing,LMGTE Am,Aston Martin Vantage V8,NaN,NaN,NaN,NaN,NaN,Aston Martin
31052,98,1,216,2:38.973,0,NaN,44.519,0,1:10.648,0,...,8,Aston Martin Racing,LMGTE Am,Aston Martin Vantage V8,NaN,NaN,NaN,NaN,NaN,Aston Martin
31053,98,1,217,2:38.636,0,NaN,42.861,0,1:13.425,0,...,8,Aston Martin Racing,LMGTE Am,Aston Martin Vantage V8,NaN,NaN,NaN,NaN,NaN,Aston Martin
31054,98,1,218,2:38.861,0,NaN,47.067,0,1:09.948,0,...,8,Aston Martin Racing,LMGTE Am,Aston Martin Vantage V8,NaN,NaN,NaN,NaN,NaN,Aston Martin
31055,98,1,219,2:05.050,0,NaN,38.385,0,58.185,0,...,8,Aston Martin Racing,LMGTE Am,Aston Martin Vantage V8,NaN,NaN,NaN,NaN,NaN,Aston Martin

In [22]:
season_not_lmp1_right_man = pd.merge(left = season_not_lmp1, right = other_lookups, on = "VEHICLE", how = "outer")
season_not_lmp1_right_man['MANUFACTURER'] = season_not_lmp1_right_man['MANUFACTURER_y']
season_not_lmp1_right_man = season_not_lmp1_right_man.drop(['MANUFACTURER_x','MANUFACTURER_y'], axis=1)
season_not_lmp1_right_man

,NUMBER,DRIVER_NUMBER,LAP_NUMBER,LAP_TIME,LAP_IMPROVEMENT,CROSSING_FINISH_LINE_IN_PIT,S1,S1_IMPROVEMENT,S2,S2_IMPROVEMENT,...,round,TEAM,CLASS,VEHICLE,T6,T7,PORSCHE,FORD,GROUP,MANUFACTURER
0,26,1,1,1:58.243,0,NaN,38.648,0,48.412,0,...,1,G-Drive Racing,LMP2,Morgan - Nissan,NaN,NaN,NaN,NaN,NaN,Morgan
1,26,1,2,1:52.384,0,NaN,34.242,0,47.227,0,...,1,G-Drive Racing,LMP2,Morgan - Nissan,NaN,NaN,NaN,NaN,NaN,Morgan
2,26,1,3,1:51.339,2,NaN,33.989,0,46.698,2,...,1,G-Drive Racing,LMP2,Morgan - Nissan,NaN,NaN,NaN,NaN,NaN,Morgan
3,26,1,4,1:51.639,0,NaN,33.928,0,46.828,0,...,1,G-Drive Racing,LMP2,Morgan - Nissan,NaN,NaN,NaN,NaN,NaN,Morgan
4,26,1,5,1:51.410,0,NaN,33.850,2,46.811,0,...,1,G-Drive Racing,LMP2,Morgan - Nissan,NaN,NaN,NaN,NaN,NaN,Morgan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31051,74,1,329,3:58.829,0,NaN,38.213,0,1:31.325,0,...,3,Corvette Racing,LMGTE Pro,Chevrolet Corvette - C7,NaN,NaN,NaN,NaN,NaN,Chevrolet
31052,74,1,330,3:59.186,0,NaN,38.036,0,1:30.736,0,...,3,Corvette Racing,LMGTE Pro,Chevrolet Corvette - C7,NaN,NaN,NaN,NaN,NaN,Chevrolet
31053,74,1,331,3:58.607,0,NaN,37.991,0,1:30.846,0,...,3,Corvette Racing,LMGTE Pro,Chevrolet Corvette - C7,NaN,NaN,NaN,NaN,NaN,Chevrolet
31054,74,1,332,4:01.070,0,NaN,38.389,0,1:31.921,0,...,3,Corvette Racing,LMGTE Pro,Chevrolet Corvette - C7,NaN,NaN,NaN,NaN,NaN,Chevrolet
31055,74,1,333,4:36.217,0,NaN,38.263,0,1:34.593,0,...,3,Corvette Racing,LMGTE Pro,Chevrolet Corvette - C7,NaN,NaN,NaN,NaN,NaN,Chevrolet

In [26]:
season_combined = season_lmp1_right_class.append(season_not_lmp1_right_man).reset_index(drop="True")
season_combined = season_combined.drop('GROUP', axis=1)
season_combined.to_csv("2014_WEC_SEASON_w_man.csv", sep = ";")

In [37]:
season_combined = pd.read_csv("2012_WEC_SEASON_w_man.csv", index_col=0, sep=";")
season_combined

,NUMBER,DRIVER_NUMBER,LAP_NUMBER,LAP_TIME,LAP_IMPROVEMENT,CROSSING_FINISH_LINE_IN_PIT,S1,S1_IMPROVEMENT,S2,S2_IMPROVEMENT,...,circuit,round,TEAM,VEHICLE,CLASS,T6,T7,PORSCHE,FORD,MANUFACTURER
0,1.0,2.0,1.0,1:57.002,0.0,NaN,36.575,0.0,38.786,0.0,...,SEBRING,1.0,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1,NaN,NaN,NaN,NaN,Audi
1,1.0,2.0,2.0,1:49.997,0.0,NaN,32.678,0.0,38.707,0.0,...,SEBRING,1.0,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1,NaN,NaN,NaN,NaN,Audi
2,1.0,2.0,3.0,1:49.306,0.0,NaN,32.516,0.0,38.311,0.0,...,SEBRING,1.0,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1,NaN,NaN,NaN,NaN,Audi
3,1.0,2.0,4.0,1:48.975,0.0,NaN,32.115,0.0,38.539,0.0,...,SEBRING,1.0,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1,NaN,NaN,NaN,NaN,Audi
4,1.0,2.0,5.0,1:48.489,0.0,NaN,31.852,0.0,38.269,0.0,...,SEBRING,1.0,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1,NaN,NaN,NaN,NaN,Audi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54427,7.0,0.0,187.0,1:52.368,0.0,NaN,37.843,0.0,40.710,0.0,...,SHANGHAI_INTERNATIONAL_CIRCUIT,8.0,Toyota Racing,Toyota TS 030 - Hybrid,LMP1,NaN,NaN,NaN,NaN,Toyota
54428,7.0,0.0,188.0,1:53.409,0.0,NaN,39.227,0.0,40.589,0.0,...,SHANGHAI_INTERNATIONAL_CIRCUIT,8.0,Toyota Racing,Toyota TS 030 - Hybrid,LMP1,NaN,NaN,NaN,NaN,Toyota
54429,7.0,0.0,189.0,1:51.816,0.0,NaN,37.957,0.0,40.569,0.0,...,SHANGHAI_INTERNATIONAL_CIRCUIT,8.0,Toyota Racing,Toyota TS 030 - Hybrid,LMP1,NaN,NaN,NaN,NaN,Toyota
54430,7.0,0.0,190.0,1:51.166,0.0,NaN,38.010,0.0,39.795,0.0,...,SHANGHAI_INTERNATIONAL_CIRCUIT,8.0,Toyota Racing,Toyota TS 030 - Hybrid,LMP1,NaN,NaN,NaN,NaN,Toyota
54431,7.0,0.0,191.0,1:54.136,0.0,NaN,38.175,0.0,40.297,0.0,...,SHANGHAI_INTERNATIONAL_CIRCUIT,8.0,Toyota Racing,Toyota TS 030 - Hybrid,LMP1,NaN,NaN,NaN,NaN,Toyota

In [38]:
for i in range(0, len(seasons)):
    if i <= 2:
        csv_path = seasons[i] +  "WEC_SEASON_w_man.csv"
    else:
        csv_path = 
    df = pd.read_csv(csv_path, sep = ";", index_col = 0)
    season_combined = season_combined.append(df)
season_combined = season_combined.reset_index(drop=True)
season_combined

,NUMBER,DRIVER_NUMBER,LAP_NUMBER,LAP_TIME,LAP_IMPROVEMENT,CROSSING_FINISH_LINE_IN_PIT,S1,S1_IMPROVEMENT,S2,S2_IMPROVEMENT,...,circuit,round,TEAM,VEHICLE,CLASS,T6,T7,PORSCHE,FORD,MANUFACTURER
0,1.0,2.0,1.0,1:57.002,0.0,NaN,36.575,0.0,38.786,0.0,...,SEBRING,1.0,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1,NaN,NaN,NaN,NaN,Audi
1,1.0,2.0,2.0,1:49.997,0.0,NaN,32.678,0.0,38.707,0.0,...,SEBRING,1.0,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1,NaN,NaN,NaN,NaN,Audi
2,1.0,2.0,3.0,1:49.306,0.0,NaN,32.516,0.0,38.311,0.0,...,SEBRING,1.0,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1,NaN,NaN,NaN,NaN,Audi
3,1.0,2.0,4.0,1:48.975,0.0,NaN,32.115,0.0,38.539,0.0,...,SEBRING,1.0,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1,NaN,NaN,NaN,NaN,Audi
4,1.0,2.0,5.0,1:48.489,0.0,NaN,31.852,0.0,38.269,0.0,...,SEBRING,1.0,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1,NaN,NaN,NaN,NaN,Audi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132154,74.0,1.0,329.0,3:58.829,0.0,NaN,38.213,0.0,1:31.325,0.0,...,LE_MANS,3.0,Corvette Racing,Chevrolet Corvette - C7,LMGTE Pro,NaN,NaN,NaN,NaN,Chevrolet
132155,74.0,1.0,330.0,3:59.186,0.0,NaN,38.036,0.0,1:30.736,0.0,...,LE_MANS,3.0,Corvette Racing,Chevrolet Corvette - C7,LMGTE Pro,NaN,NaN,NaN,NaN,Chevrolet
132156,74.0,1.0,331.0,3:58.607,0.0,NaN,37.991,0.0,1:30.846,0.0,...,LE_MANS,3.0,Corvette Racing,Chevrolet Corvette - C7,LMGTE Pro,NaN,NaN,NaN,NaN,Chevrolet
132157,74.0,1.0,332.0,4:01.070,0.0,NaN,38.389,0.0,1:31.921,0.0,...,LE_MANS,3.0,Corvette Racing,Chevrolet Corvette - C7,LMGTE Pro,NaN,NaN,NaN,NaN,Chevrolet
132158,74.0,1.0,333.0,4:36.217,0.0,NaN,38.263,0.0,1:34.593,0.0,...,LE_MANS,3.0,Corvette Racing,Chevrolet Corvette - C7,LMGTE Pro,NaN,NaN,NaN,NaN,Chevrolet

In [43]:
season_combined_2013 = season_combined[season_combined['season'] == 2014]
season_combined_2013

,NUMBER,DRIVER_NUMBER,LAP_NUMBER,LAP_TIME,LAP_IMPROVEMENT,CROSSING_FINISH_LINE_IN_PIT,S1,S1_IMPROVEMENT,S2,S2_IMPROVEMENT,...,circuit,round,TEAM,VEHICLE,CLASS,T6,T7,PORSCHE,FORD,MANUFACTURER
88515,1.0,0.0,1.0,1:50.025,0.0,NaN,34.368,0.0,44.737,0.0,...,SILVERSTONE,1.0,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1-H,NaN,NaN,NaN,NaN,Audi
88516,1.0,0.0,2.0,1:47.971,0.0,NaN,33.893,0.0,45.075,0.0,...,SILVERSTONE,1.0,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1-H,NaN,NaN,NaN,NaN,Audi
88517,1.0,0.0,3.0,1:44.961,0.0,NaN,32.215,0.0,43.844,0.0,...,SILVERSTONE,1.0,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1-H,NaN,NaN,NaN,NaN,Audi
88518,1.0,0.0,4.0,1:45.228,0.0,NaN,32.317,0.0,43.945,0.0,...,SILVERSTONE,1.0,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1-H,NaN,NaN,NaN,NaN,Audi
88519,1.0,0.0,5.0,1:45.501,0.0,NaN,32.181,0.0,43.922,0.0,...,SILVERSTONE,1.0,Audi Sport Team Joest,Audi R18 e-tron quattro,LMP1-H,NaN,NaN,NaN,NaN,Audi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132154,74.0,1.0,329.0,3:58.829,0.0,NaN,38.213,0.0,1:31.325,0.0,...,LE_MANS,3.0,Corvette Racing,Chevrolet Corvette - C7,LMGTE Pro,NaN,NaN,NaN,NaN,Chevrolet
132155,74.0,1.0,330.0,3:59.186,0.0,NaN,38.036,0.0,1:30.736,0.0,...,LE_MANS,3.0,Corvette Racing,Chevrolet Corvette - C7,LMGTE Pro,NaN,NaN,NaN,NaN,Chevrolet
132156,74.0,1.0,331.0,3:58.607,0.0,NaN,37.991,0.0,1:30.846,0.0,...,LE_MANS,3.0,Corvette Racing,Chevrolet Corvette - C7,LMGTE Pro,NaN,NaN,NaN,NaN,Chevrolet
132157,74.0,1.0,332.0,4:01.070,0.0,NaN,38.389,0.0,1:31.921,0.0,...,LE_MANS,3.0,Corvette Racing,Chevrolet Corvette - C7,LMGTE Pro,NaN,NaN,NaN,NaN,Chevrolet
132158,74.0,1.0,333.0,4:36.217,0.0,NaN,38.263,0.0,1:34.593,0.0,...,LE_MANS,3.0,Corvette Racing,Chevrolet Corvette - C7,LMGTE Pro,NaN,NaN,NaN,NaN,Chevrolet

In [ ]:
season_manufacturer_na = season_combined[season_combined['MANUFACTURER'].isna()]
wanted_columns = ['VEHICLE', 'CLASS']
season_manufacturer_na = season_manufacturer_na.groupby(wanted_columns).mean().reset_index([0,1])
season_manufacturer_na = season_manufacturer_na[wanted_columns]
season_manufacturer_na['MANUFACTURER'] = np.nan
#season_manufacturer_na.to_csv('2012_season_man_mapping.csv')

In [ ]:

season_manufacturer = pd.merge(left = season, right = vehicle_man_lookup, on = 'VEHICLE', how = "outer")
season_manufacturer = season_manufacturer[season_manufacturer['TEAM'].notna()]
wanted_columns = ['VEHICLE', 'CLASS_x']
season_man = season_manufacturer.groupby(wanted_columns).mean().reset_index([0,1])
season_man = season_man[wanted_columns]
#season_man.to_csv('2014_mapping.csv', sep=";")