In [150]:
import pandas as pd
import numpy as np

In [151]:
fia_wec_data = pd.read_csv('2012-2022_FIA_WEC_FULL_LAP_DATA.csv', index_col = 0)

C:\Users\trist\AppData\Local\Programs\Python\Python38\lib\site-packages\IPython\core\interactiveshell.py:3331: DtypeWarning: Columns (23,26,29,30,31,32,34) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [152]:
fia_wec_data['season'] = fia_wec_data['season'].map(str)
#break it into gte, p2 and p1
fia_wec_data_gte = fia_wec_data[fia_wec_data['class'].str.contains("LMGTE")].reset_index(drop=True)
fia_wec_data_lmp2 = fia_wec_data[fia_wec_data['class'].str.contains("LMP2")].reset_index(drop=True)
fia_wec_data_lmp1 = fia_wec_data[fia_wec_data['class'].str.contains("LMP1")|fia_wec_data['class'].str.contains("HYPERCAR")].reset_index(drop=True)
fia_wec_data_misc = fia_wec_data[fia_wec_data['class'].str.contains("INNOVATIVE CAR")|fia_wec_data['class'].str.contains("CDNT")]
fia_wec_data_misc.reset_index(drop=True)

,number,driver_number,lap_number,lap_time,lap_improvement,crossing_finish_line_in_pit,s1,s1_improvement,s2,s2_improvement,...,t6,t7,porsche,ford,vehicle,flag_at_fl,team_no,lap_time_ms,lap_time_s,engine
0,0.0,1.0,1.0,4:21.958,0.0,NaN,57.805,0.0,1:32.907,0.0,...,0:03.843,NaN,0:21.258,0:07.847,Delta Wing Nissan,NaN,Highcroft Racing #0,261958.0,261.958,Nissan
1,0.0,1.0,2.0,3:56.264,0.0,NaN,37.908,0.0,1:30.948,0.0,...,0:03.843,0:04.203,0:20.033,0:06.830,Delta Wing Nissan,NaN,Highcroft Racing #0,236264.0,236.264,Nissan
2,0.0,1.0,3.0,3:56.285,0.0,NaN,39.460,0.0,1:30.659,0.0,...,0:03.635,0:04.209,0:19.571,0:06.834,Delta Wing Nissan,NaN,Highcroft Racing #0,236285.0,236.285,Nissan
3,0.0,1.0,4.0,3:51.298,0.0,NaN,36.586,0.0,1:28.522,0.0,...,0:03.571,0:04.116,0:19.789,0:06.687,Delta Wing Nissan,NaN,Highcroft Racing #0,231298.0,231.298,Nissan
4,0.0,1.0,5.0,3:49.693,0.0,NaN,36.421,0.0,1:28.633,0.0,...,0:03.602,0:04.100,0:19.066,0:06.688,Delta Wing Nissan,NaN,Highcroft Racing #0,229693.0,229.693,Nissan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
724,84.0,1.0,330.0,4:04.252,0.0,B,38.128,0.0,1:27.214,0.0,...,NaN,NaN,NaN,NaN,Oreca 07,NaN,Association SRT41 #84,244252.0,244.252,Gibson
725,84.0,1.0,331.0,5:01.193,0.0,NaN,1:47.160,0.0,1:27.483,0.0,...,NaN,NaN,NaN,NaN,Oreca 07,NaN,Association SRT41 #84,301193.0,301.193,Gibson
726,84.0,1.0,332.0,3:50.136,0.0,NaN,37.062,0.0,1:26.542,0.0,...,NaN,NaN,NaN,NaN,Oreca 07,NaN,Association SRT41 #84,230136.0,230.136,Gibson
727,84.0,1.0,333.0,3:49.041,0.0,NaN,36.569,0.0,1:26.499,0.0,...,NaN,NaN,NaN,NaN,Oreca 07,NaN,Association SRT41 #84,229041.0,229.041,Gibson
728,84.0,1.0,334.0,3:57.733,0.0,NaN,40.911,0.0,1:29.111,0.0,...,NaN,NaN,NaN,NaN,Oreca 07,NaN,Association SRT41 #84,237733.0,237.733,Gibson

In [153]:
fia_wec_data.groupby("class").mean()

,number,driver_number,lap_number,lap_improvement,s1_improvement,s2_improvement,s3_improvement,kph,top_speed,round,lap_time_ms,lap_time_s
class,,,,,,,,,,,,
CDNT,66.987342,1.222785,133.253165,0.015190,0.022785,0.022785,0.022785,193.825316,278.980759,3.000000,278448.665823,278.448666
HYPERCAR,177.227647,1.998732,131.197527,0.009670,0.017914,0.017755,0.017914,191.588396,290.475986,3.262048,151035.873811,151.035874
INNOVATIVE CAR,84.000000,2.104790,167.500000,0.005988,0.011976,0.011976,0.011976,197.904491,290.617066,4.000000,259289.083832,259.289084
LMGTE Am,82.794095,1.469006,112.536399,0.010374,0.020418,0.020434,0.020458,169.306063,254.556708,4.306365,181438.871338,181.438871
LMGTE Pro,77.644961,1.069517,111.900550,0.010298,0.017035,0.017066,0.017066,171.257552,256.940804,4.441672,172506.449188,172.506449
LMP1,7.651117,1.178525,116.224057,0.010815,0.019924,0.019974,0.019962,188.912200,279.330051,4.384302,152788.633640,152.788634
LMP1-H,8.576869,0.950792,114.486270,0.010824,0.019643,0.019643,0.019643,189.590840,279.113159,4.668270,136244.724093,136.244724
LMP1-L,12.394253,1.013410,100.253257,0.012261,0.023755,0.023755,0.023755,177.640307,281.991901,4.967816,144929.270115,144.929270
LMP2,34.196935,1.395113,122.494383,0.009527,0.018573,0.018604,0.018598,183.557216,274.952876,4.277797,174267.210592,174.267211

In [154]:
#oh this might be easier if I just do this:
gte_vehicles = fia_wec_data_gte.groupby(["season", "vehicle"]).mean().reset_index()
gte_vehicles['vehicle_actual'] = np.nan
wanted_columns = ['vehicle', 'season','vehicle_actual']
gte_vehicles = gte_vehicles[wanted_columns]
#gte_vehicles.to_csv("gtes.csv")

In [155]:
gte_vehicles = pd.read_csv("gtes.csv", index_col=0)
gte_vehicles['vehicle_season'] = gte_vehicles['vehicle'] + "_" + gte_vehicles['season']
wanted_columns = ['vehicle_actual', 'vehicle_season']
gte_vehicles_fixed = gte_vehicles[wanted_columns]
gte_vehicles_fixed

                 vehicle_actual                      vehicle_season
0      Aston Martin Vantage GT2        Aston Martin Vantage V8_2012
1   Chevrolet Corvette C6.R GT2      Chevrolet Corvette C6 ZR1_2012
2        Ferrari 458 Italia GT2             Ferrari 458 Italia_2012
3           Porsche 997 GT3-RSR          Porsche 911 RSR (997)_2012
4      Aston Martin Vantage GT2        Aston Martin Vantage V8_2013
5   Chevrolet Corvette C6.R GT2        Chevrolet Corvette - C7_2013
6        Ferrari 458 Italia GT2             Ferrari 458 Italia_2013
7           Porsche 997 GT3-RSR            Porsche 911 GT3 RSR_2013
8               Porsche 911 RSR                Porsche 911 RSR_2013
9      Aston Martin Vantage GT2        Aston Martin Vantage V8_2014
10      Chevrolet Corvette C7.R        Chevrolet Corvette - C7_2014
11       Ferrari 458 Italia GT2             Ferrari 458 Italia_2014
12              Porsche 911 RSR            Porsche 911 GT3 RSR_2014
13              Porsche 911 RSR                Porsche 911 RSR_2014
14     Aston Martin Vantage GT2        Aston Martin Vantage V8_2015
15      Chevrolet Corvette C7.R         Chevrolet Corvette C7R_2015
16       Ferrari 458 Italia GT2             Ferrari 458 Italia_2015
17              Porsche 911 RSR      Porsche 911 GT3 RSR (997)_2015
18              Porsche 911 RSR                Porsche 911 RSR_2015
19              SRT VIPER GTS-R                Srt VIPER GTS-R_2015
20     Aston Martin Vantage GT2        Aston Martin Vantage V8_2016
21      Chevrolet Corvette C7.R          Chevrolet Corvette C7_2016
22              Ferrari 488 GTE                Ferrari 488 GTE_2016
23       Ferrari 458 Italia GT2            Ferrari F458 Italia_2016
24                      Ford GT                        Ford GT_2016
25              Porsche 911 RSR                Porsche 911 RSR_2016
26              Porsche 911 RSR         Porsche 911 RSR (2016)_2016
27     Aston Martin Vantage GT2           Aston Martin Vantage_2017
28      Chevrolet Corvette C7.R        Chevrolet Corvette C7.R_2017
29              Ferrari 488 GTE                Ferrari 488 GTE_2017
30                      Ford GT                        Ford GT_2017
31              Porsche 911 RSR                Porsche 911 RSR_2017
32              Porsche 911 RSR         Porsche 911 RSR (2016)_2017
33              Porsche 911 RSR            Porsche 911 RSR 991_2017
34     Aston Martin Vantage GTE      Aston Martin Vantage_2018-2019
35     Aston Martin Vantage GTE  Aston Martin Vantage AMR_2018-2019
36                   BMW M8 GTE                BMW M8 GTE_2018-2019
37      Chevrolet Corvette C7.R   Chevrolet Corvette C7.R_2018-2019
38              Ferrari 488 GTE           Ferrari 488 GTE_2018-2019
39          Ferrari 488 GTE Evo       Ferrari 488 GTE EVO_2018-2019
40                      Ford GT                   Ford GT_2018-2019
41           Porsche 911 RSR-19           Porsche 911 RSR_2018-2019
42     Aston Martin Vantage GTE  Aston Martin Vantage AMR_2019-2020
43          Ferrari 488 GTE Evo       Ferrari 488 GTE Evo_2019-2020
44           Porsche 911 RSR-19           Porsche 911 RSR_2019-2020
45           Porsche 911 RSR-19      Porsche 911 RSR - 19_2019-2020
46     Aston Martin Vantage GTE       Aston Martin Vantage AMR_2021
47      Chevrolet Corvette C8.R        Chevrolet Corvette C8.R_2021
48          Ferrari 488 GTE Evo            Ferrari 488 GTE Evo_2021
49           Porsche 911 RSR-19           Porsche 911 RSR - 19_2021
50     Aston Martin Vantage GTE       Aston Martin Vantage AMR_2022
51      Chevrolet Corvette C8.R        Chevrolet Corvette C8.R_2022
52          Ferrari 488 GTE Evo            Ferrari 488 GTE Evo_2022
53           Porsche 911 RSR-19           Porsche 911 RSR - 19_2022

In [156]:
fia_wec_data_gte['vehicle_season'] = fia_wec_data_gte['vehicle'] + "_" + fia_wec_data_gte['season']
fia_wec_data_gte

,number,driver_number,lap_number,lap_time,lap_improvement,crossing_finish_line_in_pit,s1,s1_improvement,s2,s2_improvement,...,t7,porsche,ford,vehicle,flag_at_fl,team_no,lap_time_ms,lap_time_s,engine,vehicle_season
0,50.0,1.0,1.0,2:10.603,0.0,NaN,44.345,0.0,52.513,0.0,...,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,130603.0,130.603,Chevrolet,Chevrolet Corvette C7.R_2015
1,50.0,1.0,2.0,2:02.960,0.0,NaN,37.242,0.0,52.167,0.0,...,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,122960.0,122.960,Chevrolet,Chevrolet Corvette C7.R_2015
2,50.0,1.0,3.0,2:03.938,0.0,NaN,37.255,0.0,52.454,0.0,...,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,123938.0,123.938,Chevrolet,Chevrolet Corvette C7.R_2015
3,50.0,1.0,4.0,2:03.733,0.0,NaN,37.649,0.0,52.314,0.0,...,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,123733.0,123.733,Chevrolet,Chevrolet Corvette C7.R_2015
4,50.0,1.0,5.0,2:03.224,0.0,NaN,37.396,0.0,52.275,0.0,...,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,123224.0,123.224,Chevrolet,Chevrolet Corvette C7.R_2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222809,85.0,2.0,330.0,3:55.968,0.0,NaN,37.231,0.0,1:30.297,0.0,...,NaN,NaN,NaN,Ford GT,NaN,Keating Motorsports #85,235968.0,235.968,Ford,Ford GT_2018-2019
222810,85.0,2.0,331.0,3:57.188,0.0,NaN,37.105,0.0,1:30.253,0.0,...,NaN,NaN,NaN,Ford GT,NaN,Keating Motorsports #85,237188.0,237.188,Ford,Ford GT_2018-2019
222811,85.0,2.0,332.0,3:58.178,0.0,NaN,37.227,0.0,1:30.844,0.0,...,NaN,NaN,NaN,Ford GT,NaN,Keating Motorsports #85,238178.0,238.178,Ford,Ford GT_2018-2019
222812,85.0,2.0,333.0,4:00.230,0.0,NaN,37.852,0.0,1:31.576,0.0,...,NaN,NaN,NaN,Ford GT,NaN,Keating Motorsports #85,240230.0,240.230,Ford,Ford GT_2018-2019
222813,85.0,2.0,334.0,4:04.206,0.0,NaN,38.379,0.0,1:32.239,0.0,...,NaN,NaN,NaN,Ford GT,NaN,Keating Motorsports #85,244206.0,244.206,Ford,Ford GT_2018-2019

In [157]:
fia_wec_data_gte_fixed = pd.merge(left = fia_wec_data_gte, right = gte_vehicles_fixed, on = "vehicle_season", how = "left")
#fia_wec_data_gte_fixed['vehicle'] = fia_wec_data_gte_fixed['vehicle_actual']
fia_wec_data_gte_fixed = fia_wec_data_gte_fixed.drop(['vehicle_season', 'vehicle_actual'], axis=1)
fia_wec_data_gte_fixed

,number,driver_number,lap_number,lap_time,lap_improvement,crossing_finish_line_in_pit,s1,s1_improvement,s2,s2_improvement,...,t6,t7,porsche,ford,vehicle,flag_at_fl,team_no,lap_time_ms,lap_time_s,engine
0,50.0,1.0,1.0,2:10.603,0.0,NaN,44.345,0.0,52.513,0.0,...,NaN,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,130603.0,130.603,Chevrolet
1,50.0,1.0,2.0,2:02.960,0.0,NaN,37.242,0.0,52.167,0.0,...,NaN,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,122960.0,122.960,Chevrolet
2,50.0,1.0,3.0,2:03.938,0.0,NaN,37.255,0.0,52.454,0.0,...,NaN,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,123938.0,123.938,Chevrolet
3,50.0,1.0,4.0,2:03.733,0.0,NaN,37.649,0.0,52.314,0.0,...,NaN,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,123733.0,123.733,Chevrolet
4,50.0,1.0,5.0,2:03.224,0.0,NaN,37.396,0.0,52.275,0.0,...,NaN,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,123224.0,123.224,Chevrolet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222809,85.0,2.0,330.0,3:55.968,0.0,NaN,37.231,0.0,1:30.297,0.0,...,NaN,NaN,NaN,NaN,Ford GT,NaN,Keating Motorsports #85,235968.0,235.968,Ford
222810,85.0,2.0,331.0,3:57.188,0.0,NaN,37.105,0.0,1:30.253,0.0,...,NaN,NaN,NaN,NaN,Ford GT,NaN,Keating Motorsports #85,237188.0,237.188,Ford
222811,85.0,2.0,332.0,3:58.178,0.0,NaN,37.227,0.0,1:30.844,0.0,...,NaN,NaN,NaN,NaN,Ford GT,NaN,Keating Motorsports #85,238178.0,238.178,Ford
222812,85.0,2.0,333.0,4:00.230,0.0,NaN,37.852,0.0,1:31.576,0.0,...,NaN,NaN,NaN,NaN,Ford GT,NaN,Keating Motorsports #85,240230.0,240.230,Ford
222813,85.0,2.0,334.0,4:04.206,0.0,NaN,38.379,0.0,1:32.239,0.0,...,NaN,NaN,NaN,NaN,Ford GT,NaN,Keating Motorsports #85,244206.0,244.206,Ford

In [209]:
gte_vehicles_fixed = pd.read_csv("gtes.csv", index_col=0)
wanted_columns = ['vehicle_actual', 'season']
gte_vehicles_fixed = gte_vehicles_fixed[wanted_columns]
gte_vehicles_fixed = gte_vehicles_fixed[(gte_vehicles_fixed['season'] == "2021")|(gte_vehicles_fixed['season'] == "2018-2019")|(gte_vehicles_fixed['season'] == "2016")].drop_duplicates().reset_index(drop=True)
gte_vehicles_fixed['manufacturer'] = gte_vehicles_fixed['vehicle_actual'].str.split(expand = True)[0]
gte_vehicles_fixed['man_season'] = gte_vehicles_fixed['manufacturer'] + "_" + gte_vehicles_fixed['season'] 
gte_vehicles_fixed = gte_vehicles_fixed.groupby(['man_season', 'vehicle_actual']).mean().drop_duplicates().reset_index()
gte_vehicles_fixed

C:\Users\trist\AppData\Local\Programs\Python\Python38\lib\site-packages\IPython\core\interactiveshell.py:3331: FutureWarning: Dropping invalid columns in DataFrameGroupBy.mean is deprecated. In a future version, a TypeError will be raised. Before calling .mean, select only columns which should be valid for the function.
  exec(code_obj, self.user_global_ns, self.user_ns)

             man_season            vehicle_actual
0            Aston_2016  Aston Martin Vantage GT2
1       Aston_2018-2019  Aston Martin Vantage GTE
2            Aston_2021  Aston Martin Vantage GTE
3         BMW_2018-2019                BMW M8 GTE
4        Chevrolet_2016   Chevrolet Corvette C7.R
5   Chevrolet_2018-2019   Chevrolet Corvette C7.R
6        Chevrolet_2021   Chevrolet Corvette C8.R
7          Ferrari_2016    Ferrari 458 Italia GT2
8          Ferrari_2016           Ferrari 488 GTE
9     Ferrari_2018-2019           Ferrari 488 GTE
10    Ferrari_2018-2019       Ferrari 488 GTE Evo
11         Ferrari_2021       Ferrari 488 GTE Evo
12            Ford_2016                   Ford GT
13       Ford_2018-2019                   Ford GT
14         Porsche_2016           Porsche 911 RSR
15    Porsche_2018-2019        Porsche 911 RSR-19
16         Porsche_2021        Porsche 911 RSR-19

In [220]:
gte_data_missing = fia_wec_data_gte_fixed[fia_wec_data_gte_fixed['vehicle'].isna()]
gte_data_notmissing = fia_wec_data_gte_fixed[fia_wec_data_gte_fixed['vehicle'].notna()]

gte_missing_vehicles = pd.read_csv("gtes_missing.csv", index_col=0)
wanted_columns = ["vehicle", "team_no"]

gte_missing_vehicles = gte_missing_vehicles[wanted_columns]
gte_data_missing = gte_data_missing.drop("vehicle", axis=1)
gte_data_missing_with_vehicles = pd.merge(left=gte_data_missing, right=gte_missing_vehicles, on = "team_no", how = "outer")
gte_data_missing_with_vehicles

,number,driver_number,lap_number,lap_time,lap_improvement,crossing_finish_line_in_pit,s1,s1_improvement,s2,s2_improvement,...,t6,t7,porsche,ford,flag_at_fl,team_no,lap_time_ms,lap_time_s,engine,vehicle
0,55.0,1.0,1.0,9:24.198,0.0,NaN,2:14.757,0.0,3:28.826,0.0,...,NaN,NaN,NaN,NaN,NaN,AF Corse #55,564198.0,564.198,Ferrari,Ferrari 458 Italia GT2
1,55.0,1.0,2.0,7:46.816,0.0,NaN,1:06.042,0.0,3:14.125,0.0,...,NaN,NaN,NaN,NaN,NaN,AF Corse #55,466816.0,466.816,Ferrari,Ferrari 458 Italia GT2
2,55.0,1.0,3.0,7:44.815,0.0,NaN,1:07.797,0.0,3:10.875,0.0,...,NaN,NaN,NaN,NaN,NaN,AF Corse #55,464815.0,464.815,Ferrari,Ferrari 458 Italia GT2
3,55.0,1.0,4.0,7:39.098,0.0,NaN,57.370,0.0,3:12.534,0.0,...,NaN,NaN,NaN,NaN,NaN,AF Corse #55,459098.0,459.098,Ferrari,Ferrari 458 Italia GT2
4,55.0,1.0,5.0,7:08.684,0.0,NaN,56.334,0.0,3:01.079,0.0,...,NaN,NaN,NaN,NaN,NaN,AF Corse #55,428684.0,428.684,Ferrari,Ferrari 458 Italia GT2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4979,61.0,3.0,181.0,1:48.235,0.0,NaN,34.673,0.0,36.558,0.0,...,NaN,NaN,NaN,NaN,NaN,AF Corse #61,108235.0,108.235,Ferrari,Ferrari 488 GTE Evo
4980,61.0,3.0,182.0,1:48.140,0.0,NaN,34.648,0.0,36.526,0.0,...,NaN,NaN,NaN,NaN,NaN,AF Corse #61,108140.0,108.140,Ferrari,Ferrari 488 GTE Evo
4981,61.0,3.0,183.0,1:48.574,0.0,NaN,34.849,0.0,36.660,0.0,...,NaN,NaN,NaN,NaN,NaN,AF Corse #61,108574.0,108.574,Ferrari,Ferrari 488 GTE Evo
4982,61.0,3.0,184.0,1:48.703,0.0,NaN,34.684,0.0,36.757,0.0,...,NaN,NaN,NaN,NaN,NaN,AF Corse #61,108703.0,108.703,Ferrari,Ferrari 488 GTE Evo
4983,61.0,3.0,185.0,1:48.564,0.0,NaN,34.672,0.0,36.578,0.0,...,NaN,NaN,NaN,NaN,NaN,AF Corse #61,108564.0,108.564,Ferrari,Ferrari 488 GTE Evo

In [228]:
fia_wec_data_gte_fixed = gte_data_notmissing.append(gte_data_missing_with_vehicles).reset_index(drop=True)
fia_wec_data_gte_fixed

,number,driver_number,lap_number,lap_time,lap_improvement,crossing_finish_line_in_pit,s1,s1_improvement,s2,s2_improvement,...,t6,t7,porsche,ford,vehicle,flag_at_fl,team_no,lap_time_ms,lap_time_s,engine
0,50.0,1.0,1.0,2:10.603,0.0,NaN,44.345,0.0,52.513,0.0,...,NaN,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,130603.0,130.603,Chevrolet
1,50.0,1.0,2.0,2:02.960,0.0,NaN,37.242,0.0,52.167,0.0,...,NaN,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,122960.0,122.960,Chevrolet
2,50.0,1.0,3.0,2:03.938,0.0,NaN,37.255,0.0,52.454,0.0,...,NaN,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,123938.0,123.938,Chevrolet
3,50.0,1.0,4.0,2:03.733,0.0,NaN,37.649,0.0,52.314,0.0,...,NaN,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,123733.0,123.733,Chevrolet
4,50.0,1.0,5.0,2:03.224,0.0,NaN,37.396,0.0,52.275,0.0,...,NaN,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,123224.0,123.224,Chevrolet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222809,61.0,3.0,181.0,1:48.235,0.0,NaN,34.673,0.0,36.558,0.0,...,NaN,NaN,NaN,NaN,Ferrari 488 GTE Evo,NaN,AF Corse #61,108235.0,108.235,Ferrari
222810,61.0,3.0,182.0,1:48.140,0.0,NaN,34.648,0.0,36.526,0.0,...,NaN,NaN,NaN,NaN,Ferrari 488 GTE Evo,NaN,AF Corse #61,108140.0,108.140,Ferrari
222811,61.0,3.0,183.0,1:48.574,0.0,NaN,34.849,0.0,36.660,0.0,...,NaN,NaN,NaN,NaN,Ferrari 488 GTE Evo,NaN,AF Corse #61,108574.0,108.574,Ferrari
222812,61.0,3.0,184.0,1:48.703,0.0,NaN,34.684,0.0,36.757,0.0,...,NaN,NaN,NaN,NaN,Ferrari 488 GTE Evo,NaN,AF Corse #61,108703.0,108.703,Ferrari
222813,61.0,3.0,185.0,1:48.564,0.0,NaN,34.672,0.0,36.578,0.0,...,NaN,NaN,NaN,NaN,Ferrari 488 GTE Evo,NaN,AF Corse #61,108564.0,108.564,Ferrari

In [159]:
fia_wec_data_gte_without_keating = fia_wec_data_gte_fixed[fia_wec_data_gte_fixed['team'] != 'Keating Motorsports']
fia_wec_data_gte_with_keating = fia_wec_data_gte_fixed[fia_wec_data_gte_fixed['team'] == 'Keating Motorsports']
fia_wec_data_gte_with_keating_2018 = fia_wec_data_gte_with_keating[fia_wec_data_gte_with_keating['circuit'] == 'LE_MANS_2018']
fia_wec_data_gte_with_keating_2019 = fia_wec_data_gte_with_keating[fia_wec_data_gte_with_keating['circuit'] == 'LE_MANS_2019']
fia_wec_data_gte_with_keating_2018['vehicle'] = "Ferrari 488 GTE"

fia_wec_data_with_keating_fixed = fia_wec_data_gte_with_keating_2018.append(fia_wec_data_gte_with_keating_2019)

fia_wec_data_gte_fixed = fia_wec_data_gte_without_keating.append(fia_wec_data_with_keating_fixed).reset_index(drop=True)
fia_wec_data_gte_fixed[fia_wec_data_gte_fixed['vehicle'].isna()]
fia_wec_data_gte_fixed['engine'] = fia_wec_data_gte_fixed['manufacturer']
fia_wec_data_gte_fixed

<ipython-input-159-6d72a464edfa>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fia_wec_data_gte_with_keating_2018['vehicle'] = "Ferrari 488 GTE"

,number,driver_number,lap_number,lap_time,lap_improvement,crossing_finish_line_in_pit,s1,s1_improvement,s2,s2_improvement,...,t6,t7,porsche,ford,vehicle,flag_at_fl,team_no,lap_time_ms,lap_time_s,engine
0,50.0,1.0,1.0,2:10.603,0.0,NaN,44.345,0.0,52.513,0.0,...,NaN,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,130603.0,130.603,Chevrolet
1,50.0,1.0,2.0,2:02.960,0.0,NaN,37.242,0.0,52.167,0.0,...,NaN,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,122960.0,122.960,Chevrolet
2,50.0,1.0,3.0,2:03.938,0.0,NaN,37.255,0.0,52.454,0.0,...,NaN,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,123938.0,123.938,Chevrolet
3,50.0,1.0,4.0,2:03.733,0.0,NaN,37.649,0.0,52.314,0.0,...,NaN,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,123733.0,123.733,Chevrolet
4,50.0,1.0,5.0,2:03.224,0.0,NaN,37.396,0.0,52.275,0.0,...,NaN,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,123224.0,123.224,Chevrolet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222809,85.0,2.0,330.0,3:55.968,0.0,NaN,37.231,0.0,1:30.297,0.0,...,NaN,NaN,NaN,NaN,Ford GT,NaN,Keating Motorsports #85,235968.0,235.968,Ford
222810,85.0,2.0,331.0,3:57.188,0.0,NaN,37.105,0.0,1:30.253,0.0,...,NaN,NaN,NaN,NaN,Ford GT,NaN,Keating Motorsports #85,237188.0,237.188,Ford
222811,85.0,2.0,332.0,3:58.178,0.0,NaN,37.227,0.0,1:30.844,0.0,...,NaN,NaN,NaN,NaN,Ford GT,NaN,Keating Motorsports #85,238178.0,238.178,Ford
222812,85.0,2.0,333.0,4:00.230,0.0,NaN,37.852,0.0,1:31.576,0.0,...,NaN,NaN,NaN,NaN,Ford GT,NaN,Keating Motorsports #85,240230.0,240.230,Ford
222813,85.0,2.0,334.0,4:04.206,0.0,NaN,38.379,0.0,1:32.239,0.0,...,NaN,NaN,NaN,NaN,Ford GT,NaN,Keating Motorsports #85,244206.0,244.206,Ford

In [160]:
lmp2_nas = fia_wec_data_lmp2[fia_wec_data_lmp2['vehicle'].isna()]
lmp2_nas

Empty DataFrame
Columns: [number, driver_number, lap_number, lap_time, lap_improvement, crossing_finish_line_in_pit, s1, s1_improvement, s2, s2_improvement, s3, s3_improvement, kph, elapsed, hour, s1_large, s2_large, s3_large, top_speed, driver_name, pit_time, class, group, team, manufacturer, season, circuit, round, t6, t7, porsche, ford, vehicle, flag_at_fl, team_no, lap_time_ms, lap_time_s, engine]
Index: []

[0 rows x 38 columns]

In [161]:
fia_wec_data_lmp2[fia_wec_data_lmp2['vehicle'].isna()].groupby(['team','season','circuit']).mean()

Empty DataFrame
Columns: [number, driver_number, lap_number, lap_improvement, s1_improvement, s2_improvement, s3_improvement, kph, top_speed, round, lap_time_ms, lap_time_s]
Index: []

In [162]:
wanted_columns = ['vehicle']
classification_2016 = pd.read_csv("2016_Lemans_Classification.csv", delimiter=";")
classification_2018 = pd.read_csv("2018_Lemans_Classification.csv", delimiter=";")
classification_2016.columns = classification_2016.columns.str.strip().str.lower()
classification_2018.columns = classification_2018.columns.str.strip().str.lower()

wanted_columns = ['number', 'vehicle']

lmp2_2016_classification = classification_2016[classification_2016['class']=="LMP2"]
lmp2_2016_classification = lmp2_2016_classification[wanted_columns]

lmp2_2018_classification = classification_2018[classification_2018['class']=="LMP2"]
lmp2_2018_classification = lmp2_2018_classification[wanted_columns]

lmp2_2016_nas = lmp2_nas[lmp2_nas['season'] == "2016"]
lmp2_2018_nas = lmp2_nas[lmp2_nas['season'] == "2018-2019"]
lmp2_2018_nas

Empty DataFrame
Columns: [number, driver_number, lap_number, lap_time, lap_improvement, crossing_finish_line_in_pit, s1, s1_improvement, s2, s2_improvement, s3, s3_improvement, kph, elapsed, hour, s1_large, s2_large, s3_large, top_speed, driver_name, pit_time, class, group, team, manufacturer, season, circuit, round, t6, t7, porsche, ford, vehicle, flag_at_fl, team_no, lap_time_ms, lap_time_s, engine]
Index: []

[0 rows x 38 columns]

In [163]:
lmp2_not_nas = fia_wec_data_lmp2[fia_wec_data_lmp2['vehicle'].notna()].reset_index(drop=True)
lmp2_not_nas

,number,driver_number,lap_number,lap_time,lap_improvement,crossing_finish_line_in_pit,s1,s1_improvement,s2,s2_improvement,...,t6,t7,porsche,ford,vehicle,flag_at_fl,team_no,lap_time_ms,lap_time_s,engine
0,26.0,2.0,1.0,1:57.029,0.0,NaN,38.395,0.0,47.607,0.0,...,NaN,NaN,NaN,NaN,Ligier JS P2,NaN,G-Drive Racing #26,117029.0,117.029,Nissan
1,26.0,2.0,2.0,1:50.750,0.0,NaN,33.863,0.0,46.283,0.0,...,NaN,NaN,NaN,NaN,Ligier JS P2,NaN,G-Drive Racing #26,110750.0,110.750,Nissan
2,26.0,2.0,3.0,1:50.194,0.0,NaN,33.646,0.0,45.927,0.0,...,NaN,NaN,NaN,NaN,Ligier JS P2,NaN,G-Drive Racing #26,110194.0,110.194,Nissan
3,26.0,2.0,4.0,1:50.173,0.0,NaN,33.614,2.0,45.959,0.0,...,NaN,NaN,NaN,NaN,Ligier JS P2,NaN,G-Drive Racing #26,110173.0,110.173,Nissan
4,26.0,2.0,5.0,1:50.522,0.0,NaN,33.669,0.0,45.865,0.0,...,NaN,NaN,NaN,NaN,Ligier JS P2,NaN,G-Drive Racing #26,110522.0,110.522,Nissan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157646,49.0,2.0,341.0,3:46.347,0.0,NaN,36.428,0.0,1:27.002,0.0,...,NaN,NaN,NaN,NaN,Ligier JS P2,NaN,Michael Shank Racing #49,226347.0,226.347,Honda
157647,49.0,2.0,342.0,3:45.590,0.0,NaN,35.034,0.0,1:26.707,0.0,...,NaN,NaN,NaN,NaN,Ligier JS P2,NaN,Michael Shank Racing #49,225590.0,225.590,Honda
157648,49.0,2.0,343.0,3:41.431,0.0,NaN,34.644,0.0,1:26.188,0.0,...,NaN,NaN,NaN,NaN,Ligier JS P2,NaN,Michael Shank Racing #49,221431.0,221.431,Honda
157649,49.0,2.0,344.0,3:43.548,0.0,NaN,34.879,0.0,1:26.247,0.0,...,NaN,NaN,NaN,NaN,Ligier JS P2,NaN,Michael Shank Racing #49,223548.0,223.548,Honda
157650,49.0,2.0,345.0,3:54.005,0.0,NaN,35.628,0.0,1:27.574,0.0,...,NaN,NaN,NaN,NaN,Ligier JS P2,NaN,Michael Shank Racing #49,234005.0,234.005,Honda

In [164]:
lmp2_2016_nas_with_classification = pd.merge(left = lmp2_2016_nas, right=lmp2_2016_classification, on = 'number', how = 'outer').dropna(axis=1, how="all")

In [165]:
lmp2_2018_nas_with_classification = pd.merge(left = lmp2_2018_nas, right=lmp2_2018_classification, on = 'number', how = 'outer').dropna(axis=1, how="all")

In [166]:
lmp2_nas_with_classification = lmp2_2018_nas_with_classification.append(lmp2_2016_nas_with_classification).reset_index(drop=True)
lmp2_nas_with_classification = lmp2_nas_with_classification[lmp2_nas_with_classification['manufacturer'].notna()]
lmp2_nas_with_classification['vehicle'] = lmp2_nas_with_classification['vehicle_y']
lmp2_nas_with_classification = lmp2_nas_with_classification.drop('vehicle_y', axis=1)
lmp2_nas_with_classification

KeyError: 'manufacturer'

In [ ]:
lmp2s_with_classification = lmp2_not_nas.append(lmp2_nas_with_classification).reset_index(drop=True)
wanted_columns = ["vehicle", "number", "season"]
lmp2s_with_classification.groupby('vehicle').mean()

,number,driver_number,lap_number,lap_improvement,s1_improvement,s2_improvement,s3_improvement,kph,top_speed,round,lap_time_ms,lap_time_s
vehicle,,,,,,,,,,,,
Alpine A450b - Nissan,36.000000,0.898755,114.844613,0.010828,0.020574,0.020574,0.020574,178.269031,265.077531,4.322144,180391.313481,180.391313
Alpine A460 - Nissan,35.475708,1.121070,109.537282,0.009873,0.019745,0.019745,0.019745,175.402546,270.501171,4.708236,149905.735776,149.905736
Alpine A470 - Gibson,35.898320,1.454848,120.799615,0.009800,0.019251,0.019251,0.019251,183.770004,280.553794,4.573329,159769.078404,159.769078
Aurus 01 - Gibson,25.471038,2.005632,140.675784,0.008850,0.017699,0.017699,0.017699,201.469912,294.877212,4.485519,206127.887772,206.127888
BR01 - Nissan,32.306543,0.862494,115.979374,0.009957,0.018492,0.018492,0.018492,176.556923,269.678307,4.762684,164117.883120,164.117883
Dallara P217 - Gibson,38.413152,1.810514,138.063562,0.008395,0.016790,0.016790,0.016790,190.855587,289.123862,4.446732,196073.112532,196.073113
Dome S103 - Nissan,42.000000,1.187800,94.851268,0.010966,0.021933,0.021933,0.021933,168.930021,257.724674,4.400274,149302.671693,149.302672
Gibson 015S - Nissan,40.497845,1.100575,122.869612,0.010057,0.018678,0.018678,0.018678,184.999964,269.906968,3.475934,183262.196121,183.262196
HPD ARX 03b - Honda,42.698866,1.189749,123.649581,0.008871,0.017743,0.017743,0.017743,180.005372,260.263551,4.057664,157780.795959,157.780796
LIGIER JS P2 - Nissan,34.731657,1.039292,106.270950,0.010056,0.020112,0.020112,0.020112,171.479683,263.841304,4.941527,145372.096462,145.372096
Ligier - Nissan,35.000000,0.906610,115.342857,0.010235,0.019616,0.019616,0.019616,176.328529,263.898536,4.431983,161733.414925,161.733415
Ligier JS P2 - HPD,31.188363,1.067481,116.072795,0.010096,0.019660,0.019660,0.019660,177.775558,262.570037,3.970244,187882.321732,187.882322
Ligier JS P2 - Honda,49.000000,1.118841,173.000000,0.005797,0.011594,0.011594,0.011594,201.851014,281.803478,3.000000,250609.533333,250.609533
Ligier JS P2 - Judd,30.930876,1.013825,163.259601,0.006144,0.012289,0.012289,0.012289,197.247619,284.137020,3.000000,265881.439324,265.881439
Ligier JS P2 - Nissan,30.680124,1.055353,129.308001,0.008769,0.017537,0.017537,0.017537,183.813792,269.101115,3.689258,189008.051334,189.008051
Ligier JSP217 - Gibson,36.722053,1.687792,153.206735,0.007484,0.014733,0.014733,0.014733,201.419504,298.983400,4.455800,233794.790225,233.794790
Lola B12/80 Coupe - Nissan,28.643154,0.860996,89.926003,0.013831,0.024896,0.024896,0.024896,166.549239,247.872721,3.912172,147877.773167,147.877773
Lola - Judd,30.000000,0.873810,107.502381,0.009524,0.019048,0.019048,0.019048,190.833810,264.742857,3.861905,203497.676190,203.497676
Lola B12/80 Coupe - Lotus,31.000000,0.767756,99.261364,0.011364,0.020597,0.020597,0.020597,168.954190,251.223588,4.122159,138418.077415,138.418077
Lola B12/80 Coupé - Lotus,32.000000,0.896752,90.696056,0.013921,0.025522,0.025522,0.025522,165.150580,253.534507,5.236659,120801.265661,120.801266
Morgan - Judd,38.285568,1.057982,120.512644,0.009706,0.018902,0.018902,0.018902,175.250140,256.625932,3.944317,177698.910856,177.698911
Morgan - Nissan,28.326419,1.041703,113.271179,0.010917,0.019869,0.020306,0.020306,179.907729,265.404379,3.943450,177466.249563,177.466250
Morgan Evo - SARD,43.000000,1.014214,86.463211,0.011706,0.023411,0.023411,0.023411,165.706940,257.979181,5.035953,142889.790134,142.889790
Norma MP 2000 - Judd,43.000000,0.864450,130.618926,0.010230,0.017903,0.017903,0.017903,184.401279,266.983376,2.787724,255494.838875,255.494839
Oreca 03 - Judd,40.000000,1.167123,143.547945,0.010959,0.019178,0.019178,0.019178,196.147945,280.959726,2.876712,261343.424658,261.343425
Oreca 03 - Nissan,34.147560,0.952879,118.593080,0.009553,0.018719,0.018719,0.018719,179.783372,262.416924,4.201782,159233.072683,159.233073
Oreca 03R - Judd,34.000000,1.044071,159.875131,0.006296,0.012592,0.012592,0.012592,196.594334,279.343022,3.000000,272605.401889,272.605402
Oreca 03R - Nissan,35.895879,0.937909,112.630049,0.011190,0.021152,0.021152,0.021152,178.949754,265.164786,4.079012,178188.101392,178.188101
Oreca 05 - Nissan,40.004273,1.174761,108.719840,0.010255,0.020225,0.020367,0.020367,178.667811,270.304446,4.437545,162771.210654,162.771211
Oreca 07 - Gibson,31.876008,1.781942,124.593877,0.009239,0.018169,0.018203,0.018186,186.163906,282.203905,4.361563,166804.020634,166.804021
Riley MK30 - GIBSON,43.000000,1.051282,156.500000,0.006410,0.012821,0.012821,0.012821,199.433654,299.741026,3.000000,277702.352564,277.702353
Zytek Z11SN - Nissan,40.378229,1.071822,126.989321,0.008956,0.017568,0.017568,0.017568,183.468998,261.991773,3.704444,185625.533586,185.625534

In [ ]:
len(lmp2s_with_classification) - len(fia_wec_data_lmp2)

0

In [ ]:
import pandas as pd

#why do we need these again?... i mean i guess it's nice to have

wanted_columns = ['vehicle']

lmp1_vehicles = pd.read_csv("lmp1s.csv", index_col=0)
lmp2_vehicles = pd.read_csv("lmp2s.csv", index_col=0)

lmp1_vehicles['vehicle'] = lmp1_vehicles['vehicle_actual']

lmp2_vehicles = lmp2_vehicles[wanted_columns]
lmp1_vehicles = lmp1_vehicles[wanted_columns]
lmp1_vehicles = lmp1_vehicles.drop_duplicates().reset_index(drop=True)
lmp2_vehicles = lmp2_vehicles.drop_duplicates().reset_index(drop=True)

lmp_vehicles = lmp1_vehicles.append(lmp2_vehicles).reset_index(drop=True)

lmp_vehicles_with_engine = lmp_vehicles.vehicle.str.split(" - ",expand = True).drop_duplicates().reset_index(drop=True)
lmp_vehicles_with_engine['vehicle_actual']  = lmp_vehicles_with_engine[0] + " - " +  lmp_vehicles_with_engine[1] 
lmp_vehicles_with_engine['vehicle'] = lmp_vehicles_with_engine[0]
lmp_vehicles_with_engine['engine'] = lmp_vehicles_with_engine[1]

lmp_vehicles_with_engine = lmp_vehicles_with_engine.drop([0,1],axis=1)
lmp_vehicles_with_engine

                        vehicle_actual                  vehicle        engine
0                 Alpine A480 - Gibson              Alpine A480        Gibson
1                      Audi R18 - Audi                 Audi R18          Audi
2                Audi R18 Ultra - Audi           Audi R18 Ultra          Audi
3       Audi R18 e-tron quattro - Audi  Audi R18 e-tron quattro          Audi
4             BR Engineering BR1 - AER       BR Engineering BR1           AER
5          BR Engineering BR1 - Gibson       BR Engineering BR1        Gibson
6                      CLM P1/01 - AER                CLM P1/01           AER
7                          Dome - Judd                     Dome          Judd
8              Enso CLM P1/01 - Gibson           Enso CLM P1/01        Gibson
9               Enso CLM P1/01 - Nismo           Enso CLM P1/01         Nismo
10  Glickenhaus 007 LMH - Pipo Moteurs      Glickenhaus 007 LMH  Pipo Moteurs
11                HPD ARX  03a - Honda             HPD ARX  03a         Honda
12          Lola B12/60 Coupe - Toyota        Lola B12/60 Coupe        Toyota
13       Nissan GT-R LM Nismo - Nissan     Nissan GT-R LM Nismo        Nissan
14                Oak Pescarolo - Judd            Oak Pescarolo          Judd
15                 Pescarolo 03 - Judd             Pescarolo 03          Judd
16        Porsche 919 Hybrid - Porsche       Porsche 919 Hybrid       Porsche
17               Rebellion R-One - AER          Rebellion R-One           AER
18            Rebellion R-One - Toyota          Rebellion R-One        Toyota
19              Rebellion R13 - Gibson            Rebellion R13        Gibson
20        Toyota GR010 HYBRID - Toyota      Toyota GR010 HYBRID        Toyota
21       Toyota TS 030 Hybrid - Toyota     Toyota TS 030 Hybrid        Toyota
22       Toyota TS 040 Hybrid - Toyota     Toyota TS 040 Hybrid        Toyota
23        Toyota TS050 Hybrid - Toyota      Toyota TS050 Hybrid        Toyota
24               Alpine A450b - Nissan             Alpine A450b        Nissan
25                Alpine A460 - Nissan              Alpine A460        Nissan
26                Alpine A470 - Gibson              Alpine A470        Gibson
27                   Aurus 01 - Gibson                 Aurus 01        Gibson
28                       BR01 - Nissan                     BR01        Nissan
29               Dallara P217 - Gibson             Dallara P217        Gibson
30                  Dome S103 - Nissan                Dome S103        Nissan
31                Gibson 015S - Nissan              Gibson 015S        Nissan
32                 HPD ARX 03b - Honda              HPD ARX 03b         Honda
33               Ligier JS P2 - Nissan             Ligier JS P2        Nissan
34           Ligier Morgan P2 - Nissan         Ligier Morgan P2        Nissan
35                Ligier JS P2 - Honda             Ligier JS P2         Honda
36                 Ligier JS P2 - Judd             Ligier JS P2          Judd
37              Ligier JSP217 - Gibson            Ligier JSP217        Gibson
38          Lola B12/80 Coupe - Nissan        Lola B12/80 Coupe        Nissan
39                         Lola - Judd                     Lola          Judd
40           Lola B12/80 Coupe - Lotus        Lola B12/80 Coupe         Lotus
41                       Morgan - Judd                   Morgan          Judd
42                     Morgan - Nissan                   Morgan        Nissan
43                   Morgan Evo - SARD               Morgan Evo          SARD
44                Norma MP 2000 - Judd            Norma MP 2000          Judd
45                     Oreca 03 - Judd                 Oreca 03          Judd
46                   Oreca 03 - Nissan                 Oreca 03        Nissan
47                    Oreca 03R - Judd                Oreca 03R          Judd
48                  Oreca 03R - Nissan                Oreca 03R        Nissan
49                   Oreca 05 - Nissan                 Oreca 05        Nissan
50                   Oreca 07 - Gibson                 Oreca 07        Gibson
51                 Riley MK30 - GIBSON               Riley MK30        GIBSON
52                Zytek Z11SN - Nissan              Zytek Z11SN        Nissan

In [ ]:
lmp1_vehicles = pd.read_csv("lmp1s.csv", index_col=0)
lmp2_vehicles = pd.read_csv("lmp2s.csv", index_col=0)

lmp1_vehicles = lmp1_vehicles.drop(["manufacturer", "season"], axis=1).drop_duplicates().reset_index(drop=True)
lmp2_vehicles = lmp2_vehicles.drop(["number", "season"], axis=1).drop_duplicates().reset_index(drop=True)

lmp2_vehicles['vehicle_actual'] = lmp2_vehicles['vehicle']
lmp_vehicles = lmp1_vehicles.append(lmp2_vehicles).drop_duplicates().reset_index(drop=True)

lmp_vehicles

                        vehicle                      vehicle_actual
0          Alpine A480 - Gibson                Alpine A480 - Gibson
1                      Audi R18                     Audi R18 - Audi
2                Audi R18 Ultra               Audi R18 Ultra - Audi
3       Audi R18 e-tron quattro      Audi R18 e-tron quattro - Audi
4      BR Engineering BR1 - AER            BR Engineering BR1 - AER
5   BR Engineering BR1 - Gibson         BR Engineering BR1 - Gibson
6               CLM P1/01 - AER                     CLM P1/01 - AER
7                   Dome - Judd                         Dome - Judd
8       Enso CLM P1/01 - Gibson             Enso CLM P1/01 - Gibson
9        Enso CLM P1/01 - Nismo              Enso CLM P1/01 - Nismo
10          Glickenhaus 007 LMH  Glickenhaus 007 LMH - Pipo Moteurs
11         HPD ARX  03a - Honda                HPD ARX  03a - Honda
12   Lola B12/60 Coupe - Toyota          Lola B12/60 Coupe - Toyota
13         Nissan GT-R LM Nismo       Nissan GT-R LM Nismo - Nissan
14         Oak Pescarolo - Judd                Oak Pescarolo - Judd
15          Pescarolo 03 - Judd                 Pescarolo 03 - Judd
16           Porsche 919 Hybrid        Porsche 919 Hybrid - Porsche
17        Rebellion R-One - AER               Rebellion R-One - AER
18     Rebellion R-One - Toyota            Rebellion R-One - Toyota
19       Rebellion R13 - Gibson              Rebellion R13 - Gibson
20          Toyota GR010 HYBRID        Toyota GR010 HYBRID - Toyota
21       Toyota TS 030 - Hybrid       Toyota TS 030 Hybrid - Toyota
22       Toyota TS 040 - Hybrid       Toyota TS 040 Hybrid - Toyota
23        Toyota TS050 - Hybrid        Toyota TS050 Hybrid - Toyota
24        Alpine A450b - Nissan               Alpine A450b - Nissan
25         Alpine A460 - Nissan                Alpine A460 - Nissan
26         Alpine A470 - Gibson                Alpine A470 - Gibson
27            Aurus 01 - Gibson                   Aurus 01 - Gibson
28                BR01 - Nissan                       BR01 - Nissan
29        Dallara P217 - Gibson               Dallara P217 - Gibson
30           Dome S103 - Nissan                  Dome S103 - Nissan
31         Gibson 015S - Nissan                Gibson 015S - Nissan
32          HPD ARX 03b - Honda                 HPD ARX 03b - Honda
33        Ligier JS P2 - Nissan               Ligier JS P2 - Nissan
34    Ligier Morgan P2 - Nissan           Ligier Morgan P2 - Nissan
35         Ligier JS P2 - Honda                Ligier JS P2 - Honda
36          Ligier JS P2 - Judd                 Ligier JS P2 - Judd
37       Ligier JSP217 - Gibson              Ligier JSP217 - Gibson
38   Lola B12/80 Coupe - Nissan          Lola B12/80 Coupe - Nissan
39                  Lola - Judd                         Lola - Judd
40    Lola B12/80 Coupe - Lotus           Lola B12/80 Coupe - Lotus
41                Morgan - Judd                       Morgan - Judd
42              Morgan - Nissan                     Morgan - Nissan
43            Morgan Evo - SARD                   Morgan Evo - SARD
44         Norma MP 2000 - Judd                Norma MP 2000 - Judd
45              Oreca 03 - Judd                     Oreca 03 - Judd
46            Oreca 03 - Nissan                   Oreca 03 - Nissan
47             Oreca 03R - Judd                    Oreca 03R - Judd
48           Oreca 03R - Nissan                  Oreca 03R - Nissan
49            Oreca 05 - Nissan                   Oreca 05 - Nissan
50            Oreca 07 - Gibson                   Oreca 07 - Gibson
51          Riley MK30 - GIBSON                 Riley MK30 - GIBSON
52         Zytek Z11SN - Nissan                Zytek Z11SN - Nissan

In [ ]:
lmp_vehicles_fixed = pd.merge(left = lmp_vehicles, right = lmp_vehicles_with_engine, on = "vehicle_actual", how = "outer")
lmp_vehicles_fixed['vehicle'] = lmp_vehicles_fixed['vehicle_y']
lmp_vehicles_fixed = lmp_vehicles_fixed.drop(['vehicle_x', 'vehicle_y'], axis=1)
#lmp_vehicles_fixed.to_csv('lmps.csv')

In [ ]:
lmps_fixed = pd.read_csv('lmps.csv', index_col = 0)
lmps_fixed

                 vehicle_actual        engine                  vehicle
0          Alpine A480 - Gibson        Gibson              Alpine A480
1                      Audi R18          Audi                 Audi R18
2                Audi R18 Ultra          Audi           Audi R18 Ultra
3       Audi R18 e-tron quattro          Audi  Audi R18 e-tron quattro
4      BR Engineering BR1 - AER           AER       BR Engineering BR1
5   BR Engineering BR1 - Gibson        Gibson       BR Engineering BR1
6               CLM P1/01 - AER           AER                CLM P1/01
7                   Dome - Judd          Judd                     Dome
8       ENSO CLM P1/01 - Gibson        Gibson           Enso CLM P1/01
9       Enso CLM P1/01 - Gibson        Gibson           Enso CLM P1/01
10       Enso CLM P1/01 - Nismo         Nismo           Enso CLM P1/01
11          Glickenhaus 007 LMH  Pipo Moteurs      Glickenhaus 007 LMH
12         HPD ARX  03a - Honda         Honda             HPD ARX  03a
13   Lola B12/60 Coupe - Toyota        Toyota        Lola B12/60 Coupe
14         Nissan GT-R LM Nismo        Nissan     Nissan GT-R LM Nismo
15         Oak Pescarolo - Judd          Judd            Oak Pescarolo
16          Pescarolo 03 - Judd          Judd             Pescarolo 03
17           Porsche 919 Hybrid       Porsche       Porsche 919 Hybrid
18        Rebellion R-One - AER           AER          Rebellion R-One
19     Rebellion R-One - Toyota        Toyota          Rebellion R-One
20       Rebellion R13 - Gibson        Gibson            Rebellion R13
21          Toyota GR010 HYBRID        Toyota      Toyota GR010 HYBRID
22       Toyota TS 030 - Hybrid        Toyota     Toyota TS 030 Hybrid
23       Toyota TS 040 - Hybrid        Toyota     Toyota TS 040 Hybrid
24        Toyota TS050 - Hybrid        Toyota      Toyota TS050 Hybrid
25        Alpine A450b - Nissan        Nissan             Alpine A450b
26         Alpine A460 - Nissan        Nissan              Alpine A460
27         Alpine A470 - Gibson        Gibson              Alpine A470
28            Aurus 01 - Gibson        Gibson                 Aurus 01
29                BR01 - Nissan        Nissan                     BR01
30        Dallara P217 - Gibson        Gibson             Dallara P217
31           Dome S103 - Nissan        Nissan                Dome S103
32         Gibson 015S - Nissan        Nissan              Gibson 015S
33          HPD ARX 03b - Honda         Honda              HPD ARX 03b
34        LIGIER JS P2 - Nissan        Nissan             Ligier JS P2
35              Ligier - Nissan        Nissan             Ligier JS P2
36        Ligier JS P2 - Nissan        Nissan             Ligier JS P2
37    Ligier Morgan P2 - Nissan        Nissan         Ligier Morgan P2
38           Ligier JS P2 - HPD         Honda             Ligier JS P2
38         Ligier JS P2 - Honda         Honda             Ligier JS P2
39          Ligier JS P2 - Judd          Judd             Ligier JS P2
40       Ligier JSP217 - Gibson        Gibson            Ligier JSP217
41  Lola  B12/80 Coupe - Nissan        Nissan        Lola B12/80 Coupe
42   Lola B12/80 Coupe - Nissan        Nissan        Lola B12/80 Coupe
43                  Lola - Judd          Judd                     Lola
44    Lola B12/80 Coupé - Lotus         Lotus        Lola B12/80 Coupe
45    Lola B12/80 Coupe - Lotus         Lotus        Lola B12/80 Coupe
46                Morgan - Judd          Judd                   Morgan
47              Morgan - Nissan        Nissan                   Morgan
48            Morgan Evo - SARD          SARD               Morgan Evo
49         Norma MP 2000 - Judd          Judd            Norma MP 2000
50              Oreca 03 - Judd          Judd                 Oreca 03
51            Oreca 03 - Nissan        Nissan                 Oreca 03
52             Oreca 03R - Judd          Judd                Oreca 03R
53           Oreca 03R - Nissan        Nissan                Oreca 03R
54            Oreca 05 - Nissan        Nissan                 Oreca 05
55            Oreca 07 - Gibson        Gibson                 Oreca 07
56          Riley MK30 - GIBSON        GIBSON               Riley MK30
57         Zytek Z11SN - Nissan        Nissan              Zytek Z11SN

In [ ]:
lmp2s_with_classification = lmp2s_with_classification.reset_index(drop=True)
lmp_laps = fia_wec_data_lmp1.append(lmp2s_with_classification).reset_index(drop=True)
lmp_laps

,number,driver_number,lap_number,lap_time,lap_improvement,crossing_finish_line_in_pit,s1,s1_improvement,s2,s2_improvement,...,round,t6,t7,porsche,ford,vehicle,flag_at_fl,team_no,lap_time_ms,lap_time_s
0,1,1.0,1.0,1:50.082,0.0,NaN,36.119,0.0,44.488,0.0,...,1.0,NaN,NaN,NaN,NaN,Toyota TS 040 - Hybrid,NaN,Toyota Racing #1,110082.0,110.082
1,1,1.0,2.0,1:43.499,0.0,NaN,31.573,0.0,43.488,0.0,...,1.0,NaN,NaN,NaN,NaN,Toyota TS 040 - Hybrid,NaN,Toyota Racing #1,103499.0,103.499
2,1,1.0,3.0,1:42.844,0.0,NaN,31.478,0.0,43.061,0.0,...,1.0,NaN,NaN,NaN,NaN,Toyota TS 040 - Hybrid,NaN,Toyota Racing #1,102844.0,102.844
3,1,1.0,4.0,1:42.209,2.0,NaN,31.183,2.0,42.630,2.0,...,1.0,NaN,NaN,NaN,NaN,Toyota TS 040 - Hybrid,NaN,Toyota Racing #1,102209.0,102.209
4,1,1.0,5.0,1:42.430,0.0,NaN,31.352,0.0,42.785,0.0,...,1.0,NaN,NaN,NaN,NaN,Toyota TS 040 - Hybrid,NaN,Toyota Racing #1,102430.0,102.430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256245,49,2.0,341.0,3:46.347,0.0,NaN,36.428,0.0,1:27.002,0.0,...,3.0,NaN,NaN,NaN,NaN,Ligier JS P2 - Honda,NaN,Michael Shank Racing #49,226347.0,226.347
256246,49,2.0,342.0,3:45.590,0.0,NaN,35.034,0.0,1:26.707,0.0,...,3.0,NaN,NaN,NaN,NaN,Ligier JS P2 - Honda,NaN,Michael Shank Racing #49,225590.0,225.590
256247,49,2.0,343.0,3:41.431,0.0,NaN,34.644,0.0,1:26.188,0.0,...,3.0,NaN,NaN,NaN,NaN,Ligier JS P2 - Honda,NaN,Michael Shank Racing #49,221431.0,221.431
256248,49,2.0,344.0,3:43.548,0.0,NaN,34.879,0.0,1:26.247,0.0,...,3.0,NaN,NaN,NaN,NaN,Ligier JS P2 - Honda,NaN,Michael Shank Racing #49,223548.0,223.548
256249,49,2.0,345.0,3:54.005,0.0,NaN,35.628,0.0,1:27.574,0.0,...,3.0,NaN,NaN,NaN,NaN,Ligier JS P2 - Honda,NaN,Michael Shank Racing #49,234005.0,234.005

In [ ]:
lmp_vehicles_fixed = pd.read_csv("lmps.csv", index_col=0)

In [ ]:
lmps_with_engine = pd.merge(left = lmp_laps, right = lmp_vehicles_fixed, left_on = "vehicle", right_on = "vehicle_actual",how = "outer")
lmps_with_engine_fixed = lmps_with_engine[lmps_with_engine['vehicle_x'].notna()]
lmps_with_engine_fixed['vehicle'] = lmps_with_engine_fixed['vehicle_y']
lmps_with_engine_fixed = lmps_with_engine_fixed.drop(['vehicle_x','vehicle_actual', 'vehicle_y'], axis=1)
lmps_with_engine_fixed

<ipython-input-97-44e61450b450>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lmps_with_engine_fixed['vehicle'] = lmps_with_engine_fixed['vehicle_y']

,number,driver_number,lap_number,lap_time,lap_improvement,crossing_finish_line_in_pit,s1,s1_improvement,s2,s2_improvement,...,t6,t7,porsche,ford,flag_at_fl,team_no,lap_time_ms,lap_time_s,engine,vehicle
0,1.0,1.0,1.0,1:50.082,0.0,NaN,36.119,0.0,44.488,0.0,...,NaN,NaN,NaN,NaN,NaN,Toyota Racing #1,110082.0,110.082,Toyota,Toyota TS 040 Hybrid
1,1.0,1.0,2.0,1:43.499,0.0,NaN,31.573,0.0,43.488,0.0,...,NaN,NaN,NaN,NaN,NaN,Toyota Racing #1,103499.0,103.499,Toyota,Toyota TS 040 Hybrid
2,1.0,1.0,3.0,1:42.844,0.0,NaN,31.478,0.0,43.061,0.0,...,NaN,NaN,NaN,NaN,NaN,Toyota Racing #1,102844.0,102.844,Toyota,Toyota TS 040 Hybrid
3,1.0,1.0,4.0,1:42.209,2.0,NaN,31.183,2.0,42.630,2.0,...,NaN,NaN,NaN,NaN,NaN,Toyota Racing #1,102209.0,102.209,Toyota,Toyota TS 040 Hybrid
4,1.0,1.0,5.0,1:42.430,0.0,NaN,31.352,0.0,42.785,0.0,...,NaN,NaN,NaN,NaN,NaN,Toyota Racing #1,102430.0,102.430,Toyota,Toyota TS 040 Hybrid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256245,49.0,2.0,341.0,3:46.347,0.0,NaN,36.428,0.0,1:27.002,0.0,...,NaN,NaN,NaN,NaN,NaN,Michael Shank Racing #49,226347.0,226.347,Honda,Ligier JS P2
256246,49.0,2.0,342.0,3:45.590,0.0,NaN,35.034,0.0,1:26.707,0.0,...,NaN,NaN,NaN,NaN,NaN,Michael Shank Racing #49,225590.0,225.590,Honda,Ligier JS P2
256247,49.0,2.0,343.0,3:41.431,0.0,NaN,34.644,0.0,1:26.188,0.0,...,NaN,NaN,NaN,NaN,NaN,Michael Shank Racing #49,221431.0,221.431,Honda,Ligier JS P2
256248,49.0,2.0,344.0,3:43.548,0.0,NaN,34.879,0.0,1:26.247,0.0,...,NaN,NaN,NaN,NaN,NaN,Michael Shank Racing #49,223548.0,223.548,Honda,Ligier JS P2
256249,49.0,2.0,345.0,3:54.005,0.0,NaN,35.628,0.0,1:27.574,0.0,...,NaN,NaN,NaN,NaN,NaN,Michael Shank Racing #49,234005.0,234.005,Honda,Ligier JS P2

In [ ]:
fia_wec_data_gte_fixed

,number,driver_number,lap_number,lap_time,lap_improvement,crossing_finish_line_in_pit,s1,s1_improvement,s2,s2_improvement,...,round,t6,t7,porsche,ford,vehicle,flag_at_fl,team_no,lap_time_ms,lap_time_s
0,50,1,1,2:10.603,0.0,NaN,44.345,0.0,52.513,0.0,...,1,NaN,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,130603,130.603
1,50,1,2,2:02.960,0.0,NaN,37.242,0.0,52.167,0.0,...,1,NaN,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,122960,122.960
2,50,1,3,2:03.938,0.0,NaN,37.255,0.0,52.454,0.0,...,1,NaN,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,123938,123.938
3,50,1,4,2:03.733,0.0,NaN,37.649,0.0,52.314,0.0,...,1,NaN,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,123733,123.733
4,50,1,5,2:03.224,0.0,NaN,37.396,0.0,52.275,0.0,...,1,NaN,NaN,NaN,NaN,Chevrolet Corvette C7.R,NaN,Larbre Competition #50,123224,123.224
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222809,98,2,176,2:00.136,0.0,NaN,35.565,0.0,41.630,0.0,...,1,NaN,NaN,NaN,NaN,Aston Martin Vantage GTE,GF,Northwest AMR #98,120136,120.136
222810,98,2,177,2:00.514,0.0,NaN,35.849,0.0,41.913,0.0,...,1,NaN,NaN,NaN,NaN,Aston Martin Vantage GTE,GF,Northwest AMR #98,120514,120.514
222811,98,2,178,2:00.760,0.0,NaN,35.627,0.0,41.511,0.0,...,1,NaN,NaN,NaN,NaN,Aston Martin Vantage GTE,GF,Northwest AMR #98,120760,120.760
222812,98,2,179,2:08.667,0.0,NaN,35.600,0.0,42.613,0.0,...,1,NaN,NaN,NaN,NaN,Aston Martin Vantage GTE,SF,Northwest AMR #98,128667,128.667
222813,98,2,180,24:46.859,0.0,NaN,51.685,0.0,1:22.717,0.0,...,1,NaN,NaN,NaN,NaN,Aston Martin Vantage GTE,SF,Northwest AMR #98,1486859,1486.859

In [240]:
fia_wec_data_misc[fia_wec_data_misc['manufacturer']=='Morgan']

,number,driver_number,lap_number,lap_time,lap_improvement,crossing_finish_line_in_pit,s1,s1_improvement,s2,s2_improvement,...,t6,t7,porsche,ford,vehicle,flag_at_fl,team_no,lap_time_ms,lap_time_s,engine
479144,84.0,1.0,1.0,9:01.255,0.0,NaN,1:51.726,0.0,3:24.870,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,SRT41 By OAK Racing #84,541255.0,541.255,Nissan
479145,84.0,1.0,2.0,7:49.046,0.0,NaN,1:05.442,0.0,3:10.426,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,SRT41 By OAK Racing #84,469046.0,469.046,Nissan
479146,84.0,1.0,3.0,7:44.810,0.0,NaN,1:09.836,0.0,3:05.284,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,SRT41 By OAK Racing #84,464810.0,464.810,Nissan
479147,84.0,1.0,4.0,7:39.255,0.0,NaN,1:00.299,0.0,3:09.133,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,SRT41 By OAK Racing #84,459255.0,459.255,Nissan
479148,84.0,1.0,5.0,7:07.338,0.0,NaN,1:02.404,0.0,2:54.538,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,SRT41 By OAK Racing #84,427338.0,427.338,Nissan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479454,84.0,2.0,311.0,4:05.463,0.0,B,37.431,0.0,1:30.335,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,SRT41 By OAK Racing #84,245463.0,245.463,Nissan
479455,84.0,0.0,312.0,7:48.892,0.0,NaN,4:04.389,0.0,1:37.985,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,SRT41 By OAK Racing #84,468892.0,468.892,Nissan
479456,84.0,0.0,313.0,4:31.538,0.0,NaN,43.833,0.0,1:39.886,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,SRT41 By OAK Racing #84,271538.0,271.538,Nissan
479457,84.0,0.0,314.0,4:26.092,0.0,NaN,42.089,0.0,1:40.637,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,SRT41 By OAK Racing #84,266092.0,266.092,Nissan
479458,84.0,0.0,315.0,4:28.743,0.0,NaN,43.908,0.0,1:36.557,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,SRT41 By OAK Racing #84,268743.0,268.743,Nissan

In [243]:
fia_wec_data_misc_nissan = fia_wec_data_misc[fia_wec_data_misc['manufacturer']!="Oreca"]
fia_wec_data_misc_nissan['vehicle'] = "Morgan"
fia_wec_data_misc_nissan['engine'] = "Nissan"

<ipython-input-243-4ac2b0157926>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fia_wec_data_misc_nissan['vehicle'] = "Morgan"
<ipython-input-243-4ac2b0157926>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fia_wec_data_misc_nissan['engine'] = "Nissan"

In [244]:
fia_wec_data_misc_oreca = fia_wec_data_misc[fia_wec_data_misc['manufacturer']=="Oreca"]
fia_wec_data_misc_oreca['vehicle'] = "Oreca 07"
fia_wec_data_misc_oreca['engine'] = "Gibson"

fia_wec_data_misc_fixed = fia_wec_data_misc_nissan.append(fia_wec_data_misc_oreca)
fia_wec_data_misc_fixed

<ipython-input-244-700a542de071>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fia_wec_data_misc_oreca['vehicle'] = "Oreca 07"
<ipython-input-244-700a542de071>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fia_wec_data_misc_oreca['engine'] = "Gibson"

,number,driver_number,lap_number,lap_time,lap_improvement,crossing_finish_line_in_pit,s1,s1_improvement,s2,s2_improvement,...,t6,t7,porsche,ford,vehicle,flag_at_fl,team_no,lap_time_ms,lap_time_s,engine
479064,0.0,1.0,1.0,4:21.958,0.0,NaN,57.805,0.0,1:32.907,0.0,...,0:03.843,NaN,0:21.258,0:07.847,Morgan,NaN,Highcroft Racing #0,261958.0,261.958,Nissan
479065,0.0,1.0,2.0,3:56.264,0.0,NaN,37.908,0.0,1:30.948,0.0,...,0:03.843,0:04.203,0:20.033,0:06.830,Morgan,NaN,Highcroft Racing #0,236264.0,236.264,Nissan
479066,0.0,1.0,3.0,3:56.285,0.0,NaN,39.460,0.0,1:30.659,0.0,...,0:03.635,0:04.209,0:19.571,0:06.834,Morgan,NaN,Highcroft Racing #0,236285.0,236.285,Nissan
479067,0.0,1.0,4.0,3:51.298,0.0,NaN,36.586,0.0,1:28.522,0.0,...,0:03.571,0:04.116,0:19.789,0:06.687,Morgan,NaN,Highcroft Racing #0,231298.0,231.298,Nissan
479068,0.0,1.0,5.0,3:49.693,0.0,NaN,36.421,0.0,1:28.633,0.0,...,0:03.602,0:04.100,0:19.066,0:06.688,Morgan,NaN,Highcroft Racing #0,229693.0,229.693,Nissan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479788,84.0,1.0,330.0,4:04.252,0.0,B,38.128,0.0,1:27.214,0.0,...,NaN,NaN,NaN,NaN,Oreca 07,NaN,Association SRT41 #84,244252.0,244.252,Gibson
479789,84.0,1.0,331.0,5:01.193,0.0,NaN,1:47.160,0.0,1:27.483,0.0,...,NaN,NaN,NaN,NaN,Oreca 07,NaN,Association SRT41 #84,301193.0,301.193,Gibson
479790,84.0,1.0,332.0,3:50.136,0.0,NaN,37.062,0.0,1:26.542,0.0,...,NaN,NaN,NaN,NaN,Oreca 07,NaN,Association SRT41 #84,230136.0,230.136,Gibson
479791,84.0,1.0,333.0,3:49.041,0.0,NaN,36.569,0.0,1:26.499,0.0,...,NaN,NaN,NaN,NaN,Oreca 07,NaN,Association SRT41 #84,229041.0,229.041,Gibson
479792,84.0,1.0,334.0,3:57.733,0.0,NaN,40.911,0.0,1:29.111,0.0,...,NaN,NaN,NaN,NaN,Oreca 07,NaN,Association SRT41 #84,237733.0,237.733,Gibson

In [253]:
fia_wec_data_fixed = fia_wec_data_gte_fixed.append(lmps_with_engine_fixed).append(fia_wec_data_misc_fixed).reset_index(drop=True)
fia_wec_data_fixed.to_csv("2012-2022_FIA_WEC_FULL_LAP_DATA.csv")

In [246]:
len(fia_wec_data) - len(fia_wec_data_fixed)

0