In [4]:
import numpy as np
import pandas as pd
new_data = pd.read_csv('alkamel_timing_board.csv', dtype=str)

In [5]:
#sanity check
new_data[new_data['number']=='01']

,number,driver_number,lap_number,lap_improvement,crossing_finish_line_in_pit,s1_improvement,s2_improvement,s3_improvement,kph,hour,...,event,round_event,team_no,position,class_position,int,class_int,gap,class_gap,elapsed_minutes
77106,01,2,210,0,NaN,0,0,0,206.2,17:40:58.597,...,Road Atlanta,12_Road Atlanta,#01_Cadillac Chip Ganassi Racing,5,5,0.943,0.943,3.845,3.845,329.852
77139,01,2,211,0,NaN,0,0,0,208.9,17:42:09.056,...,Road Atlanta,12_Road Atlanta,#01_Cadillac Chip Ganassi Racing,5,5,0.774,0.774,4.027,4.027,331.026
77171,01,2,212,0,NaN,0,0,0,209.1,17:43:19.442,...,Road Atlanta,12_Road Atlanta,#01_Cadillac Chip Ganassi Racing,5,5,0.371,0.371,4.063,4.063,332.2
77202,01,2,213,0,NaN,0,0,0,206.4,17:44:30.745,...,Road Atlanta,12_Road Atlanta,#01_Cadillac Chip Ganassi Racing,4,4,0.811,0.811,3.664,3.664,333.388
77234,01,2,214,0,NaN,0,0,0,205.7,17:45:42.276,...,Road Atlanta,12_Road Atlanta,#01_Cadillac Chip Ganassi Racing,4,4,0.077,0.077,0.199,4.299,334.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1327149,01,2,205,0,NaN,0,0,0,84.1,17:31:47.741,...,Road Atlanta,12_Road Atlanta,#01_Cadillac Chip Ganassi Racing,6,6,3.039,22.546,9.417,33.094,320.671
1327171,01,2,206,0,NaN,0,0,0,120.5,17:33:49.878,...,Road Atlanta,12_Road Atlanta,#01_Cadillac Chip Ganassi Racing,6,6,0.958,6.804,3.498,9.769,322.707
1327197,01,2,207,0,NaN,0,0,0,100.4,17:36:16.467,...,Road Atlanta,12_Road Atlanta,#01_Cadillac Chip Ganassi Racing,6,6,0.739,0.739,5.353,5.353,325.15
1327230,01,2,208,0,NaN,0,0,0,107,17:38:33.940,...,Road Atlanta,12_Road Atlanta,#01_Cadillac Chip Ganassi Racing,6,6,0.109,0.109,1.465,1.465,327.441
1327262,01,2,209,0,NaN,0,0,0,200.8,17:39:47.228,...,Road Atlanta,12_Road Atlanta,#01_Cadillac Chip Ganassi Racing,5,5,0.564,0.564,3.049,3.049,328.663

In [10]:
new_data_race = new_data[new_data['session']=='RACE']
new_data_race = new_data_race[new_data_race['season']=='2023']
new_data_race = new_data_race.sort_values(by=['season','championship','round','number'])
#since we're mostly working with just race data probably better to just go wtih using season + round + number
new_data_race['team_key'] = new_data_race['season'].map(str) + "_" + new_data_race['championship'] + "_" + new_data_race['round'].map(int).map(str) + "_" + new_data_race['number']
new_data_race['driver_key'] = new_data_race['season'].map(str) + "_" + new_data_race['championship'] + "_" + new_data_race['round'].map(int).map(str) + "_" + new_data_race['number'] + "_" + new_data_race['driver_number'].map(str)
new_data_race = new_data_race.reset_index(drop=True)
new_data_race

,number,driver_number,lap_number,lap_improvement,crossing_finish_line_in_pit,s1_improvement,s2_improvement,s3_improvement,kph,hour,...,team_no,position,class_position,int,class_int,gap,class_gap,elapsed_minutes,team_key,driver_key
0,10,1,1,0,NaN,0,0,0,134.2,11:31:50.593,...,#10_Eurointernational,25,9,1.026,1.026,22.849,6.812,2.019,2023_ELMS_2_10,2023_ELMS_2_10_1
1,10,1,2,0,NaN,0,0,0,80.9,11:35:17.731,...,#10_Eurointernational,25,9,1.796,1.796,27.785,9.746,5.471,2023_ELMS_2_10,2023_ELMS_2_10_1
2,10,1,3,0,NaN,0,0,0,88.8,11:38:26.520,...,#10_Eurointernational,25,9,2.191,2.191,29.57,10.584,8.618,2023_ELMS_2_10,2023_ELMS_2_10_1
3,10,1,4,0,NaN,0,0,0,99.9,11:41:14.406,...,#10_Eurointernational,25,9,1.151,1.151,30.679,10.441,11.416,2023_ELMS_2_10,2023_ELMS_2_10_1
4,10,1,5,0,NaN,0,0,0,107.7,11:43:50.039,...,#10_Eurointernational,25,9,1.761,1.761,31.296,9.952,14.01,2023_ELMS_2_10,2023_ELMS_2_10_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83380,97,2,47,0,NaN,0,0,0,167.5,19:24:52.497,...,#97_COOL Racing,31,21,0.091,0.919,83.312,69.615,104.615,2023_LeMansCup_2_97,2023_LeMansCup_2_97_2
83381,97,2,48,0,NaN,0,0,0,163.8,19:26:34.827,...,#97_COOL Racing,31,21,0.89,0.89,64.536,64.981,106.321,2023_LeMansCup_2_97,2023_LeMansCup_2_97_2
83382,97,2,49,0,NaN,0,0,0,167.1,19:28:15.130,...,#97_COOL Racing,31,21,0.86,0.86,67.222,51.153,107.993,2023_LeMansCup_2_97,2023_LeMansCup_2_97_2
83383,97,2,50,0,NaN,0,0,0,167.4,19:29:55.256,...,#97_COOL Racing,31,21,0.436,0.436,90.825,66.804,109.661,2023_LeMansCup_2_97,2023_LeMansCup_2_97_2
83384,97,2,51,0,NaN,0,0,0,164.1,19:31:37.401,...,#97_COOL Racing,30,20,0.682,0.682,76.501,74.333,111.364,2023_LeMansCup_2_97,2023_LeMansCup_2_97_2

In [11]:
def add_team_stint(new_data):
    #we take the next lap: next = df shifted by 1 row (starts from lap 2)
    new_data_next = new_data.shift(-1).fillna(0)

    #check where the team changes
    new_data['change_team'] = np.where(new_data['number'] == new_data_next['number'], 0, 1)
    new_data['change_team'] = new_data['change_team'].shift(1).fillna(0)

    new_data['change_stint'] = np.where(new_data['crossing_finish_line_in_pit'] == "B", 1, 0)
    new_data['change_stint'] = new_data['change_stint'].shift(1).fillna(0)
    #here we're creating a dictionary for the keys by pivoting it by these columns
    wanted_columns = ['team_key']
    new_data_pivoted = new_data.groupby(wanted_columns).mean().reset_index()[wanted_columns]
    new_data_pivoted['team_stint_no'] = 0

    wanted_columns = ['team_key', 'team_stint_no']
    new_data_pivoted_wc = new_data_pivoted[wanted_columns]
    new_data_pivoted_dict = new_data_pivoted_wc.to_dict('records')

    #methods for incrementing and getting values of keys in dictionaries
    def search_team_key_in_dicts(key, dict):
        for d in dict:
            if d['team_key'] == key:
                return d
        return None
    def search_driver_key_in_dicts(key, dict):
        for d in dict:
            if d['driver_key'] == key:
                return d
        return None
    def update_value_in_dicts(key, dict, col, value, type):
        if(type == 0):
            dict_key = search_driver_key_in_dicts(key, dict)
        else:
            dict_key = search_team_key_in_dicts(key, dict)
        dict_key.update({col : value})
    def increment_team_stint_value(key,dict):
        update_value_in_dicts(key, dict, 'team_stint_no', search_team_key_in_dicts(key, dict).get('team_stint_no') + 1, 1)
        return search_team_key_in_dicts(key, new_data_pivoted_dict).get('team_stint_no')
    def increment_driver_stint_value(key, dict):
        update_value_in_dicts(key, dict, 'driver_stint_no', search_driver_key_in_dicts(key, dict).get('driver_stint_no') + 1, 0)
        return search_driver_key_in_dicts(key, new_data_pivoted_dict).get('driver_stint_no')
    key = new_data.at[0, 'team_key']
    #zero everything out again, but we need to increment the very first stint
    update_value_in_dicts(key, new_data_pivoted_dict, 'team_stint_no', 1, 1)
    #getting team_stint_no
    new_data['team_stint_no'] = 0
    for i in range(0,len(new_data)):
        x = new_data.iloc[i]
        if x['change_stint'] == 1 or x['change_team'] == 1:
            increment_team_stint_value(x.team_key, new_data_pivoted_dict)
        new_data.at[x.name, 'team_stint_no'] = (search_team_key_in_dicts(x.team_key, new_data_pivoted_dict).get('team_stint_no'))

    #so using the same key parameter we zero it all out again
    wanted_columns = ['driver_key']
    new_data_pivoted = new_data.groupby(wanted_columns).mean().reset_index()[wanted_columns]
    new_data_pivoted['driver_stint_no'] = 0

    #and then convert these into a dictionary
    wanted_columns = ['driver_key', 'driver_stint_no']
    new_data_pivoted_wc = new_data_pivoted[wanted_columns]
    new_data_pivoted_dict = new_data_pivoted_wc.to_dict('records')

    #check where the driver changes, different from "crossing line in pit" since we know that the driver changes.
    new_data['change_driver'] = np.where(new_data['driver_key'] == new_data_next['driver_key'], 0, 1)
    new_data['change_driver'] = new_data['change_driver'].shift(1).fillna(0)
    #zero everything out again, but we need to increment the very first stint
    key = new_data.at[0, 'driver_key']
    update_value_in_dicts(key, new_data_pivoted_dict, 'driver_stint_no', 1, 0)

    new_data['driver_stint_no'] = 0
    for i in range(0,len(new_data)):
        x = new_data.iloc[i]
        if x['change_stint'] == 1 or x['change_team'] == 1 or x['change_driver'] == 1:
            increment_driver_stint_value(x.driver_key, new_data_pivoted_dict)
        new_data.at[x.name, 'driver_stint_no'] = (search_driver_key_in_dicts(x.driver_key, new_data_pivoted_dict).get('driver_stint_no'))
    return new_data
new_data_2023_w_team_stint = add_team_stint(new_data_race)

In [14]:
new_data_2023_w_team_stint_drop =new_data_2023_w_team_stint.drop(['change_team', 'change_stint','change_driver','team_key','driver_key'],axis=1)

In [17]:
new_data_2023_w_team_stint_drop.columns

Index(['number', 'driver_number', 'lap_number', 'lap_improvement',
       'crossing_finish_line_in_pit', 's1_improvement', 's2_improvement',
       's3_improvement', 'kph', 'hour', 'top_speed', 'driver_name', 'class',
       'group', 'team', 'manufacturer', 'flag_at_fl', 's1_seconds',
       's2_seconds', 's3_seconds', 'vehicle', 'championship', 'session_type',
       'season', 'circuit', 'round', 'key', 'lap_time_seconds',
       'elapsed_seconds', 'pit_time_seconds', 'session', 'event',
       'round_event', 'team_no', 'position', 'class_position', 'int',
       'class_int', 'gap', 'class_gap', 'elapsed_minutes', 'team_stint_no',
       'driver_stint_no', 'team_stint', 'driver_stint'],
      dtype='object')

In [16]:
new_data_2023_w_team_stint_drop['team_stint'] = new_data_2023_w_team_stint_drop['team_no'] + " Stint #" + new_data_2023_w_team_stint_drop['team_stint_no'].map(str)
new_data_2023_w_team_stint_drop['driver_stint'] = new_data_2023_w_team_stint_drop['driver_name'] + " Stint #" + new_data_2023_w_team_stint_drop['driver_stint_no'].map(str)

new_data_2023_w_team_stint_drop.to_csv('data_with_stint_no_2023.csv',index=False)